# Generated by Django 5.2.16 on 2026-08-07 17:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0002_checklist_response_definition_schema'),
        ('organizations', '0002_phase04a_shift_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_reference', models.CharField(help_text='Explicit external/business production-batch reference. Not a ProductionBatch FK — full batch master schema is deferred.', max_length=128)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_tasks', to='checklists.checklisttemplate')),
                ('checklist_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_tasks', to='checklists.checklistversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_tasks', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Checklist task',
                'verbose_name_plural': 'Checklist tasks',
                'ordering': ('-created_at',),
                'permissions': [('manage_checklisttask', 'Can manage checklist tasks')],
                'indexes': [models.Index(fields=['organization', 'status'], name='sched_task_org_status_idx'), models.Index(fields=['organization', 'batch_reference'], name='sched_task_org_batch_idx'), models.Index(fields=['checklist_template', 'status'], name='sched_task_tmpl_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'checklist_template', 'batch_reference'), name='sched_task_org_tmpl_batch_uniq')],
            },
        ),
    ]
