# Generated by Django 5.2.16 on 2026-08-09 23:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_occurrence_keys(apps, schema_editor):
    ChecklistTask = apps.get_model("scheduling", "ChecklistTask")
    for task in ChecklistTask.objects.all().iterator():
        ref = (task.batch_reference or "").strip()
        if ref:
            task.occurrence_key = f"batch:{ref}"
        else:
            task.occurrence_key = f"legacy:{task.id}"
        if not getattr(task, "trigger_type", None):
            task.trigger_type = "BATCH"
        task.save(update_fields=["occurrence_key", "trigger_type"])


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0011_phase07d_effective_version'),
        ('organizations', '0003_phase04c_organization_configuration'),
        ('scheduling', '0003_phase07c_checklist_applicability'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('trigger_type', models.CharField(choices=[('BATCH', 'Batch'), ('SHIFT_START', 'Shift start'), ('SHIFT_END', 'Shift end'), ('SCHEDULED', 'Scheduled window / interval'), ('MANUAL', 'Manual')], max_length=16)),
                ('timezone_name', models.CharField(default='UTC', help_text='IANA timezone for window/shift interpretation. Default UTC until org policy evidenced.', max_length=64)),
                ('window_start_time', models.TimeField(blank=True, help_text='Optional daily window start for SCHEDULED triggers. Not a seeded Nelna frequency.', null=True)),
                ('window_end_time', models.TimeField(blank=True, help_text='Optional daily window end for SCHEDULED triggers.', null=True)),
                ('interval_minutes', models.PositiveIntegerField(blank=True, help_text='Optional interval in minutes for SCHEDULED triggers. Blank = not interval-based. Do not invent production values.', null=True)),
                ('due_grace_minutes', models.PositiveIntegerField(blank=True, help_text='Optional grace after window end before OVERDUE. Production SLAs EVIDENCE REQUIRED.', null=True)),
                ('missed_policy', models.CharField(choices=[('MARK_MISSED', 'Mark occurrence MISSED (no NCR)'), ('CREATE_OVERDUE', 'Keep/create OVERDUE task (no NCR)'), ('SKIP', 'Skip missed occurrence (no task)')], default='MARK_MISSED', help_text='Missed-window handling. Never auto-creates NCR. Business choice DECISION REQUIRED.', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Checklist schedule',
                'verbose_name_plural': 'Checklist schedules',
                'ordering': ('organization__code', 'code'),
                'permissions': [('manage_checklistschedule', 'Can manage checklist schedules')],
            },
        ),
        migrations.RemoveConstraint(
            model_name='checklisttask',
            name='sched_task_org_tmpl_batch_uniq',
        ),
        migrations.AddField(
            model_name='checklisttask',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklisttask',
            name='occurrence_key',
            field=models.CharField(default='', help_text='Deterministic occurrence identity for idempotent generation / retries.', max_length=191),
        ),
        migrations.AddField(
            model_name='checklisttask',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Configured Shift for SHIFT_* triggers. Null for BATCH/SCHEDULED/MANUAL as applicable.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_tasks', to='organizations.shift'),
        ),
        migrations.AddField(
            model_name='checklisttask',
            name='trigger_type',
            field=models.CharField(choices=[('BATCH', 'Batch'), ('SHIFT_START', 'Shift start'), ('SHIFT_END', 'Shift end'), ('SCHEDULED', 'Scheduled window / interval'), ('MANUAL', 'Manual')], default='BATCH', max_length=16),
        ),
        migrations.AddField(
            model_name='checklisttask',
            name='window_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklisttask',
            name='window_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklisttask',
            name='batch_reference',
            field=models.CharField(blank=True, default='', help_text='Explicit external/business production-batch reference for BATCH triggers. Blank for SHIFT_*/SCHEDULED/MANUAL occurrences. Not a ProductionBatch FK — full batch master schema is deferred.', max_length=128),
        ),
        migrations.AlterField(
            model_name='checklisttask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue'), ('MISSED', 'Missed')], default='PENDING', max_length=16),
        ),
        migrations.AddField(
            model_name='checklistschedule',
            name='checklist_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='checklists.checklisttemplate'),
        ),
        migrations.AddField(
            model_name='checklistschedule',
            name='checklist_version',
            field=models.ForeignKey(blank=True, help_text='Optional exact PUBLISHED pin. Null = resolve via Phase 07D at generation time.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='checklists.checklistversion'),
        ),
        migrations.AddField(
            model_name='checklistschedule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_schedules', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='checklistschedule',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Required for SHIFT_START / SHIFT_END. Uses configured Shift rows only.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_schedules', to='organizations.shift'),
        ),
        migrations.AddField(
            model_name='checklisttask',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='Null for legacy/ad-hoc BATCH tasks created without a schedule definition.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='scheduling.checklistschedule'),
        ),
        migrations.AddIndex(
            model_name='checklisttask',
            index=models.Index(fields=['organization', 'trigger_type', 'status'], name='sched_task_org_trig_st_idx'),
        ),
        migrations.AddIndex(
            model_name='checklisttask',
            index=models.Index(fields=['schedule', 'status'], name='sched_task_sched_status_idx'),
        ),
        migrations.AddIndex(
            model_name='checklisttask',
            index=models.Index(fields=['due_at', 'status'], name='sched_task_due_status_idx'),
        ),
        migrations.RunPython(backfill_occurrence_keys, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='checklisttask',
            constraint=models.UniqueConstraint(fields=('organization', 'checklist_template', 'occurrence_key'), name='sched_task_org_tmpl_occ_uniq'),
        ),
        migrations.AddConstraint(
            model_name='checklisttask',
            constraint=models.UniqueConstraint(condition=models.Q(('batch_reference__gt', '')), fields=('organization', 'checklist_template', 'batch_reference'), name='sched_task_org_tmpl_batch_uniq'),
        ),
        migrations.AddIndex(
            model_name='checklistschedule',
            index=models.Index(fields=['organization', 'is_active', 'trigger_type'], name='sched_sched_org_act_trig_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistschedule',
            index=models.Index(fields=['shift', 'is_active'], name='sched_sched_shift_act_idx'),
        ),
        migrations.AddConstraint(
            model_name='checklistschedule',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='sched_schedule_org_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='checklistschedule',
            constraint=models.CheckConstraint(condition=models.Q(('interval_minutes__isnull', True), ('interval_minutes__gte', 1), _connector='OR'), name='sched_schedule_interval_positive'),
        ),
    ]
