# Generated by Django 5.2.16 on 2026-08-09 23:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_phase06o_product_specifications'),
        ('organizations', '0003_phase04c_organization_configuration'),
        ('scheduling', '0004_phase07e_recurring_schedules'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalBatchEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(max_length=64)),
                ('source_event_id', models.CharField(max_length=128)),
                ('external_batch_id', models.CharField(max_length=128)),
                ('external_organization_key', models.CharField(max_length=128)),
                ('external_product_key', models.CharField(blank=True, default='', max_length=128)),
                ('external_site_key', models.CharField(blank=True, default='', max_length=128)),
                ('external_shift_key', models.CharField(blank=True, default='', max_length=128)),
                ('external_line_key', models.CharField(blank=True, default='', help_text='Opaque line reference only — Production Line master is EVIDENCE REQUIRED / not modeled. Does not participate in applicability dimensions.', max_length=128)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('MAPPING_FAILED', 'Mapping failed'), ('APPLICABILITY_FAILED', 'Applicability failed'), ('VERSION_FAILED', 'Effective version failed'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='RECEIVED', max_length=24)),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('failure_message', models.CharField(blank=True, default='', max_length=512)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_batch_events', to='scheduling.checklisttask')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_batch_events', to='organizations.organization')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_batch_events', to='master_data.fgproduct')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_batch_events', to='organizations.shift')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_batch_events', to='organizations.site')),
            ],
            options={
                'verbose_name': 'External batch event',
                'verbose_name_plural': 'External batch events',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='sched_extbatchevt_status_idx'), models.Index(fields=['organization', 'status'], name='sched_extbatchevt_org_st_idx'), models.Index(fields=['external_batch_id'], name='sched_extbatchevt_batch_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_system', 'source_event_id'), name='sched_extbatchevt_src_event_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ExternalBatchMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(help_text='Stable source-system label (configured). Not a live connector credential.', max_length=64)),
                ('mapping_kind', models.CharField(choices=[('ORGANIZATION', 'Organization'), ('PRODUCT', 'FG Product'), ('SITE', 'Site'), ('SHIFT', 'Shift')], max_length=16)),
                ('external_key', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(help_text='Target organization (ORGANIZATION kind) or scope for PRODUCT/SITE/SHIFT.', on_delete=django.db.models.deletion.PROTECT, related_name='external_batch_mappings', to='organizations.organization')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_batch_mappings', to='master_data.fgproduct')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_batch_mappings', to='organizations.shift')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_batch_mappings', to='organizations.site')),
            ],
            options={
                'verbose_name': 'External batch mapping',
                'verbose_name_plural': 'External batch mappings',
                'ordering': ('source_system', 'mapping_kind', 'external_key'),
                'permissions': [('manage_externalbatchmapping', 'Can manage external batch mappings')],
                'indexes': [models.Index(fields=['source_system', 'mapping_kind', 'external_key'], name='sched_extmap_src_kind_key_idx'), models.Index(fields=['organization', 'is_active'], name='sched_extmap_org_act_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('mapping_kind', 'ORGANIZATION')), fields=('source_system', 'mapping_kind', 'external_key'), name='sched_extmap_org_src_key_uniq'), models.UniqueConstraint(condition=models.Q(('mapping_kind', 'ORGANIZATION'), _negated=True), fields=('source_system', 'mapping_kind', 'organization', 'external_key'), name='sched_extmap_scoped_src_key_uniq')],
            },
        ),
    ]
