# Generated by Django 5.2.16 on 2026-08-09 23:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0004_phase03c_roletemplate_deliverable'),
        ('checklists', '0011_phase07d_effective_version'),
        ('organizations', '0003_phase04c_organization_configuration'),
        ('scheduling', '0006_phase07g_task_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttask',
            name='due_from',
            field=models.DateTimeField(blank=True, help_text='Optional start of the due window. Before this instant the derived display state is NOT_DUE. No default SLA — leave blank if unused.', null=True),
        ),
        migrations.AddField(
            model_name='checklisttask',
            name='due_soon_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Optional configured minutes before due_at for DUE_SOON display. Null = DUE_SOON is not used. Never seed production SLA values.', null=True),
        ),
        migrations.AlterField(
            model_name='checklisttask',
            name='due_at',
            field=models.DateTimeField(blank=True, help_text='Due deadline (due_to). After this instant the derived display state is OVERDUE. Overdue is not an NCR. No invented SLA durations.', null=True),
        ),
        migrations.AddIndex(
            model_name='checklisttask',
            index=models.Index(fields=['organization', 'due_from', 'due_at'], name='sched_task_org_due_win_idx'),
        ),
    ]
