# Generated by Django 5.2.16 on 2026-08-10 00:27

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0011_phase07d_effective_version'),
        ('instruments', '0001_phase05d_equipment_calibration'),
        ('organizations', '0003_phase04c_organization_configuration'),
        ('quality', '0001_phase10a_qa_review'),
        ('recording', '0011_phase08c_recording_hardening'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchQualityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('delivery_loading_reference', models.CharField(blank=True, default='', max_length=128)),
                ('vehicle_reference', models.CharField(blank=True, default='', max_length=128)),
                ('driver_reference', models.CharField(blank=True, default='', max_length=128)),
                ('loading_bay', models.CharField(blank=True, default='', max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('seal_number', models.CharField(blank=True, default='', max_length=64)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, help_text='Optional declared quantity — not an ERP inventory balance.', max_digits=18, null=True)),
                ('quantity_uom', models.CharField(blank=True, default='', help_text='Opaque UOM label — catalogue EVIDENCE REQUIRED.', max_length=32)),
                ('batch_reference', models.CharField(blank=True, default='', max_length=128)),
                ('sub_lot_reference', models.CharField(blank=True, default='', help_text='Opaque sub-lot reference — disposition architecture not invented.', max_length=128)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_quality_records_cancelled', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_quality_records_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_quality_records_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_quality_records', to='organizations.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_quality_records_owned', to=settings.AUTH_USER_MODEL)),
                ('qa_review', models.ForeignKey(blank=True, help_text='Optional QA quality status reference — gate behaviour is policy-driven.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_quality_records', to='quality.qareview')),
                ('vehicle_inspection_checklist_version', models.ForeignKey(blank=True, help_text='Dynamic checklist definition for hygiene/pre-cooling — no hardcoded questions.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_vehicle_inspections', to='checklists.checklistversion')),
                ('vehicle_inspection_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_vehicle_inspections', to='recording.checklistsubmission')),
            ],
            options={
                'verbose_name': 'Dispatch quality record',
                'verbose_name_plural': 'Dispatch quality records',
                'ordering': ('organization__code', 'code'),
                'permissions': [('create_dispatchqualityrecord', 'Can create dispatch quality records'), ('manage_dispatchqualityrecord', 'Can manage dispatch quality records'), ('complete_dispatchqualityrecord', 'Can complete dispatch quality records'), ('manage_dispatchreleasepolicy', 'Can manage dispatch QA release policy')],
            },
        ),
        migrations.CreateModel(
            name='DispatchHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('VEHICLE_INSPECTION_LINKED', 'Vehicle inspection linked'), ('QA_REVIEW_LINKED', 'QA review linked'), ('TEMPERATURE_RECORDED', 'Temperature recorded'), ('QUANTITY_LINE_SET', 'Quantity line set'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RELEASE_GATE_EVALUATED', 'Release gate evaluated')], max_length=64)),
                ('from_status', models.CharField(blank=True, default='', max_length=16)),
                ('to_status', models.CharField(blank=True, default='', max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_history_entries', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_history_entries', to='organizations.organization')),
                ('dispatch_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_entries', to='dispatch.dispatchqualityrecord')),
            ],
            options={
                'verbose_name': 'Dispatch history entry',
                'verbose_name_plural': 'Dispatch history entries',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ColdChainTemperatureReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reading_at', models.DateTimeField()),
                ('temperature_celsius', models.DecimalField(decimal_places=3, help_text='Recorded temperature in °C — no allowable limits invented.', max_digits=8)),
                ('device_reference', models.CharField(blank=True, default='', help_text='Opaque device identifier when equipment master not linked.', max_length=128)),
                ('reading_context', models.CharField(blank=True, default='', help_text='Free-text context (e.g. probe location) — not a company fact catalogue.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_temperature_readings', to='instruments.equipment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cold_chain_temperature_readings', to='organizations.organization')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cold_chain_temperatures_recorded', to=settings.AUTH_USER_MODEL)),
                ('dispatch_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temperature_readings', to='dispatch.dispatchqualityrecord')),
            ],
            options={
                'verbose_name': 'Cold-chain temperature reading',
                'verbose_name_plural': 'Cold-chain temperature readings',
                'ordering': ('dispatch_record', 'reading_at', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='DispatchQuantityLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_reference', models.CharField(blank=True, default='', max_length=64)),
                ('product_reference', models.CharField(blank=True, default='', max_length=128)),
                ('batch_reference', models.CharField(blank=True, default='', max_length=128)),
                ('sub_lot_reference', models.CharField(blank=True, default='', max_length=128)),
                ('released_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('loaded_quantity', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('remaining_quantity', models.DecimalField(decimal_places=6, help_text='Derived: released_quantity - loaded_quantity.', max_digits=18)),
                ('unit_of_measure', models.CharField(blank=True, default='', help_text='Opaque UOM — not a seeded company catalogue.', max_length=32)),
                ('source_reference', models.CharField(blank=True, default='', help_text='Opaque source of released quantity (EVIDENCE REQUIRED for production use).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_quantity_lines_created', to=settings.AUTH_USER_MODEL)),
                ('dispatch_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quantity_lines', to='dispatch.dispatchqualityrecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_quantity_lines', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_quantity_lines_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispatch quantity line',
                'verbose_name_plural': 'Dispatch quantity lines',
                'ordering': ('dispatch_record', 'line_reference', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='DispatchReleasePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('require_qa_release_before_loading', models.BooleanField(default=False, help_text='When True, completing a dispatch quality record requires a linked QAReview with decision RELEASE. Default False — company policy EVIDENCE REQUIRED.')),
                ('notes', models.TextField(blank=True, default='', help_text='Policy rationale / evidence reference — not an approval claim.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_release_policy', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_release_policies_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispatch release policy',
                'verbose_name_plural': 'Dispatch release policies',
            },
        ),
        migrations.AddIndex(
            model_name='dispatchqualityrecord',
            index=models.Index(fields=['organization', 'status'], name='dispatch_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchqualityrecord',
            index=models.Index(fields=['organization', 'batch_reference'], name='dispatch_org_batch_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchqualityrecord',
            index=models.Index(fields=['organization', 'delivery_loading_reference'], name='dispatch_org_delivery_idx'),
        ),
        migrations.AddConstraint(
            model_name='dispatchqualityrecord',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='dispatch_org_code_ci_uniq'),
        ),
        migrations.AddIndex(
            model_name='dispatchhistoryentry',
            index=models.Index(fields=['dispatch_record', 'created_at'], name='dispatch_hist_rec_at_idx'),
        ),
        migrations.AddIndex(
            model_name='coldchaintemperaturereading',
            index=models.Index(fields=['organization', 'reading_at'], name='dispatch_temp_org_at_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchquantityline',
            index=models.Index(fields=['organization', 'batch_reference'], name='dispatch_qty_org_batch_idx'),
        ),
    ]
