# Generated by Django 5.2.16 on 2026-08-09 20:35

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capa', '0002_phase32_supplier_quality_foundation'),
        ('nonconformance', '0001_phase32_supplier_quality_foundation'),
        ('organizations', '0002_phase04a_shift_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierQualityProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_supplier_reference', models.CharField(help_text='External ERP/Bileeta supplier identifier — not a local financial master code.', max_length=128)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('quality_status', models.CharField(blank=True, default='', help_text='Optional configurable status label. Official values remain EVIDENCE REQUIRED.', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_quality_profiles', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Supplier quality profile',
                'verbose_name_plural': 'Supplier quality profiles',
                'ordering': ('organization__code', 'erp_supplier_reference'),
                'permissions': [('manage_supplierquality_qa', 'Can manage supplier quality profiles (QA)'), ('view_supplierquality_procurement', 'Can view supplier quality profiles (Procurement)')],
            },
        ),
        migrations.CreateModel(
            name='SupplierQualityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_kind', models.CharField(choices=[('INCOMING_DEFECT', 'Incoming defect'), ('AUDIT', 'Supplier audit'), ('COMPLAINT', 'Complaint'), ('OTHER', 'Other')], max_length=32)),
                ('occurred_at', models.DateTimeField()),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corrective_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_quality_events', to='capa.correctiveaction')),
                ('nonconformance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_quality_events', to='nonconformance.nonconformancerecord')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_quality_events_recorded', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_events', to='supplier_quality.supplierqualityprofile')),
            ],
            options={
                'verbose_name': 'Supplier quality event',
                'verbose_name_plural': 'Supplier quality events',
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='SupplierCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_type', models.CharField(max_length=128)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('evidence_object_key', models.CharField(blank=True, default='', help_text='Object-storage key placeholder — not a file BLOB.', max_length=512)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_certificates_verified', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='supplier_quality.supplierqualityprofile')),
            ],
            options={
                'verbose_name': 'Supplier certificate',
                'verbose_name_plural': 'Supplier certificates',
                'ordering': ('profile', '-expires_on', 'certificate_type'),
            },
        ),
        migrations.AddIndex(
            model_name='supplierqualityprofile',
            index=models.Index(fields=['organization', 'is_active'], name='sq_profile_org_act_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierqualityprofile',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('erp_supplier_reference'), models.F('organization'), name='sq_profile_org_erp_ref_ci_uniq'),
        ),
        migrations.AddIndex(
            model_name='supplierqualityevent',
            index=models.Index(fields=['profile', 'event_kind'], name='sq_event_profile_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierqualityevent',
            index=models.Index(fields=['occurred_at'], name='sq_event_occurred_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliercertificate',
            index=models.Index(fields=['expires_on'], name='sq_cert_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliercertificate',
            index=models.Index(fields=['profile', 'certificate_type'], name='sq_cert_profile_type_idx'),
        ),
    ]
