# Generated by Django 5.2.16 on 2026-08-11 06:03

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capa', '0003_phase12_ncr_hold_capa_foundation'),
        ('organizations', '0003_phase04c_organization_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RcaCause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement', models.TextField()),
                ('state', models.CharField(choices=[('POSSIBLE_CAUSE', 'Possible cause'), ('SUPPORTED_CAUSE', 'Supported cause'), ('CONFIRMED_ROOT_CAUSE', 'Confirmed root cause')], default='POSSIBLE_CAUSE', max_length=24)),
                ('suggested_by_ai', models.BooleanField(default=False)),
                ('evidence_citation', models.CharField(blank=True, default='', max_length=512)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rca_causes_confirmed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rca_causes_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RcaCapaLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corrective_action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rca_cause_links', to='capa.correctiveaction')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rca_capa_links_created', to=settings.AUTH_USER_MODEL)),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capa_links', to='rca.rcacause')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RootCauseAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rca_code', models.CharField(help_text='Owner-supplied RCA identifier (not seeded).', max_length=64)),
                ('source_kind', models.CharField(choices=[('NCR', 'Nonconformance'), ('COMPLAINT', 'Customer complaint'), ('AUDIT_FINDING', 'QMS audit finding'), ('CAPA', 'CAPA'), ('OTHER', 'Other owner-cited source')], max_length=16)),
                ('source_citation', models.CharField(max_length=512)),
                ('linked_object_id', models.UUIDField(blank=True, null=True)),
                ('problem_statement', models.TextField()),
                ('containment_reference', models.TextField(blank=True, default='', help_text='Optional immediate containment citation. Does not open or close NCR/CAPA.')),
                ('facilitator_reference', models.CharField(blank=True, default='', max_length=128)),
                ('started_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In progress'), ('ROOT_CAUSE_CONFIRMED', 'Root cause confirmed'), ('VERIFIED', 'Verification recorded'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=24)),
                ('confirmed_root_cause_text', models.TextField(blank=True, default='')),
                ('verification_notes', models.TextField(blank=True, default='')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rca_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rca_created', to=settings.AUTH_USER_MODEL)),
                ('facilitator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rca_facilitated', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='root_cause_analyses', to='organizations.organization')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rca_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Root cause analysis',
                'verbose_name_plural': 'Root cause analyses',
                'permissions': [('view_rca', 'Can view root-cause analyses'), ('manage_rca', 'Can create and edit RCA records and hypotheses'), ('confirm_rca', 'Can confirm a human-supported root cause'), ('link_rca_capa', 'Can link a confirmed root cause to CAPA')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RcaParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_reference', models.CharField(blank=True, default='', max_length=128)),
                ('role_note', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rca_participants_added', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rca_participations', to=settings.AUTH_USER_MODEL)),
                ('rca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='rca.rootcauseanalysis')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RcaFiveWhyStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('why_question', models.CharField(max_length=512)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rca_five_why_created', to=settings.AUTH_USER_MODEL)),
                ('rca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='five_why_steps', to='rca.rootcauseanalysis')),
            ],
            options={
                'ordering': ('sequence',),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RcaFishboneEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('PEOPLE', 'People'), ('METHOD', 'Method'), ('MACHINE', 'Machine'), ('MATERIAL', 'Material'), ('MEASUREMENT', 'Measurement'), ('ENVIRONMENT', 'Environment'), ('OTHER', 'Other owner-cited category')], max_length=16)),
                ('category_label', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rca_fishbone_created', to=settings.AUTH_USER_MODEL)),
                ('rca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fishbone_entries', to='rca.rootcauseanalysis')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RcaEvidenceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('citation', models.CharField(max_length=512)),
                ('linked_object_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence_links', to='rca.rcacause')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rca_evidence_created', to=settings.AUTH_USER_MODEL)),
                ('rca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_links', to='rca.rootcauseanalysis')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RcaEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=512)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rca_events', to=settings.AUTH_USER_MODEL)),
                ('rca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='rca.rootcauseanalysis')),
            ],
            options={
                'ordering': ('created_at',),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='rcacause',
            name='rca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='causes', to='rca.rootcauseanalysis'),
        ),
        migrations.AddIndex(
            model_name='rootcauseanalysis',
            index=models.Index(fields=['organization', 'status'], name='rca_org_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='rootcauseanalysis',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('rca_code'), models.F('organization'), name='rca_org_code_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='rcafivewhystep',
            constraint=models.UniqueConstraint(fields=('rca', 'sequence'), name='rca_five_why_sequence_uniq'),
        ),
        migrations.AddIndex(
            model_name='rcaevent',
            index=models.Index(fields=['rca', 'created_at'], name='rca_event_created_idx'),
        ),
    ]
