# Generated by Django 5.2.16 on 2026-08-11 05:25

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capa', '0003_phase12_ncr_hold_capa_foundation'),
        ('change_control', '0001_phase44_change_control'),
        ('document_control', '0001_phase43_document_control'),
        ('organizations', '0003_phase04c_organization_configuration'),
        ('training', '0001_phase05e_training_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityRisk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_code', models.CharField(help_text='Owner-supplied risk identifier (not seeded).', max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('category_code', models.CharField(blank=True, default='', help_text='Owner-configured category shell. Not a seeded Nelna taxonomy.', max_length=64)),
                ('cause', models.TextField(blank=True, default='')),
                ('potential_impact', models.TextField(blank=True, default='')),
                ('existing_control', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('owner_reference', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('UNDER_REVIEW', 'Under review'), ('ACCEPTED', 'Accepted (residual)'), ('MITIGATING', 'Mitigating'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('acceptance_rationale', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_risks_accepted', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_risks_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_risks_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_risks', to='organizations.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_risks_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quality risk',
                'verbose_name_plural': 'Quality risks',
                'permissions': [('view_qualityrisk', 'Can view quality risks'), ('manage_qualityrisk', 'Can create and maintain quality risks'), ('assess_qualityrisk', 'Can record historical risk assessments'), ('accept_qualityrisk', 'Can accept residual quality risk'), ('manage_qualityriskpolicy', 'Can configure owner-cited scoring policy')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QualityRiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('likelihood_input', models.CharField(blank=True, default='', max_length=64)),
                ('severity_input', models.CharField(blank=True, default='', max_length=64)),
                ('detectability_input', models.CharField(blank=True, default='', max_length=64)),
                ('exposure_input', models.CharField(blank=True, default='', max_length=64)),
                ('residual_risk_input', models.CharField(blank=True, default='', max_length=64)),
                ('computed_score_text', models.CharField(blank=True, default='', help_text='Owner-supplied score text. Allowed only when scoring_enabled.', max_length=64)),
                ('method_citation', models.CharField(blank=True, default='', max_length=512)),
                ('notes', models.TextField(blank=True, default='')),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_risk_assessments', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='quality_risks.qualityrisk')),
            ],
            options={
                'ordering': ('version_number',),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QualityRiskCategoryConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_risk_categories_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_risk_categories', to='organizations.organization')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QualityRiskEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=512)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_risk_events', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='quality_risks.qualityrisk')),
            ],
            options={
                'ordering': ('created_at',),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QualityRiskLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_kind', models.CharField(choices=[('PRODUCT', 'Product'), ('PROCESS', 'Process'), ('HACCP', 'HACCP'), ('SUPPLIER', 'Supplier'), ('EQUIPMENT', 'Equipment'), ('SYSTEM_FEATURE', 'System feature'), ('NCR', 'Nonconformance'), ('CAPA', 'CAPA'), ('AUDIT', 'QMS audit'), ('CHANGE_CONTROL', 'Change control')], max_length=32)),
                ('linked_object_id', models.UUIDField(blank=True, null=True)),
                ('citation', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_risk_links_created', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='quality_risks.qualityrisk')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QualityRiskMitigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mitigation_kind', models.CharField(choices=[('CAPA', 'CAPA'), ('CHANGE_REQUEST', 'Change request'), ('TRAINING', 'Training'), ('DOCUMENT', 'Controlled document'), ('CONTROL', 'Control')], max_length=16)),
                ('summary', models.CharField(max_length=512)),
                ('citation', models.CharField(blank=True, default='', max_length=512)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_risk_mitigations', to='change_control.qualitychangerequest')),
                ('corrective_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_risk_mitigations', to='capa.correctiveaction')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_risk_mitigations_created', to=settings.AUTH_USER_MODEL)),
                ('document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_risk_mitigations', to='document_control.qualitydocumentversion')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_risk_mitigations_owned', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mitigations', to='quality_risks.qualityrisk')),
                ('training_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_risk_mitigations', to='training.trainingrecord')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QualityRiskReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField()),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_risk_reviews', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='quality_risks.qualityrisk')),
            ],
            options={
                'ordering': ('reviewed_at',),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QualityRiskScoringPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scoring_enabled', models.BooleanField(default=False)),
                ('formula_citation', models.CharField(blank=True, default='', help_text='Official owner-cited scoring method. Empty until APR-072.', max_length=512)),
                ('high_rated_codes', models.JSONField(blank=True, default=list, help_text='Owner-supplied residual-risk input codes treated as high-rated. Empty default.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_risk_scoring_policies', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_risk_scoring_policies_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='qualityrisk',
            index=models.Index(fields=['organization', 'status'], name='qr_risk_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityrisk',
            index=models.Index(fields=['organization', 'next_review_date'], name='qr_risk_org_review_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualityrisk',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('risk_code'), models.F('organization'), name='quality_risk_org_code_ci_uniq'),
        ),
        migrations.AddIndex(
            model_name='qualityriskassessment',
            index=models.Index(fields=['risk', 'assessed_at'], name='qr_assess_risk_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualityriskassessment',
            constraint=models.UniqueConstraint(fields=('risk', 'version_number'), name='quality_risk_assessment_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='qualityriskcategoryconfig',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='quality_risk_category_org_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='qualityriskevent',
            index=models.Index(fields=['risk', 'created_at'], name='qr_event_risk_created_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityrisklink',
            index=models.Index(fields=['risk', 'link_kind'], name='qr_link_risk_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualityriskscoringpolicy',
            constraint=models.UniqueConstraint(fields=('organization',), name='quality_risk_scoring_policy_org_uniq'),
        ),
    ]
