import Joi from "joi";

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid("development", "test", "production").default("development"),
  PORT: Joi.number().default(3000),
  CORS_ORIGIN: Joi.string().default("http://localhost:3001"),
  FRONTEND_URL: Joi.string().uri().default("http://localhost:3001"),
  DATABASE_URL: Joi.string().required(),
  REDIS_URL: Joi.string().empty("").default(""),
  MONGODB_URI: Joi.string().allow(""),
  MONGO_SYNC_ON_STARTUP: Joi.boolean().default(false),
  JWT_SECRET: Joi.string().empty(""),
  JWT_ACCESS_SECRET: Joi.string().empty(""),
  JWT_REFRESH_SECRET: Joi.string().empty(""),
  JWT_ACCESS_EXPIRES: Joi.string().default("15m"),
  JWT_REFRESH_EXPIRES: Joi.string().default("7d"),
  STRIPE_SECRET_KEY: Joi.string().allow(""),
  STRIPE_WEBHOOK_SECRET: Joi.string().allow(""),
  GOOGLE_CLIENT_ID: Joi.string().allow(""),
  GOOGLE_CLIENT_SECRET: Joi.string().allow(""),
  GOOGLE_CALLBACK_URL: Joi.string().allow(""),
  RAPIDAPI_GOOGLE_MAP_PLACES_KEY: Joi.string().allow(""),
  SENDGRID_API_KEY: Joi.string().allow(""),
  SMTP_HOST: Joi.string().allow(""),
  SMTP_PORT: Joi.number().allow(""),
  SMTP_USER: Joi.string().allow(""),
  SMTP_PASS: Joi.string().allow(""),
  SMTP_FROM: Joi.string().allow(""),
  TWILIO_ACCOUNT_SID: Joi.string().allow(""),
  TWILIO_AUTH_TOKEN: Joi.string().allow(""),
  TWILIO_PHONE_NUMBER: Joi.string().allow(""),
  RAPIDAPI_COPILOT_API_KEY: Joi.string().allow(""),
  RAPIDAPI_COPILOT_HOST: Joi.string().default("copilot5.p.rapidapi.com"),
  RAPIDAPI_QR_CODE_API_KEY: Joi.string().allow(""),
  RAPIDAPI_QR_CODE_HOST: Joi.string().default(
    "simple-qr-code-generator-cheap-and-efficient.p.rapidapi.com"
  ),
  RAPIDAPI_QR_CODE_COLOR: Joi.string().allow(""),
  RAPIDAPI_QR_CODE_BG_COLOR: Joi.string().allow(""),
  CLOUDINARY_CLOUD_NAME: Joi.string().allow(""),
  CLOUDINARY_API_KEY: Joi.string().allow(""),
  CLOUDINARY_API_SECRET: Joi.string().allow(""),
  CLOUDINARY_ASSET_FOLDER: Joi.string().default("maintainpro/asset-documents"),
  MINIO_ENDPOINT: Joi.string().allow(""),
  MINIO_PORT: Joi.number().allow("").default(9000),
  MINIO_USE_SSL: Joi.boolean().default(false),
  MINIO_ACCESS_KEY: Joi.string().allow(""),
  MINIO_SECRET_KEY: Joi.string().allow(""),
  MINIO_BUCKET: Joi.string().allow("")
})
  .or("JWT_SECRET", "JWT_ACCESS_SECRET")
  .or("JWT_SECRET", "JWT_REFRESH_SECRET");
