# Generated by Django 5.2.16 on 2026-08-09 20:35

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capa', '0001_phase32_supplier_quality_foundation'),
        ('nonconformance', '0001_phase32_supplier_quality_foundation'),
        ('organizations', '0002_phase04a_shift_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctiveaction',
            name='nonconformance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrective_actions', to='nonconformance.nonconformancerecord'),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrective_actions', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['organization', 'status'], name='capa_org_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='correctiveaction',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='capa_org_code_ci_uniq'),
        ),
    ]
