# Generated by Django 5.2.16 on 2026-08-10 01:40

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0011_phase07d_effective_version'),
        ('master_data', '0003_phase06o_product_specifications'),
        ('organizations', '0003_phase04c_organization_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('control_point_type', models.CharField(choices=[('CCP', 'CCP (evidence-gated)'), ('OPRP', 'OPRP (evidence-gated)'), ('PRP', 'PRP (evidence-gated)')], max_length=8)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'HACCP control point',
                'verbose_name_plural': 'HACCP control points',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('BIOLOGICAL', 'Biological'), ('CHEMICAL', 'Chemical'), ('PHYSICAL', 'Physical'), ('ALLERGEN', 'Allergen')], max_length=16)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'HACCP hazard',
                'verbose_name_plural': 'HACCP hazards',
                'ordering': ('process_step__sequence', 'code'),
            },
        ),
        migrations.CreateModel(
            name='CorrectiveActionReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('procedure_reference', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('auto_raise_hold_enabled', models.BooleanField(default=False)),
                ('auto_raise_ncr_enabled', models.BooleanField(default=False)),
                ('control_point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_action_ref', to='haccp.controlpoint')),
            ],
            options={
                'verbose_name': 'HACCP corrective action reference',
                'verbose_name_plural': 'HACCP corrective action references',
            },
        ),
        migrations.CreateModel(
            name='CriticalLimitReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_reference', models.CharField(blank=True, default='', help_text='Opaque approved rule/document reference code — not a limit value.', max_length=255)),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('precision', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('boundary_semantics', models.CharField(choices=[('INCLUSIVE', 'Inclusive'), ('EXCLUSIVE', 'Exclusive'), ('LOWER_INCLUSIVE_UPPER_EXCLUSIVE', 'Lower inclusive / upper exclusive'), ('LOWER_EXCLUSIVE_UPPER_INCLUSIVE', 'Lower exclusive / upper inclusive'), ('QUALITATIVE', 'Qualitative / non-numeric')], default='INCLUSIVE', max_length=40)),
                ('lower_bound', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('upper_bound', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('source_reference', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('control_point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='critical_limit', to='haccp.controlpoint')),
                ('specification_parameter', models.ForeignKey(blank=True, help_text='Optional pin to an approved specification parameter — not invented bounds.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='haccp_critical_limit_refs', to='master_data.specificationparameter')),
            ],
            options={
                'verbose_name': 'HACCP critical limit reference',
                'verbose_name_plural': 'HACCP critical limit references',
            },
        ),
        migrations.CreateModel(
            name='HaccpPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='haccp_plans_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='haccp_plans', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'HACCP plan',
                'verbose_name_plural': 'HACCP plans',
                'ordering': ('organization__code', 'code'),
                'permissions': [('manage_haccpplan', 'Can draft/edit HACCP plan versions'), ('approve_haccpplan', 'Can approve/retire HACCP plan versions'), ('view_haccp', 'Can view HACCP plans (read-only)')],
            },
        ),
        migrations.CreateModel(
            name='HaccpPlanVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('RETIRED', 'Retired')], default='DRAFT', max_length=16)),
                ('change_summary', models.TextField(blank=True, default='')),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='haccp_versions_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='haccp_versions_created', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='haccp.haccpplan')),
            ],
            options={
                'verbose_name': 'HACCP plan version',
                'verbose_name_plural': 'HACCP plan versions',
                'ordering': ('plan__code', '-version_number'),
            },
        ),
        migrations.CreateModel(
            name='HaccpHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='haccp_history_actions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='haccp_history_entries', to='organizations.organization')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='haccp.haccpplan')),
                ('plan_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='haccp.haccpplanversion')),
            ],
            options={
                'verbose_name': 'HACCP history entry',
                'verbose_name_plural': 'HACCP history entries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='controlpoint',
            name='plan_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_points', to='haccp.haccpplanversion'),
        ),
        migrations.CreateModel(
            name='ChecklistItemHaccpBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frozen_haccp_context', models.JSONField(blank=True, default=dict, help_text='Immutable snapshot of plan version + control-point identity at bind time; historical submissions must rely on this, not live plan edits.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='haccp_binding', to='checklists.checklistitem')),
                ('control_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_bindings', to='haccp.controlpoint')),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_bindings', to='haccp.haccpplanversion')),
            ],
            options={
                'verbose_name': 'Checklist item HACCP binding',
                'verbose_name_plural': 'Checklist item HACCP bindings',
            },
        ),
        migrations.AddField(
            model_name='controlpoint',
            name='hazard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_points', to='haccp.hazard'),
        ),
        migrations.CreateModel(
            name='ControlMeasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_measures', to='haccp.hazard')),
            ],
            options={
                'verbose_name': 'HACCP control measure',
                'verbose_name_plural': 'HACCP control measures',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='MonitoringRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_reference', models.CharField(blank=True, default='', max_length=255)),
                ('frequency_reference', models.CharField(blank=True, default='', max_length=255)),
                ('responsible_category', models.CharField(blank=True, default='', max_length=128)),
                ('required_equipment_reference', models.CharField(blank=True, default='', max_length=255)),
                ('verification_requirement', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('control_point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_rule', to='haccp.controlpoint')),
            ],
            options={
                'verbose_name': 'HACCP monitoring rule',
                'verbose_name_plural': 'HACCP monitoring rules',
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, default='')),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='haccp.haccpplanversion')),
            ],
            options={
                'verbose_name': 'HACCP process step',
                'verbose_name_plural': 'HACCP process steps',
                'ordering': ('sequence', 'code'),
            },
        ),
        migrations.AddField(
            model_name='hazard',
            name='process_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazards', to='haccp.processstep'),
        ),
        migrations.AddField(
            model_name='controlpoint',
            name='process_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_points', to='haccp.processstep'),
        ),
        migrations.AddConstraint(
            model_name='haccpplan',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='haccp_plan_org_code_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='haccpplanversion',
            constraint=models.UniqueConstraint(fields=('plan', 'version_number'), name='haccp_plan_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='controlmeasure',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('hazard'), name='haccp_measure_hazard_code_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='processstep',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('plan_version'), name='haccp_step_version_code_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='hazard',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('process_step'), name='haccp_hazard_step_code_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='controlpoint',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('plan_version'), name='haccp_cp_version_code_ci_uniq'),
        ),
    ]
