# Generated by Django 5.2.16 on 2026-08-10 03:02

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0012_phase25_device_traceability'),
        ('master_data', '0003_phase06o_product_specifications'),
        ('organizations', '0003_phase04c_organization_configuration'),
        ('recording', '0012_phase25_device_traceability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('RETIRED', 'Retired')], default='DRAFT', max_length=16)),
                ('change_summary', models.TextField(blank=True, default='')),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('approval_reference', models.CharField(blank=True, default='', help_text='Opaque company approval / document-control reference — not invented.', max_length=255)),
                ('date_code_format_reference', models.CharField(blank=True, default='', help_text='Opaque approved date-code format/rule reference — no formula invented.', max_length=255)),
                ('batch_code_format_reference', models.CharField(blank=True, default='', help_text='Opaque batch-code format reference — no formula invented.', max_length=255)),
                ('evidence_object_key', models.CharField(blank=True, default='', help_text='Optional private-storage object key for artwork PDF/image evidence.', max_length=512)),
                ('evidence_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('evidence_content_type', models.CharField(blank=True, default='', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artwork_versions_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artwork_versions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artwork version',
                'verbose_name_plural': 'Artwork versions',
                'ordering': ('artwork__code', '-version_number'),
            },
        ),
        migrations.CreateModel(
            name='ArtworkVerificationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_reference', models.CharField(blank=True, default='', max_length=128)),
                ('mfg_date', models.DateField(blank=True, help_text='Recorded MFG date when company procedure requires it — not calculated.', null=True)),
                ('exp_date', models.DateField(blank=True, help_text='Recorded EXP date when supplied — shelf-life calculation not implemented.', null=True)),
                ('batch_code', models.CharField(blank=True, default='', max_length=128)),
                ('date_code_format_reference_snapshot', models.CharField(blank=True, default='', help_text='Copied from artwork version at verification time.', max_length=255)),
                ('frozen_artwork_context', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('checklist_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artwork_verifications', to='recording.checklistsubmission')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artwork_verification_records', to='organizations.organization')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artwork_verifications_recorded', to=settings.AUTH_USER_MODEL)),
                ('artwork_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_records', to='packaging.artworkversion')),
            ],
            options={
                'verbose_name': 'Artwork verification record',
                'verbose_name_plural': 'Artwork verification records',
                'ordering': ('-recorded_at',),
            },
        ),
        migrations.CreateModel(
            name='ChecklistItemArtworkBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frozen_artwork_context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artwork_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_bindings', to='packaging.artworkversion')),
                ('checklist_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artwork_binding', to='checklists.checklistitem')),
            ],
            options={
                'verbose_name': 'Checklist item artwork binding',
                'verbose_name_plural': 'Checklist item artwork bindings',
            },
        ),
        migrations.CreateModel(
            name='PackagingArtwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Company-assigned artwork code — not invented by the system.', max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('pack_configuration_label', models.CharField(blank=True, default='', help_text='Opaque pack-configuration label — catalogue EVIDENCE REQUIRED.', max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packaging_artworks_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packaging_artworks', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packaging_artworks', to='master_data.fgproduct')),
            ],
            options={
                'verbose_name': 'Packaging artwork',
                'verbose_name_plural': 'Packaging artworks',
                'ordering': ('organization__code', 'code'),
                'permissions': [('manage_packagingartwork', 'Can draft/edit packaging artwork versions (Product Master)'), ('approve_packagingartwork', 'Can approve/retire packaging artwork versions (Document Control)'), ('view_packaging', 'Can view packaging artwork (read-only)')],
            },
        ),
        migrations.AddField(
            model_name='artworkversion',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='packaging.packagingartwork'),
        ),
        migrations.CreateModel(
            name='PackagingHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_history_actions', to=settings.AUTH_USER_MODEL)),
                ('artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='packaging.packagingartwork')),
                ('artwork_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='packaging.artworkversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packaging_history_entries', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Packaging history entry',
                'verbose_name_plural': 'Packaging history entries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LineClearanceArtworkHook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('line_code', models.CharField(blank=True, default='', help_text='Opaque line label — Line master EVIDENCE REQUIRED.', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artwork_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_clearance_hooks', to='packaging.artworkversion')),
                ('checklist_template', models.ForeignKey(blank=True, help_text='Optional future line-clearance checklist template.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='line_clearance_artwork_hooks', to='checklists.checklisttemplate')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_clearance_artwork_hooks_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_clearance_artwork_hooks', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Line clearance artwork hook',
                'verbose_name_plural': 'Line clearance artwork hooks',
                'ordering': ('organization__code', 'code'),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='packaging_line_clearance_hook_org_code_ci_uniq')],
            },
        ),
        migrations.AddConstraint(
            model_name='packagingartwork',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='packaging_artwork_org_code_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='artworkversion',
            constraint=models.UniqueConstraint(fields=('artwork', 'version_number'), name='packaging_artwork_version_uniq'),
        ),
    ]
