# Generated by Django 5.2.16 on 2026-08-11 04:18

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_phase04c_organization_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_code', models.CharField(help_text='Owner-supplied change identifier (not seeded).', max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('ASSESSMENT', 'Assessment'), ('APPROVED', 'Approved'), ('IMPLEMENTING', 'Implementing'), ('VERIFICATION', 'Verification'), ('CLOSED', 'Closed')], default='REQUESTED', max_length=16)),
                ('requested_at', models.DateTimeField()),
                ('target_date', models.DateField(blank=True, null=True)),
                ('risk_impact_assessment', models.TextField(blank=True, default='')),
                ('approval_reference', models.CharField(blank=True, default='', max_length=255)),
                ('verification_reference', models.CharField(blank=True, default='', max_length=255)),
                ('engineering_complete', models.BooleanField(default=False, help_text='Engineering completion does not constitute business approval.')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_changes_approved', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_changes_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_changes_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_change_requests', to='organizations.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_changes_owned', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_changes_requested', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_changes_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quality change request',
                'verbose_name_plural': 'Quality change requests',
                'permissions': [('view_qualitychange', 'Can view quality change requests'), ('create_qualitychange', 'Can create quality change requests'), ('assess_qualitychange', 'Can assess quality change impact'), ('approve_qualitychange', 'Can approve quality change requests'), ('implement_qualitychange', 'Can record implementation of approved changes'), ('verify_qualitychange', 'Can verify and close quality change requests')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QualityChangeImplementationLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('implemented_kind', models.CharField(choices=[('DOCUMENT_VERSION', 'Document version'), ('CHECKLIST_VERSION', 'Checklist version'), ('SPECIFICATION_VERSION', 'Specification version'), ('HACCP_PLAN_VERSION', 'HACCP plan version'), ('CONFIGURATION', 'Configuration'), ('ERP_MAPPING', 'ERP mapping'), ('OTHER', 'Other deployed reference')], max_length=32)),
                ('implemented_object_id', models.UUIDField(blank=True, null=True)),
                ('implemented_reference', models.CharField(max_length=255)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('recorded_at', models.DateTimeField()),
                ('does_not_constitute_approval', models.BooleanField(default=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_change_implementations_recorded', to=settings.AUTH_USER_MODEL)),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='implementation_links', to='change_control.qualitychangerequest')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QualityChangeImpactAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quality_impact', models.TextField()),
                ('food_safety_impact', models.TextField()),
                ('technical_impact', models.TextField()),
                ('training_impact', models.TextField()),
                ('validation_requirement', models.TextField()),
                ('data_migration_impact', models.TextField()),
                ('assessed_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_change_assessments', to=settings.AUTH_USER_MODEL)),
                ('change_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='impact_assessment', to='change_control.qualitychangerequest')),
            ],
            options={
                'verbose_name': 'Quality change impact assessment',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QualityChangeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=512)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_change_events', to=settings.AUTH_USER_MODEL)),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='change_control.qualitychangerequest')),
            ],
            options={
                'ordering': ('created_at',),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QualityChangeAffectedLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('linked_kind', models.CharField(choices=[('PRODUCT', 'Product'), ('SPECIFICATION', 'Specification'), ('CHECKLIST', 'Checklist'), ('HACCP_PLAN', 'HACCP plan'), ('EQUIPMENT', 'Equipment'), ('PROCESS', 'Process'), ('ERP_MAPPING', 'ERP mapping'), ('DOCUMENT', 'Document'), ('TRAINING', 'Training'), ('SITE_LINE', 'Site / line')], max_length=32)),
                ('linked_object_id', models.UUIDField(blank=True, null=True)),
                ('linked_reference', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_change_affected_links_created', to=settings.AUTH_USER_MODEL)),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affected_links', to='change_control.qualitychangerequest')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='qualitychangerequest',
            index=models.Index(fields=['organization', 'status'], name='change_cont_organiz_37dddf_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualitychangerequest',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('change_code'), models.F('organization'), name='quality_change_org_code_ci_uniq'),
        ),
        migrations.AddIndex(
            model_name='qualitychangeevent',
            index=models.Index(fields=['change_request', 'created_at'], name='change_cont_change__16ef2e_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualitychangeaffectedlink',
            constraint=models.UniqueConstraint(fields=('change_request', 'linked_kind', 'linked_object_id', 'linked_reference'), name='quality_change_affected_link_uniq'),
        ),
    ]
