# Generated by Django 5.2.16 on 2026-08-10 01:59

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0011_phase07d_effective_version'),
        ('master_data', '0003_phase06o_product_specifications'),
        ('organizations', '0003_phase04c_organization_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('external_standard_source', models.CharField(blank=True, default='', help_text='Opaque company-declared source name/version only — never a copied ISO table.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sampling_plans_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sampling_plans', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Sampling plan',
                'verbose_name_plural': 'Sampling plans',
                'ordering': ('organization__code', 'code'),
                'permissions': [('manage_samplingplan', 'Can draft/edit sampling plan versions'), ('publish_samplingplan', 'Can approve/retire sampling plan versions'), ('view_sampling', 'Can view sampling plans (read-only)')],
            },
        ),
        migrations.CreateModel(
            name='SamplingPlanVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('RETIRED', 'Retired')], default='DRAFT', max_length=16)),
                ('change_summary', models.TextField(blank=True, default='')),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sampling_versions_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sampling_versions_created', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='sampling.samplingplan')),
            ],
            options={
                'verbose_name': 'Sampling plan version',
                'verbose_name_plural': 'Sampling plan versions',
                'ordering': ('plan__code', '-version_number'),
            },
        ),
        migrations.CreateModel(
            name='SamplingHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sampling_history_actions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sampling_history_entries', to='organizations.organization')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='sampling.samplingplan')),
                ('plan_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='sampling.samplingplanversion')),
            ],
            options={
                'verbose_name': 'Sampling history entry',
                'verbose_name_plural': 'Sampling history entries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChecklistItemSamplingBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frozen_sampling_context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sampling_binding', to='checklists.checklistitem')),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_bindings', to='sampling.samplingplanversion')),
            ],
            options={
                'verbose_name': 'Checklist item sampling binding',
                'verbose_name_plural': 'Checklist item sampling bindings',
            },
        ),
        migrations.CreateModel(
            name='SamplingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower number wins when multiple rules match (deterministic).')),
                ('product_group_code', models.CharField(blank=True, default='', max_length=64)),
                ('lot_size_min', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('lot_size_max', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('inspection_type', models.CharField(blank=True, default='', max_length=64)),
                ('risk_class', models.CharField(blank=True, default='', max_length=64)),
                ('process_code', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='sampling.samplingplanversion')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sampling_rules', to='master_data.fgproduct')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sampling_rules', to='organizations.site')),
            ],
            options={
                'verbose_name': 'Sampling rule',
                'verbose_name_plural': 'Sampling rules',
                'ordering': ('priority', 'code'),
            },
        ),
        migrations.CreateModel(
            name='SampleRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_sample_count', models.PositiveIntegerField(blank=True, help_text='Approved sample count only — null until company evidence supplies it.', null=True)),
                ('sample_grouping', models.CharField(blank=True, default='', max_length=128)),
                ('accept_threshold', models.PositiveIntegerField(blank=True, help_text='Max defectives to ACCEPT when configured — not invented.', null=True)),
                ('reject_threshold', models.PositiveIntegerField(blank=True, help_text='Min defectives to REJECT when configured — not invented.', null=True)),
                ('inspection_level', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirement', to='sampling.samplingrule')),
            ],
            options={
                'verbose_name': 'Sample requirement',
                'verbose_name_plural': 'Sample requirements',
            },
        ),
        migrations.AddConstraint(
            model_name='samplingplan',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='sampling_plan_org_code_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='samplingplanversion',
            constraint=models.UniqueConstraint(fields=('plan', 'version_number'), name='sampling_plan_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='samplingrule',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('plan_version'), name='sampling_rule_version_code_ci_uniq'),
        ),
    ]
