# Generated by Django 5.2.16 on 2026-08-07 19:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0002_checklist_response_definition_schema'),
        ('organizations', '0002_phase04a_shift_foundation'),
        ('scheduling', '0002_phase07b_record_checklisttask_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_task', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_record', to='scheduling.checklisttask')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_records', to='organizations.organization')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='started_checklist_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checklist record',
                'verbose_name_plural': 'Checklist records',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ChecklistResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choice_value', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'N/A')], default='', max_length=8)),
                ('number_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('text_value', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_responses', to='checklists.checklistitem')),
                ('checklist_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='recording.checklistrecord')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='draft_responses', to='checklists.checklistitemoption')),
            ],
            options={
                'verbose_name': 'Checklist response',
                'verbose_name_plural': 'Checklist responses',
                'ordering': ('checklist_item__section__position', 'checklist_item__position'),
            },
        ),
        migrations.AddIndex(
            model_name='checklistrecord',
            index=models.Index(fields=['organization', 'updated_at'], name='rec_record_org_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistresponse',
            index=models.Index(fields=['checklist_record', 'updated_at'], name='rec_response_record_upd_idx'),
        ),
        migrations.AddConstraint(
            model_name='checklistresponse',
            constraint=models.UniqueConstraint(fields=('checklist_record', 'checklist_item'), name='rec_response_record_item_uniq'),
        ),
        migrations.AddConstraint(
            model_name='checklistresponse',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('choice_value', ''), _negated=True), ('number_value__isnull', True), ('text_value', ''), ('selected_option__isnull', True)), models.Q(('choice_value', ''), ('number_value__isnull', False), ('text_value', ''), ('selected_option__isnull', True)), models.Q(('choice_value', ''), ('number_value__isnull', True), models.Q(('text_value', ''), _negated=True), ('selected_option__isnull', True)), models.Q(('choice_value', ''), ('number_value__isnull', True), ('text_value', ''), ('selected_option__isnull', False)), _connector='OR'), name='rec_response_exactly_one_value'),
        ),
    ]
