# Generated by Django 5.2.16 on 2026-08-07 20:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_checklist_response_definition_schema'),
        ('organizations', '0002_phase04a_shift_foundation'),
        ('recording', '0001_phase08a_checklist_draft_recording'),
        ('scheduling', '0002_phase07b_record_checklisttask_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Checklist submission',
                'verbose_name_plural': 'Checklist submissions',
                'ordering': ('checklist_record_id', 'submission_number'),
            },
        ),
        migrations.CreateModel(
            name='ChecklistSubmissionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choice_value', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'N/A')], default='', max_length=8)),
                ('number_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('text_value', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Checklist submission response',
                'verbose_name_plural': 'Checklist submission responses',
                'ordering': ('checklist_item__section__position', 'checklist_item__position'),
            },
        ),
        migrations.AddField(
            model_name='checklistrecord',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=16),
        ),
        migrations.AddIndex(
            model_name='checklistrecord',
            index=models.Index(fields=['organization', 'status'], name='rec_record_org_status_idx'),
        ),
        migrations.AddField(
            model_name='checklistsubmission',
            name='checklist_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='recording.checklistrecord'),
        ),
        migrations.AddField(
            model_name='checklistsubmission',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistsubmissionresponse',
            name='checklist_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_responses', to='checklists.checklistitem'),
        ),
        migrations.AddField(
            model_name='checklistsubmissionresponse',
            name='checklist_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='recording.checklistsubmission'),
        ),
        migrations.AddField(
            model_name='checklistsubmissionresponse',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submission_responses', to='checklists.checklistitemoption'),
        ),
        migrations.AddIndex(
            model_name='checklistsubmission',
            index=models.Index(fields=['checklist_record', 'submitted_at'], name='rec_submission_record_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='checklistsubmission',
            constraint=models.UniqueConstraint(fields=('checklist_record', 'submission_number'), name='rec_submission_record_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='checklistsubmissionresponse',
            constraint=models.UniqueConstraint(fields=('checklist_submission', 'checklist_item'), name='rec_sub_resp_submission_item_uniq'),
        ),
        migrations.AddConstraint(
            model_name='checklistsubmissionresponse',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('choice_value', ''), _negated=True), ('number_value__isnull', True), ('text_value', ''), ('selected_option__isnull', True)), models.Q(('choice_value', ''), ('number_value__isnull', False), ('text_value', ''), ('selected_option__isnull', True)), models.Q(('choice_value', ''), ('number_value__isnull', True), models.Q(('text_value', ''), _negated=True), ('selected_option__isnull', True)), models.Q(('choice_value', ''), ('number_value__isnull', True), ('text_value', ''), ('selected_option__isnull', False)), _connector='OR'), name='rec_sub_resp_exactly_one_value'),
        ),
    ]
