# Generated by Django 5.2.16 on 2026-08-08 23:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_phase06h_repeating_sample_foundation'),
        ('recording', '0003_phase09b_checklist_correction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistresponse',
            options={'ordering': ('checklist_item__section__position', 'checklist_item__position', 'sample_index'), 'verbose_name': 'Checklist response', 'verbose_name_plural': 'Checklist responses'},
        ),
        migrations.AlterModelOptions(
            name='checklistsubmissionresponse',
            options={'ordering': ('checklist_item__section__position', 'checklist_item__position', 'sample_index'), 'verbose_name': 'Checklist submission response', 'verbose_name_plural': 'Checklist submission responses'},
        ),
        migrations.RemoveConstraint(
            model_name='checklistresponse',
            name='rec_response_record_item_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='checklistsubmissionresponse',
            name='rec_sub_resp_submission_item_uniq',
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='sample_index',
            field=models.PositiveIntegerField(default=1, help_text='1 for non-repeating answers; sample/row index for repeating children.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='checklistsubmissionresponse',
            name='sample_index',
            field=models.PositiveIntegerField(default=1, help_text='Preserved sample/row index for repeating children; 1 for SIMPLE.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='checklistresponse',
            index=models.Index(fields=['checklist_record', 'checklist_item', 'sample_index'], name='rec_response_item_sample_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistsubmissionresponse',
            index=models.Index(fields=['checklist_submission', 'checklist_item', 'sample_index'], name='rec_sub_resp_item_sample_idx'),
        ),
        migrations.AddConstraint(
            model_name='checklistresponse',
            constraint=models.UniqueConstraint(fields=('checklist_record', 'checklist_item', 'sample_index'), name='rec_response_record_item_sample_uniq'),
        ),
        migrations.AddConstraint(
            model_name='checklistsubmissionresponse',
            constraint=models.UniqueConstraint(fields=('checklist_submission', 'checklist_item', 'sample_index'), name='rec_sub_resp_sub_item_sample_uniq'),
        ),
    ]
