# Generated by Django 5.2.16 on 2026-08-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0004_phase06h_repeating_sample_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistresponse',
            name='calculation_context',
            field=models.JSONField(blank=True, default=None, help_text='Server-authored explanation for CALCULATED drafts (operator + inputs).', null=True),
        ),
        migrations.AddField(
            model_name='checklistsubmissionresponse',
            name='calculation_context',
            field=models.JSONField(blank=True, default=None, help_text='Frozen CALCULATED explanation at submit time. Historical truth — do not recompute with future definition rules.', null=True),
        ),
    ]
