# Generated by Django 5.2.16 on 2026-08-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0005_phase06i_calculated_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistresponse',
            name='condition_context',
            field=models.JSONField(blank=True, default=None, help_text='Server-authored conditional applicability snapshot (Phase 06J).', null=True),
        ),
        migrations.AddField(
            model_name='checklistsubmissionresponse',
            name='condition_context',
            field=models.JSONField(blank=True, default=None, help_text='Frozen conditional applicability at submit time. Historical truth — do not re-evaluate with future definition rules.', null=True),
        ),
    ]
