# Generated by Django 5.2.16 on 2026-08-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0007_phase06k_item_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistsubmissionresponse',
            name='control_point_context',
            field=models.JSONField(blank=True, default=None, help_text='Frozen control-point / criticality metadata at submit time. Not a QA disposition — does not HOLD/REJECT/RELEASE.', null=True),
        ),
    ]
