# Generated by Django 5.2.16 on 2026-08-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0009_phase06m_measurement_semantics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistresponse',
            name='number_value',
            field=models.DecimalField(
                blank=True,
                decimal_places=12,
                help_text='Decimal-safe NUMBER storage (up to 12 fractional places for Phase 06M).',
                max_digits=26,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='checklistsubmissionresponse',
            name='number_value',
            field=models.DecimalField(
                blank=True,
                decimal_places=12,
                help_text='Frozen Decimal-safe NUMBER storage (up to 12 fractional places for Phase 06M).',
                max_digits=26,
                null=True,
            ),
        ),
    ]
