# Generated by Django 5.2.16 on 2026-08-10 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_phase25_device_traceability'),
        ('recording', '0011_phase08c_recording_hardening'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistresponse',
            name='calibration_record',
            field=models.ForeignKey(blank=True, help_text='Latest RECORDED calibration linked at measurement time (nullable).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_draft_responses', to='instruments.calibrationrecord'),
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='device_trace_context',
            field=models.JSONField(blank=True, default=None, help_text='Frozen device identity + calibration fitness at measurement time. Later equipment edits must not rewrite this snapshot.', null=True),
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='measurement_recorded_at',
            field=models.DateTimeField(blank=True, help_text='Server timestamp when the device reference was last applied.', null=True),
        ),
        migrations.AddField(
            model_name='checklistsubmissionresponse',
            name='calibration_record',
            field=models.ForeignKey(blank=True, help_text='Frozen calibration record reference at submit time.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_submission_responses', to='instruments.calibrationrecord'),
        ),
        migrations.AddField(
            model_name='checklistsubmissionresponse',
            name='device_trace_context',
            field=models.JSONField(blank=True, default=None, help_text='Frozen device + calibration snapshot at submit. Historical truth — do not recompute from later equipment master changes.', null=True),
        ),
        migrations.AddField(
            model_name='checklistsubmissionresponse',
            name='measurement_recorded_at',
            field=models.DateTimeField(blank=True, help_text='Frozen measurement timestamp copied from draft response.', null=True),
        ),
        migrations.AlterField(
            model_name='checklistresponse',
            name='equipment',
            field=models.ForeignKey(blank=True, help_text='Optional measuring device when the item requires equipment reference. Calibration enforcement follows INSTRUMENTS_CALIBRATION_ENFORCEMENT.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_draft_responses', to='instruments.equipment'),
        ),
        migrations.AlterField(
            model_name='checklistsubmissionresponse',
            name='equipment',
            field=models.ForeignKey(blank=True, help_text='Frozen measuring device reference at submit time.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_submission_responses', to='instruments.equipment'),
        ),
    ]
