# Generated by Django 5.2.16 on 2026-08-07 10:15

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_phase05a_fg_product_foundation'),
        ('organizations', '0002_phase04a_shift_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_templates', to='organizations.organization')),
                ('product', models.ForeignKey(blank=True, help_text='Optional provisional Product association — not proven mandatory by business evidence.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_templates', to='master_data.fgproduct')),
            ],
            options={
                'verbose_name': 'Checklist template',
                'verbose_name_plural': 'Checklist templates',
                'ordering': ('organization__code', 'code'),
                'permissions': [('manage_checklist', 'Can manage checklist definitions')],
            },
        ),
        migrations.CreateModel(
            name='ChecklistVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], default='DRAFT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='checklists.checklisttemplate')),
            ],
            options={
                'verbose_name': 'Checklist version',
                'verbose_name_plural': 'Checklist versions',
                'ordering': ('template__code', '-version_number'),
            },
        ),
        migrations.CreateModel(
            name='ChecklistSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='checklists.checklistversion')),
            ],
            options={
                'verbose_name': 'Checklist section',
                'verbose_name_plural': 'Checklist sections',
                'ordering': ('position', 'title'),
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=500)),
                ('help_text', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_required', models.BooleanField(default=True, help_text='Technical required flag for later recording phases — not a QA rule.')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklistsection')),
            ],
            options={
                'verbose_name': 'Checklist item',
                'verbose_name_plural': 'Checklist items',
                'ordering': ('position', 'code'),
                'constraints': [models.UniqueConstraint(fields=('section', 'position'), name='chk_item_section_position_uniq'), models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('section'), name='chk_item_section_code_ci_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='checklisttemplate',
            index=models.Index(fields=['organization', 'is_active'], name='chk_template_org_act_idx'),
        ),
        migrations.AddIndex(
            model_name='checklisttemplate',
            index=models.Index(django.db.models.functions.text.Lower('code'), name='chk_template_code_lower_idx'),
        ),
        migrations.AddConstraint(
            model_name='checklisttemplate',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='chk_template_org_code_ci_uniq'),
        ),
        migrations.AddIndex(
            model_name='checklistversion',
            index=models.Index(fields=['template', 'status'], name='chk_version_tmpl_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='checklistversion',
            constraint=models.UniqueConstraint(fields=('template', 'version_number'), name='chk_version_template_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='checklistsection',
            constraint=models.UniqueConstraint(fields=('version', 'position'), name='chk_section_version_position_uniq'),
        ),
    ]
