# Generated by Django 5.2.16 on 2026-08-07 15:39

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_checklist_definition_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='maximum_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Optional NUMBER upper bound. Unset is allowed.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='minimum_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Optional NUMBER lower bound. Unset is allowed.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='response_type',
            field=models.CharField(blank=True, choices=[('YES_NO', 'Yes / No'), ('YES_NO_NA', 'Yes / No / N/A'), ('NUMBER', 'Number'), ('TEXT', 'Text'), ('SELECT', 'Select')], default='', help_text='Blank allowed on DRAFT only; publish requires a valid response type.', max_length=16),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='unit',
            field=models.CharField(blank=True, default='', help_text='Optional unit for NUMBER items (e.g. °C). Not a limit.', max_length=32),
        ),
        migrations.CreateModel(
            name='ChecklistItemOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='checklists.checklistitem')),
            ],
            options={
                'verbose_name': 'Checklist item option',
                'verbose_name_plural': 'Checklist item options',
                'ordering': ('position', 'value'),
                'constraints': [models.UniqueConstraint(fields=('item', 'position'), name='chk_option_item_position_uniq'), models.UniqueConstraint(django.db.models.functions.text.Lower('value'), models.F('item'), name='chk_option_item_value_ci_uniq')],
            },
        ),
    ]
