# Generated by Django 5.2.16 on 2026-08-08 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_checklist_response_definition_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='item_kind',
            field=models.CharField(choices=[('SIMPLE', 'Simple'), ('REPEATING_GROUP', 'Repeating group'), ('CALCULATED', 'Calculated')], default='SIMPLE', max_length=32),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='parent_item',
            field=models.ForeignKey(blank=True, help_text='Set only for children of a REPEATING_GROUP (one level).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_items', to='checklists.checklistitem'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='repeat_default',
            field=models.PositiveIntegerField(blank=True, help_text='Optional default sample row count when defined — not invented.', null=True),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='repeat_max',
            field=models.PositiveIntegerField(blank=True, help_text='Optional maximum sample rows when defined by evidence — not invented.', null=True),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='repeat_min',
            field=models.PositiveIntegerField(blank=True, help_text='Optional minimum sample rows when defined by evidence — not invented.', null=True),
        ),
        migrations.AddIndex(
            model_name='checklistitem',
            index=models.Index(fields=['section', 'parent_item', 'position'], name='chk_item_sect_parent_pos_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistitem',
            index=models.Index(fields=['item_kind'], name='chk_item_kind_idx'),
        ),
    ]
