# Generated by Django 5.2.16 on 2026-08-09 20:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_phase06h_repeating_sample_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='calculation_operator',
            field=models.CharField(blank=True, choices=[('SUM', 'Sum'), ('AVERAGE', 'Average'), ('MIN', 'Minimum'), ('MAX', 'Maximum'), ('COUNT', 'Count'), ('RANGE', 'Range (max − min)')], default='', help_text='Closed operator for CALCULATED items only (SUM/AVERAGE/MIN/MAX/COUNT/RANGE).', max_length=16),
        ),
        migrations.CreateModel(
            name='ChecklistCalculationOperand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('calculated_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_operand_links', to='checklists.checklistitem')),
                ('source_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_as_calculation_operand_for', to='checklists.checklistitem')),
            ],
            options={
                'verbose_name': 'Checklist calculation operand',
                'verbose_name_plural': 'Checklist calculation operands',
                'ordering': ('position', 'pk'),
                'indexes': [models.Index(fields=['calculated_item', 'position'], name='chk_calc_operand_item_pos_idx')],
                'constraints': [models.UniqueConstraint(fields=('calculated_item', 'position'), name='chk_calc_operand_pos_uniq'), models.UniqueConstraint(fields=('calculated_item', 'source_item'), name='chk_calc_operand_source_uniq')],
            },
        ),
    ]
