# Generated by Django 5.2.16 on 2026-08-09 20:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_phase06i_calculated_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItemRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_kind', models.CharField(choices=[('VISIBLE_IF', 'Visible if'), ('REQUIRED_IF', 'Required if'), ('EVIDENCE_REQUIRED_IF', 'Evidence required if')], max_length=32)),
                ('comparator', models.CharField(choices=[('EQ', 'Equals'), ('NE', 'Not equals'), ('IN', 'In list'), ('GT', 'Greater than'), ('GTE', 'Greater than or equal'), ('LT', 'Less than'), ('LTE', 'Less than or equal'), ('IS_ANSWERED', 'Is answered'), ('IS_EMPTY', 'Is empty'), ('IS_NOT_EMPTY', 'Is not empty')], max_length=16)),
                ('expected_text', models.CharField(blank=True, default='', max_length=255)),
                ('expected_number', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('expected_boolean', models.BooleanField(blank=True, null=True)),
                ('expected_list', models.JSONField(blank=True, default=list)),
                ('expected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='condition_rule_expectations', to='checklists.checklistitemoption')),
                ('operand_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referenced_by_condition_rules', to='checklists.checklistitem')),
                ('target_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_rules', to='checklists.checklistitem')),
            ],
            options={
                'verbose_name': 'Checklist item rule',
                'verbose_name_plural': 'Checklist item rules',
                'ordering': ('rule_kind', 'pk'),
                'indexes': [models.Index(fields=['target_item', 'rule_kind'], name='chk_item_rule_kind_idx')],
                'constraints': [models.UniqueConstraint(fields=('target_item', 'rule_kind'), name='chk_item_rule_kind_uniq')],
            },
        ),
    ]
