# Generated by Django 5.2.16 on 2026-08-09 22:21

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_phase04c_organization_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('equipment_type', models.CharField(choices=[('SCALE', 'Scale'), ('THERMOMETER', 'Thermometer'), ('PROBE', 'Probe'), ('METAL_DETECTOR', 'Metal detector'), ('LAB_INSTRUMENT', 'Lab instrument'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('serial_number', models.CharField(blank=True, default='', max_length=128)),
                ('location_label', models.CharField(blank=True, default='', help_text='Optional free-text location label within site/org.', max_length=255)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=128)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('operational_status', models.CharField(choices=[('IN_SERVICE', 'In service'), ('OUT_OF_SERVICE', 'Out of service')], default='IN_SERVICE', max_length=32)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive equipment remains historically referenceable; prefer over delete.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_assets', to='organizations.organization')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_assets', to='organizations.site')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ('organization__code', 'code'),
                'permissions': [('manage_equipment', 'Can manage equipment and calibration records')],
            },
        ),
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calibrated_on', models.DateField()),
                ('next_due_on', models.DateField(blank=True, help_text='Optional next-due date when evidenced. Not auto-calculated from a frequency.', null=True)),
                ('certificate_reference', models.CharField(blank=True, default='', max_length=255)),
                ('provider_reference', models.CharField(blank=True, default='', help_text='Calibration provider / lab reference (not invented).', max_length=255)),
                ('status', models.CharField(choices=[('RECORDED', 'Recorded'), ('VOID', 'Void')], default='RECORDED', help_text='Record lifecycle. Prefer VOID over hard delete. Expansion EVIDENCE REQUIRED.', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibration_records_recorded', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibration_records', to='instruments.equipment')),
            ],
            options={
                'verbose_name': 'Calibration record',
                'verbose_name_plural': 'Calibration records',
                'ordering': ('-calibrated_on', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['organization', 'is_active'], name='inst_equip_org_act_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['organization', 'equipment_type'], name='inst_equip_org_type_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(django.db.models.functions.text.Lower('code'), name='inst_equip_code_lower_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='inst_equipment_org_code_ci_uniq'),
        ),
        migrations.AddIndex(
            model_name='calibrationrecord',
            index=models.Index(fields=['equipment', 'calibrated_on'], name='inst_calib_equip_on_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationrecord',
            index=models.Index(fields=['next_due_on'], name='inst_calib_next_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='calibrationrecord',
            constraint=models.CheckConstraint(condition=models.Q(('next_due_on__isnull', True), ('next_due_on__gte', models.F('calibrated_on')), _connector='OR'), name='inst_calib_next_due_gte_calibrated'),
        ),
    ]
