# Generated by Django 5.2.16 on 2026-08-10 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_phase05d_equipment_calibration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ('organization__code', 'code'), 'permissions': [('manage_equipment', 'Can manage equipment and calibration records'), ('override_calibration_gate', 'Can override calibration WARN/BLOCK when company policy approves')], 'verbose_name': 'Equipment', 'verbose_name_plural': 'Equipment'},
        ),
    ]
