# Generated by Django 5.2.16 on 2026-08-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0007_phase30_allergen_changeover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenceattachment',
            name='linked_kind',
            field=models.CharField(choices=[('CHECKLIST_RESPONSE', 'Checklist response (draft)'), ('CHECKLIST_SUBMISSION', 'Checklist submission'), ('SUPERVISOR_REVIEW', 'Supervisor review'), ('QA_REVIEW', 'QA review'), ('NONCONFORMANCE', 'Nonconformance (future)'), ('CAPA', 'CAPA (future)'), ('LAB_SAMPLE', 'Laboratory sample'), ('LAB_EXTERNAL_CERTIFICATE', 'Laboratory external certificate'), ('CALIBRATION_CERTIFICATE', 'Calibration certificate (equipment record)'), ('SANITATION_PROGRAM', 'Sanitation / SSOP program'), ('MONITORING_READING', 'Environmental monitoring reading'), ('PACKAGING_ARTWORK_VERSION', 'Packaging artwork version evidence'), ('CHANGEOVER_RECORD', 'Changeover / allergen changeover record'), ('LINE_CLEARANCE_RECORD', 'Line clearance record'), ('RECEIPT_QUALITY_RECORD', 'Raw material receipt quality record')], max_length=32),
        ),
    ]
