# Generated by Django 5.2.16 on 2026-08-06 13:30

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0001_phase03_accounts_rbac'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='access_roles', to='auth.permission')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='ScopedRoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roles_assigned', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='organizations.department')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='organizations.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='access_control.role')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='organizations.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scoped_role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_active'], name='ac_role_active_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(django.db.models.functions.text.Lower('code'), name='ac_role_code_lower_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='ac_role_code_ci_uniq'),
        ),
        migrations.AddIndex(
            model_name='scopedroleassignment',
            index=models.Index(fields=['user', 'is_active'], name='ac_assign_user_idx'),
        ),
        migrations.AddIndex(
            model_name='scopedroleassignment',
            index=models.Index(fields=['organization', 'is_active'], name='ac_assign_org_idx'),
        ),
        migrations.AddIndex(
            model_name='scopedroleassignment',
            index=models.Index(fields=['valid_until'], name='ac_assign_until_idx'),
        ),
        migrations.AddConstraint(
            model_name='scopedroleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'role', 'organization', 'site', 'department'), name='ac_active_assignment_uniq'),
        ),
    ]
