# Generated by Django 5.2.16 on 2026-08-09 22:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0004_phase03c_roletemplate_deliverable'),
        ('checklists', '0009_phase05d_equipment_calibration'),
        ('instruments', '0001_phase05d_equipment_calibration'),
        ('organizations', '0003_phase04c_organization_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingEnforcementPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gate_mode', models.CharField(choices=[('OFF', 'Off (no gate)'), ('WARN', 'Warn'), ('BLOCK', 'Block')], default='OFF', help_text='Future recording-gate mode. OFF until company policy approves WARN/BLOCK.', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='training_enforcement_policy', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_enforcement_policies_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training enforcement policy',
                'verbose_name_plural': 'Training enforcement policies',
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_code', models.CharField(help_text='Training/course reference code (not a seeded catalogue).', max_length=64)),
                ('course_name', models.CharField(blank=True, default='', max_length=255)),
                ('competency_scope', models.CharField(choices=[('GENERAL', 'General'), ('CHECKLIST', 'Specific checklist'), ('PROCESS', 'Process'), ('EQUIPMENT', 'Equipment'), ('BUSINESS_ROLE', 'Business role')], default='GENERAL', max_length=32)),
                ('process_reference', models.CharField(blank=True, default='', help_text='Optional process reference label when scope=PROCESS. Not a process master.', max_length=255)),
                ('trained_on', models.DateField()),
                ('expires_on', models.DateField(blank=True, help_text='Optional expiry when evidenced. Expiry retains the historical row.', null=True)),
                ('trainer_reference', models.CharField(blank=True, default='', max_length=255)),
                ('evidence_reference', models.CharField(blank=True, default='', help_text='Optional evidence reference. File attachments deferred to object storage.', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('VOID', 'Void')], default='ACTIVE', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_role', models.ForeignKey(blank=True, help_text='Optional when competency_scope=BUSINESS_ROLE.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_records', to='access_control.role')),
                ('checklist_template', models.ForeignKey(blank=True, help_text='Optional when competency_scope=CHECKLIST.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_records', to='checklists.checklisttemplate')),
                ('equipment', models.ForeignKey(blank=True, help_text='Optional when competency_scope=EQUIPMENT.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_records', to='instruments.equipment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_records', to='organizations.organization')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_records_recorded', to=settings.AUTH_USER_MODEL)),
                ('subject_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_records_as_subject', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training record',
                'verbose_name_plural': 'Training records',
                'ordering': ('-trained_on', '-created_at'),
                'permissions': [('manage_trainingrecord', 'Can manage training and competency records')],
                'indexes': [models.Index(fields=['organization', 'subject_user', 'status'], name='trn_rec_org_user_status_idx'), models.Index(fields=['organization', 'competency_scope'], name='trn_rec_org_scope_idx'), models.Index(fields=['expires_on'], name='trn_rec_expires_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_on__isnull', True), ('expires_on__gte', models.F('trained_on')), _connector='OR'), name='trn_record_expires_gte_trained')],
            },
        ),
    ]
