# Generated by Django 5.2.16 on 2026-08-09 20:39

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PocIdempotencyKey',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=128)),
                ('result_ref', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope', 'key'), name='mongo_poc_idempotency_uniq')],
            },
        ),
        migrations.CreateModel(
            name='PocOrganization',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('code',), name='mongo_poc_org_code_uniq')],
            },
        ),
        migrations.CreateModel(
            name='PocChecklistTemplate',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='mongo_poc.pocorganization')),
            ],
        ),
        migrations.CreateModel(
            name='PocRecord',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='draft', max_length=32)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='mongo_poc.pocorganization')),
            ],
        ),
        migrations.CreateModel(
            name='PocSubmission',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('submission_number', models.PositiveIntegerField()),
                ('is_immutable', models.BooleanField(default=True)),
                ('payload_marker', models.CharField(blank=True, default='', max_length=64)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='mongo_poc.pocorganization')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='mongo_poc.pocrecord')),
            ],
        ),
        migrations.CreateModel(
            name='PocResponseSnapshot',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('item_key', models.CharField(max_length=64)),
                ('sample_index', models.PositiveIntegerField(default=0)),
                ('value_text', models.CharField(blank=True, default='', max_length=256)),
                ('calculation_context', models.JSONField(blank=True, default=dict)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='mongo_poc.pocsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='PocCorrection',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='open', max_length=32)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='mongo_poc.pocrecord')),
                ('source_submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='correction', to='mongo_poc.pocsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='PocSupervisorReview',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('decision', models.CharField(max_length=32)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_review', to='mongo_poc.pocsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='PocQAReview',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('decision', models.CharField(max_length=32)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='qa_review', to='mongo_poc.pocsubmission')),
                ('supervisor_review', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='qa_review', to='mongo_poc.pocsupervisorreview')),
            ],
        ),
        migrations.CreateModel(
            name='PocTask',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('batch_reference', models.CharField(max_length=128)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='mongo_poc.pocorganization')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='mongo_poc.pocchecklisttemplate')),
            ],
        ),
        migrations.AddField(
            model_name='pocrecord',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='record', to='mongo_poc.poctask'),
        ),
        migrations.CreateModel(
            name='PocChecklistVersion',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='mongo_poc.pocchecklisttemplate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('template', 'version_number'), name='mongo_poc_version_number_uniq')],
            },
        ),
        migrations.CreateModel(
            name='PocEmployee',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('employee_code_normalized', models.CharField(max_length=64)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='mongo_poc.pocorganization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'employee_code_normalized'), name='mongo_poc_employee_code_uniq')],
            },
        ),
        migrations.AddConstraint(
            model_name='pocchecklisttemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'key'), name='mongo_poc_template_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pocsubmission',
            constraint=models.UniqueConstraint(fields=('record', 'submission_number'), name='mongo_poc_submission_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pocresponsesnapshot',
            constraint=models.UniqueConstraint(fields=('submission', 'item_key', 'sample_index'), name='mongo_poc_response_sample_uniq'),
        ),
        migrations.AddConstraint(
            model_name='poctask',
            constraint=models.UniqueConstraint(fields=('organization', 'template', 'batch_reference'), name='mongo_poc_task_batch_uniq'),
        ),
    ]
