# Generated by Django 5.2.16 on 2026-08-10 00:35

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_phase04c_organization_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('TASK_ASSIGNED', 'Task assignment'), ('TASK_DUE', 'Task due'), ('TASK_OVERDUE', 'Task overdue'), ('SUBMISSION_CREATED', 'Submission created'), ('SUPERVISOR_PENDING', 'Supervisor review pending'), ('CORRECTION_RETURNED', 'Returned for correction'), ('QA_PENDING', 'QA review pending'), ('QA_HOLD', 'QA HOLD disposition'), ('QA_REJECT', 'QA REJECT disposition'), ('CAPA_DUE', 'CAPA action due'), ('INTEGRATION_FAILURE', 'Integration failure')], max_length=32)),
                ('title', models.CharField(max_length=120)),
                ('safe_message', models.CharField(help_text='Privacy-safe summary only — never checklist answers or sensitive notes.', max_length=280)),
                ('reference_kind', models.CharField(blank=True, default='', max_length=64)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('dedupe_key', models.CharField(help_text='Idempotency key scoped per recipient (duplicate creates are no-ops).', max_length=128)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='DELIVERED', help_text='In-app channel status (created rows are DELIVERED).', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='organizations.organization')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ('-created_at',),
                'permissions': [('view_own_notifications', 'Can view own workflow notifications'), ('manage_notifications', 'Can manage workflow notification dispatch')],
            },
        ),
        migrations.CreateModel(
            name='NotificationDeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'Email')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=16)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_attempts', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'Notification delivery attempt',
                'verbose_name_plural': 'Notification delivery attempts',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationNotificationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled_event_types', models.JSONField(blank=True, default=list, help_text='List of NotificationEventType values enabled for this org. Default empty.')),
                ('email_delivery_enabled', models.BooleanField(default=False, help_text='When True and SMTP configured, queue email copies of enabled events.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='notification_policy', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_policies_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization notification policy',
                'verbose_name_plural': 'Organization notification policies',
                'permissions': [('manage_notificationpolicy', 'Can manage organization notification policy')],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read_at', 'created_at'], name='notif_recipient_read_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', 'event_type', 'created_at'], name='notif_org_event_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('dedupe_key'), models.F('recipient'), name='notif_recipient_dedupe_ci_uniq'),
        ),
        migrations.AddIndex(
            model_name='notificationdeliveryattempt',
            index=models.Index(fields=['status', 'channel', 'last_attempted_at'], name='notif_delivery_status_idx'),
        ),
    ]
