# Generated by Django 5.2.16 on 2026-08-10 01:17

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0003_phase06o_product_specifications'),
        ('nonconformance', '0002_phase12_ncr_hold_capa_foundation'),
        ('organizations', '0003_phase04c_organization_configuration'),
        ('recording', '0011_phase08c_recording_hardening'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabPositiveReleasePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_enabled', models.BooleanField(default=False, help_text='Company may enable policy definition — does not alone block RELEASE.')),
                ('require_finalized_results', models.BooleanField(default=True, help_text='When blocking is approved+enabled, require finalized linked results.')),
                ('notes', models.TextField(blank=True, default='', help_text='Owner notes only — not an approved SOP text.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lab_positive_release_policy', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_positive_release_policies_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lab positive-release policy',
                'verbose_name_plural': 'Lab positive-release policies',
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('ENTERED', 'Result entered'), ('VERIFIED', 'Verified'), ('FINALIZED', 'Finalized'), ('SUPERSEDED', 'Superseded by amendment'), ('CANCELLED', 'Cancelled')], default='ENTERED', max_length=16)),
                ('result_type', models.CharField(choices=[('NUMERIC', 'Numeric'), ('TEXT', 'Text'), ('SELECT', 'Select / qualitative')], max_length=16)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=12, max_digits=26, null=True)),
                ('text_value', models.CharField(blank=True, default='', max_length=512)),
                ('select_value', models.CharField(blank=True, default='', max_length=128)),
                ('unit', models.CharField(blank=True, default='', max_length=64)),
                ('bound_min', models.DecimalField(blank=True, decimal_places=12, max_digits=26, null=True)),
                ('bound_max', models.DecimalField(blank=True, decimal_places=12, max_digits=26, null=True)),
                ('amendment_reason', models.CharField(blank=True, default='', max_length=512)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_results_entered', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_results_finalized', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_results', to='organizations.organization')),
                ('previous_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='laboratory.labresult')),
                ('specification_parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_results', to='master_data.specificationparameter')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_results_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lab result',
                'verbose_name_plural': 'Lab results',
                'ordering': ('lab_test_id', 'parameter__code', '-revision_number'),
                'permissions': [('enter_labresult', 'Can enter laboratory results'), ('verify_labresult', 'Can verify laboratory results'), ('finalize_labresult', 'Can finalize laboratory results')],
            },
        ),
        migrations.CreateModel(
            name='LabSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('RECEIVED', 'Received'), ('IN_TESTING', 'In testing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REGISTERED', max_length=16)),
                ('batch_reference', models.CharField(blank=True, default='', max_length=128)),
                ('sub_lot_reference', models.CharField(blank=True, default='', help_text='Opaque sub-lot / quantity reference — no disposition rules invented.', max_length=128)),
                ('provenance_note', models.CharField(blank=True, default='', help_text='Short provenance label only — avoid sensitive free-text.', max_length=255)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('checklist_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_samples', to='recording.checklistsubmission')),
                ('hold_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_samples', to='nonconformance.holdcase')),
                ('nonconformance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_samples', to='nonconformance.nonconformancerecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_samples', to='organizations.organization')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_samples', to='master_data.fgproduct')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_samples_registered', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_samples', to='organizations.site')),
            ],
            options={
                'verbose_name': 'Lab sample',
                'verbose_name_plural': 'Lab samples',
                'ordering': ('-registered_at',),
                'permissions': [('register_labsample', 'Can register laboratory samples'), ('view_laboratory', 'Can view laboratory samples and results')],
            },
        ),
        migrations.CreateModel(
            name='LabHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('SAMPLE_CREATED', 'Sample created'), ('SAMPLE_STATUS_CHANGED', 'Sample status changed'), ('TEST_CREATED', 'Test created'), ('RESULT_ENTERED', 'Result entered'), ('RESULT_VERIFIED', 'Result verified'), ('RESULT_FINALIZED', 'Result finalized'), ('RESULT_AMENDED', 'Result amended'), ('EXTERNAL_CERT_RECORDED', 'External certificate recorded'), ('POLICY_UPDATED', 'Positive-release policy updated')], max_length=32)),
                ('from_status', models.CharField(blank=True, default='', max_length=16)),
                ('to_status', models.CharField(blank=True, default='', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_history_entries', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_history_entries', to='organizations.organization')),
                ('lab_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history_entries', to='laboratory.labresult')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history_entries', to='laboratory.labsample')),
            ],
            options={
                'verbose_name': 'Lab history entry',
                'verbose_name_plural': 'Lab history entries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('external_lab_code', models.CharField(blank=True, default='', help_text='Opaque external laboratory identifier — no vendor catalogue invented.', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_tests', to='organizations.organization')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='laboratory.labsample')),
            ],
            options={
                'verbose_name': 'Lab test',
                'verbose_name_plural': 'Lab tests',
                'ordering': ('sample__code', 'code'),
            },
        ),
        migrations.AddField(
            model_name='labresult',
            name='lab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='laboratory.labtest'),
        ),
        migrations.CreateModel(
            name='LabExternalCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_lab_reference', models.CharField(max_length=128)),
                ('certificate_reference', models.CharField(blank=True, default='', max_length=128)),
                ('result_received_at', models.DateTimeField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_external_certs_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_external_certificates', to='organizations.organization')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_external_certs_verified', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_certificates', to='laboratory.labsample')),
                ('lab_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_certificates', to='laboratory.labtest')),
            ],
            options={
                'verbose_name': 'Lab external certificate',
                'verbose_name_plural': 'Lab external certificates',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LabTestParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('result_type', models.CharField(choices=[('NUMERIC', 'Numeric'), ('TEXT', 'Text'), ('SELECT', 'Select / qualitative')], default='NUMERIC', max_length=16)),
                ('unit', models.CharField(blank=True, default='', max_length=64)),
                ('select_options', models.JSONField(blank=True, default=list, help_text='Optional qualitative choices when result_type=SELECT. Empty until approved.')),
                ('bound_min', models.DecimalField(blank=True, decimal_places=12, max_digits=26, null=True)),
                ('bound_max', models.DecimalField(blank=True, decimal_places=12, max_digits=26, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_test_parameters', to='organizations.organization')),
                ('specification_parameter', models.ForeignKey(blank=True, help_text='Optional link to an approved product-spec parameter (no invented limits).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_test_parameters', to='master_data.specificationparameter')),
            ],
            options={
                'verbose_name': 'Lab test parameter',
                'verbose_name_plural': 'Lab test parameters',
                'ordering': ('organization__code', 'code'),
                'permissions': [('manage_laboratory', 'Can administer laboratory catalogue and policy')],
            },
        ),
        migrations.AddField(
            model_name='labresult',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='laboratory.labtestparameter'),
        ),
        migrations.CreateModel(
            name='TestMethodReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_test_method_references', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Test method reference',
                'verbose_name_plural': 'Test method references',
                'ordering': ('organization__code', 'code'),
            },
        ),
        migrations.AddField(
            model_name='labtestparameter',
            name='method_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parameters', to='laboratory.testmethodreference'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='method_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='laboratory.testmethodreference'),
        ),
        migrations.AddIndex(
            model_name='labsample',
            index=models.Index(fields=['organization', 'status'], name='lab_sample_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='labsample',
            index=models.Index(fields=['organization', 'batch_reference'], name='lab_sample_org_batch_idx'),
        ),
        migrations.AddConstraint(
            model_name='labsample',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='lab_sample_org_code_ci_uniq'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['organization', 'status'], name='lab_result_org_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='labresult',
            constraint=models.UniqueConstraint(fields=('lab_test', 'parameter', 'revision_number'), name='lab_result_test_param_rev_uniq'),
        ),
        migrations.AddConstraint(
            model_name='testmethodreference',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='lab_method_org_code_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='labtestparameter',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='lab_param_org_code_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='labtest',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('sample'), name='lab_test_sample_code_ci_uniq'),
        ),
    ]
