# Generated by Django 5.2.16 on 2026-08-10 00:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_phase04c_organization_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('linked_kind', models.CharField(choices=[('CHECKLIST_RESPONSE', 'Checklist response (draft)'), ('CHECKLIST_SUBMISSION', 'Checklist submission'), ('SUPERVISOR_REVIEW', 'Supervisor review'), ('QA_REVIEW', 'QA review'), ('NONCONFORMANCE', 'Nonconformance (future)'), ('CAPA', 'CAPA (future)')], max_length=32)),
                ('linked_object_id', models.UUIDField(help_text='Primary key of the allowlisted linked domain object.')),
                ('original_filename', models.CharField(max_length=180)),
                ('storage_key', models.CharField(help_text='Opaque private storage key (randomized; not a public URL).', max_length=512, unique=True)),
                ('content_type', models.CharField(max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('content_sha256', models.CharField(help_text='Lowercase hex SHA-256 of stored file bytes.', max_length=64)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lifecycle_status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETIRED', 'Retired (soft-removed)')], default='ACTIVE', max_length=16)),
                ('linkage_immutable', models.BooleanField(default=False, help_text='True when linked to a finalized immutable record or when draft parent is no longer mutable. Controlled soft-retire only.')),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('retirement_reason', models.CharField(blank=True, default='', max_length=255)),
                ('malware_scan_status', models.CharField(choices=[('NOT_CONFIGURED', 'Scanner not configured'), ('PENDING', 'Scan pending'), ('CLEAN', 'Clean'), ('INFECTED', 'Infected'), ('ERROR', 'Scan error')], default='NOT_CONFIGURED', max_length=32)),
                ('malware_scan_provider', models.CharField(blank=True, default='', max_length=64)),
                ('malware_scan_detail', models.TextField(blank=True, default='')),
                ('malware_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_attachments', to='organizations.organization')),
                ('retired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence_retirements', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidence attachment',
                'verbose_name_plural': 'Evidence attachments',
                'ordering': ('-uploaded_at',),
                'permissions': [('upload_evidenceattachment', 'Can upload evidence attachments'), ('retire_evidenceattachment', 'Can soft-retire evidence attachments')],
                'indexes': [models.Index(fields=['organization', 'linked_kind', 'linked_object_id'], name='ev_org_link_idx'), models.Index(fields=['organization', 'lifecycle_status', 'uploaded_at'], name='ev_org_life_up_idx'), models.Index(fields=['content_sha256'], name='ev_sha256_idx')],
            },
        ),
    ]
