# Generated by Django 5.2.16 on 2026-08-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_phase11_evidence_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenceattachment',
            name='linked_kind',
            field=models.CharField(choices=[('CHECKLIST_RESPONSE', 'Checklist response (draft)'), ('CHECKLIST_SUBMISSION', 'Checklist submission'), ('SUPERVISOR_REVIEW', 'Supervisor review'), ('QA_REVIEW', 'QA review'), ('NONCONFORMANCE', 'Nonconformance (future)'), ('CAPA', 'CAPA (future)'), ('LAB_SAMPLE', 'Laboratory sample'), ('LAB_EXTERNAL_CERTIFICATE', 'Laboratory external certificate')], max_length=32),
        ),
    ]
