# Generated by Django 5.2.16 on 2026-08-07 20:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_phase04a_shift_foundation'),
        ('recording', '0002_phase08b_checklist_submission_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved (supervisor review complete)'), ('RETURNED_FOR_CORRECTION', 'Returned for correction')], max_length=32)),
                ('review_note', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('checklist_submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_review', to='recording.checklistsubmission')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_reviews', to='organizations.organization')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supervisor review',
                'verbose_name_plural': 'Supervisor reviews',
                'ordering': ('-reviewed_at',),
                'permissions': [('review_checklistsubmission', 'Can review checklist submissions (Supervisor review)')],
                'indexes': [models.Index(fields=['organization', 'reviewed_at'], name='rev_sup_org_reviewed_idx'), models.Index(fields=['organization', 'decision'], name='rev_sup_org_decision_idx')],
            },
        ),
    ]
