# Generated by Django 5.2.16 on 2026-08-09 22:40

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_phase05c_fg_product_master'),
        ('organizations', '0003_phase04c_organization_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_specifications', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_specifications', to='master_data.fgproduct')),
            ],
            options={
                'verbose_name': 'Product specification',
                'verbose_name_plural': 'Product specifications',
                'ordering': ('organization__code', 'product__code', 'code'),
                'permissions': [('manage_productspecification', 'Can manage product specifications')],
            },
        ),
        migrations.CreateModel(
            name='SpecificationVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('RETIRED', 'Retired')], default='DRAFT', max_length=16)),
                ('effective_from', models.DateField(blank=True, help_text='Optional. Blank means unbounded start until business policy confirms.', null=True)),
                ('effective_to', models.DateField(blank=True, help_text='Optional. Blank means unbounded end until business policy confirms.', null=True)),
                ('approval_reference', models.CharField(blank=True, default='', help_text='Document / approval reference — empty until owner evidence.', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_specification_versions', to=settings.AUTH_USER_MODEL)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='master_data.productspecification')),
            ],
            options={
                'verbose_name': 'Specification version',
                'verbose_name_plural': 'Specification versions',
                'ordering': ('specification__code', '-version_number'),
            },
        ),
        migrations.CreateModel(
            name='SpecificationParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('precision', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bound_min', models.DecimalField(blank=True, decimal_places=12, max_digits=26, null=True)),
                ('bound_max', models.DecimalField(blank=True, decimal_places=12, max_digits=26, null=True)),
                ('min_inclusive', models.BooleanField(blank=True, null=True)),
                ('max_inclusive', models.BooleanField(blank=True, null=True)),
                ('warn_min', models.DecimalField(blank=True, decimal_places=12, max_digits=26, null=True)),
                ('warn_max', models.DecimalField(blank=True, decimal_places=12, max_digits=26, null=True)),
                ('warn_min_inclusive', models.BooleanField(blank=True, null=True)),
                ('warn_max_inclusive', models.BooleanField(blank=True, null=True)),
                ('test_method_reference', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='master_data.specificationversion')),
            ],
            options={
                'verbose_name': 'Specification parameter',
                'verbose_name_plural': 'Specification parameters',
                'ordering': ('version_id', 'code'),
            },
        ),
        migrations.AddIndex(
            model_name='productspecification',
            index=models.Index(fields=['organization', 'is_active'], name='md_productspec_org_act_idx'),
        ),
        migrations.AddIndex(
            model_name='productspecification',
            index=models.Index(django.db.models.functions.text.Lower('code'), name='md_productspec_code_lower_idx'),
        ),
        migrations.AddConstraint(
            model_name='productspecification',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('product'), name='md_productspec_product_code_ci_uniq'),
        ),
        migrations.AddIndex(
            model_name='specificationversion',
            index=models.Index(fields=['specification', 'status'], name='md_specversion_spec_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='specificationversion',
            constraint=models.UniqueConstraint(fields=('specification', 'version_number'), name='md_specversion_spec_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='specificationversion',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='md_specversion_effective_window_valid'),
        ),
        migrations.AddIndex(
            model_name='specificationparameter',
            index=models.Index(django.db.models.functions.text.Lower('code'), name='md_specparam_code_lower_idx'),
        ),
        migrations.AddConstraint(
            model_name='specificationparameter',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('version'), name='md_specparam_version_code_ci_uniq'),
        ),
    ]
