# Generated by Django 5.2.16 on 2026-08-11 04:02

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_phase04c_organization_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Owner-supplied document code.', max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('document_kind', models.CharField(choices=[('SOP', 'SOP'), ('WORK_INSTRUCTION', 'Work instruction'), ('SPECIFICATION', 'Specification'), ('TEST_METHOD', 'Test method'), ('POLICY', 'Policy'), ('FORM_REFERENCE', 'Form reference')], max_length=32)),
                ('type_code_reference', models.CharField(blank=True, default='', help_text='Optional owner-configured type catalogue code (APR-068).', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_documents_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_documents', to='organizations.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_documents_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quality document',
                'verbose_name_plural': 'Quality documents',
                'permissions': [('view_effectivedocument', 'Can view effective quality documents'), ('edit_qualitydocument', 'Can create/edit draft quality documents'), ('approve_qualitydocument', 'Can review/approve quality document versions'), ('publish_qualitydocument', 'Can make effective / retire document versions'), ('acknowledge_qualitydocument', 'Can acknowledge a document version (not training)'), ('link_qualitydocumentversion', 'Can link quality records to a document version')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QualityDocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('EFFECTIVE', 'Effective'), ('RETIRED', 'Retired')], default='DRAFT', max_length=16)),
                ('title_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('approval_reference', models.CharField(blank=True, default='', max_length=255)),
                ('evidence_attachment_id', models.UUIDField(blank=True, null=True)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('change_summary', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_document_versions_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_document_versions_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='document_control.qualitydocument')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_document_versions_published', to=settings.AUTH_USER_MODEL)),
                ('retired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_document_versions_retired', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quality document version',
                'verbose_name_plural': 'Quality document versions',
                'ordering': ('document__code', '-created_at'),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QualityDocumentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=512)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_document_events', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='document_control.qualitydocument')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='document_control.qualitydocumentversion')),
            ],
            options={
                'ordering': ('created_at',),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QualityDocumentAcknowledgement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acknowledged_at', models.DateTimeField()),
                ('is_not_competency_training', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('acknowledged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_document_acknowledgements', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgements', to='document_control.qualitydocumentversion')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QualityRecordDocumentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('linked_kind', models.CharField(max_length=64)),
                ('linked_object_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_record_document_links_created', to=settings.AUTH_USER_MODEL)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_links', to='document_control.qualitydocumentversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_record_document_links', to='organizations.organization')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='qualitydocument',
            index=models.Index(fields=['organization', 'document_kind'], name='document_co_organiz_800399_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualitydocument',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='quality_document_org_code_ci_uniq'),
        ),
        migrations.AddIndex(
            model_name='qualitydocumentversion',
            index=models.Index(fields=['document', 'status'], name='document_co_documen_80f5dd_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitydocumentversion',
            index=models.Index(fields=['status', 'effective_from'], name='document_co_status_adc29a_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualitydocumentversion',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('revision'), models.F('document'), name='quality_document_version_rev_ci_uniq'),
        ),
        migrations.AddIndex(
            model_name='qualitydocumentevent',
            index=models.Index(fields=['document', 'created_at'], name='document_co_documen_4e51d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualitydocumentacknowledgement',
            constraint=models.UniqueConstraint(fields=('version', 'acknowledged_by'), name='quality_document_ack_version_user_uniq'),
        ),
        migrations.AddIndex(
            model_name='qualityrecorddocumentlink',
            index=models.Index(fields=['organization', 'linked_kind', 'linked_object_id'], name='document_co_organiz_c6ae76_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualityrecorddocumentlink',
            constraint=models.UniqueConstraint(fields=('organization', 'linked_kind', 'linked_object_id', 'document_version'), name='quality_record_doc_link_uniq'),
        ),
    ]
