# Generated by Django 5.2.16 on 2026-08-10 05:12

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_phase04c_organization_configuration'),
        ('recall', '0001_phase37_product_recall'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockExerciseMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scope_snapshot', models.TextField(blank=True, default='')),
                ('traceback_completeness', models.CharField(choices=[('NOT_ASSESSED', 'Not assessed'), ('COMPLETE', 'Complete (operator assessment)'), ('PARTIAL', 'Partial (operator assessment)'), ('GAPS_IDENTIFIED', 'Gaps identified')], default='NOT_ASSESSED', max_length=32)),
                ('traceback_notes', models.TextField(blank=True, default='')),
                ('traceforward_completeness', models.CharField(choices=[('NOT_ASSESSED', 'Not assessed'), ('COMPLETE', 'Complete (operator assessment)'), ('PARTIAL', 'Partial (operator assessment)'), ('GAPS_IDENTIFIED', 'Gaps identified')], default='NOT_ASSESSED', max_length=32)),
                ('traceforward_notes', models.TextField(blank=True, default='')),
                ('quantity_reconciliation_notes', models.TextField(blank=True, default='', help_text='Opaque qty reconciliation notes — no invented variance rules.')),
                ('gaps', models.JSONField(blank=True, default=list, help_text='List of opaque gap descriptions — not invented scoring.')),
                ('actions', models.JSONField(blank=True, default=list, help_text='List of opaque action descriptions taken during the exercise.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mock recall exercise metrics',
                'verbose_name_plural': 'Mock recall exercise metrics',
            },
        ),
        migrations.CreateModel(
            name='MockImprovementAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='MockRecallFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('link_kind', models.CharField(choices=[('NONE', 'Finding only'), ('NCR', 'Linked nonconformance'), ('CAPA', 'Linked CAPA'), ('IMPROVEMENT', 'Linked improvement action')], default='NONE', max_length=16)),
                ('nonconformance_id', models.UUIDField(blank=True, null=True)),
                ('capa_id', models.UUIDField(blank=True, null=True)),
                ('improvement_action_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='recallcase',
            options={'permissions': [('view_recall', 'Can view recall/withdrawal cases'), ('initiate_recall', 'Can initiate recall/withdrawal cases (high-risk; not System Admin by default)'), ('manage_recallcase', 'Can update recall case scope and quantities'), ('close_recall', 'Can close recall/withdrawal cases'), ('manage_recallpolicy', 'Can manage recall policy stubs'), ('run_mock_recall', 'Can run mock recall exercises (never a real recall)'), ('manage_mock_recall_findings', 'Can record mock findings and explicitly link NCR/CAPA/improvement')], 'verbose_name': 'Recall case', 'verbose_name_plural': 'Recall cases'},
        ),
        migrations.AddField(
            model_name='recallcase',
            name='is_mock',
            field=models.BooleanField(default=False, help_text='Denormalized mock flag — must match mode=MOCK_EXERCISE.'),
        ),
        migrations.AddField(
            model_name='recallcase',
            name='mode',
            field=models.CharField(choices=[('REAL', 'Real recall / withdrawal'), ('MOCK_EXERCISE', 'MOCK EXERCISE — not a real recall')], default='REAL', help_text='REAL vs MOCK_EXERCISE — mock never affects live inventory/notify.', max_length=16),
        ),
        migrations.AddIndex(
            model_name='recallcase',
            index=models.Index(fields=['organization', 'is_mock'], name='recall_reca_organiz_397d00_idx'),
        ),
        migrations.AddIndex(
            model_name='recallcase',
            index=models.Index(fields=['organization', 'mode'], name='recall_reca_organiz_9c035a_idx'),
        ),
        migrations.AddConstraint(
            model_name='recallcase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_mock', True), ('mode', 'MOCK_EXERCISE')), models.Q(('is_mock', False), ('mode', 'REAL')), _connector='OR'), name='recall_case_mock_mode_consistent'),
        ),
        migrations.AddField(
            model_name='mockexercisemetrics',
            name='recall_case',
            field=models.OneToOneField(limit_choices_to={'is_mock': True}, on_delete=django.db.models.deletion.PROTECT, related_name='mock_metrics', to='recall.recallcase'),
        ),
        migrations.AddField(
            model_name='mockexercisemetrics',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mock_recall_metrics_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mockimprovementaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mock_improvement_actions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mockimprovementaction',
            name='recall_case',
            field=models.ForeignKey(limit_choices_to={'is_mock': True}, on_delete=django.db.models.deletion.PROTECT, related_name='mock_improvement_actions', to='recall.recallcase'),
        ),
        migrations.AddField(
            model_name='mockrecallfinding',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mock_recall_findings_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mockrecallfinding',
            name='recall_case',
            field=models.ForeignKey(limit_choices_to={'is_mock': True}, on_delete=django.db.models.deletion.PROTECT, related_name='mock_findings', to='recall.recallcase'),
        ),
        migrations.AddField(
            model_name='mockimprovementaction',
            name='finding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='improvement_actions', to='recall.mockrecallfinding'),
        ),
        migrations.AddIndex(
            model_name='mockrecallfinding',
            index=models.Index(fields=['recall_case', 'link_kind'], name='recall_mock_recall__b8575e_idx'),
        ),
        migrations.AddConstraint(
            model_name='mockimprovementaction',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('recall_case'), name='mock_improvement_case_code_ci_uniq'),
        ),
    ]
