# Generated by Django 5.2.16 on 2026-08-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_audit', '0001_phase03_accounts_rbac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityauditevent',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILURE', 'Login failure'), ('ACCOUNT_LOCKED', 'Account locked'), ('ACCOUNT_UNLOCKED', 'Account unlocked'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Password changed'), ('PASSWORD_RESET_BY_ADMIN', 'Password reset by admin'), ('USER_ACTIVATED', 'User activated'), ('USER_DEACTIVATED', 'User deactivated'), ('ROLE_ASSIGNED', 'Role assigned'), ('ROLE_REVOKED', 'Role revoked'), ('SHIFT_CREATED', 'Shift created'), ('SHIFT_UPDATED', 'Shift updated'), ('SHIFT_ACTIVATED', 'Shift activated'), ('SHIFT_DEACTIVATED', 'Shift deactivated')], max_length=64),
        ),
    ]
