# Generated by Django 5.2.16 on 2026-08-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_audit', '0013_phase06l_control_point_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityauditevent',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILURE', 'Login failure'), ('ACCOUNT_LOCKED', 'Account locked'), ('ACCOUNT_UNLOCKED', 'Account unlocked'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Password changed'), ('PASSWORD_RESET_BY_ADMIN', 'Password reset by admin'), ('USER_ACTIVATED', 'User activated'), ('USER_DEACTIVATED', 'User deactivated'), ('ROLE_ASSIGNED', 'Role assigned'), ('ROLE_REVOKED', 'Role revoked'), ('SHIFT_CREATED', 'Shift created'), ('SHIFT_UPDATED', 'Shift updated'), ('SHIFT_ACTIVATED', 'Shift activated'), ('SHIFT_DEACTIVATED', 'Shift deactivated'), ('FG_PRODUCT_CREATED', 'FG Product created'), ('FG_PRODUCT_UPDATED', 'FG Product updated'), ('FG_PRODUCT_ACTIVATED', 'FG Product activated'), ('FG_PRODUCT_DEACTIVATED', 'FG Product deactivated'), ('CHECKLIST_TEMPLATE_CREATED', 'Checklist template created'), ('CHECKLIST_TEMPLATE_UPDATED', 'Checklist template updated'), ('CHECKLIST_TEMPLATE_ACTIVATED', 'Checklist template activated'), ('CHECKLIST_TEMPLATE_DEACTIVATED', 'Checklist template deactivated'), ('CHECKLIST_VERSION_CREATED', 'Checklist version created'), ('CHECKLIST_VERSION_CLONED', 'Checklist version cloned'), ('CHECKLIST_VERSION_PUBLISHED', 'Checklist version published'), ('CHECKLIST_VERSION_RETIRED', 'Checklist version retired'), ('CHECKLIST_ITEM_EVALUATION_RULE_SET', 'Checklist item evaluation rule set'), ('CHECKLIST_ITEM_EVALUATION_RULE_CLEARED', 'Checklist item evaluation rule cleared'), ('CHECKLIST_ITEM_CONTROL_POINT_METADATA_UPDATED', 'Checklist item control-point metadata updated'), ('CHECKLIST_ITEM_MEASUREMENT_SEMANTICS_UPDATED', 'Checklist item measurement semantics updated'), ('CHECKLIST_TASK_CREATED', 'Checklist task created'), ('CHECKLIST_TASK_CANCELLED', 'Checklist task cancelled'), ('CHECKLIST_RECORD_STARTED', 'Checklist record started'), ('CHECKLIST_RECORD_DRAFT_SAVED', 'Checklist record draft saved'), ('CHECKLIST_RECORD_SUBMITTED', 'Checklist record submitted'), ('SUPERVISOR_REVIEW_COMPLETED', 'Supervisor review completed'), ('CHECKLIST_CORRECTION_STARTED', 'Checklist correction started'), ('CHECKLIST_CORRECTION_RESUBMITTED', 'Checklist correction resubmitted'), ('QA_REVIEW_COMPLETED', 'QA review disposition completed'), ('NONCONFORMANCE_CREATED', 'Nonconformance created'), ('NONCONFORMANCE_CLOSED', 'Nonconformance closed'), ('CAPA_CREATED', 'CAPA created'), ('CAPA_CLOSED', 'CAPA closed'), ('SUPPLIER_QUALITY_PROFILE_CREATED', 'Supplier quality profile created'), ('SUPPLIER_QUALITY_PROFILE_UPDATED', 'Supplier quality profile updated'), ('SUPPLIER_CERTIFICATE_RECORDED', 'Supplier certificate recorded'), ('SUPPLIER_CERTIFICATE_VERIFIED', 'Supplier certificate verified'), ('SUPPLIER_QUALITY_EVENT_RECORDED', 'Supplier quality event recorded')], max_length=64),
        ),
    ]
