# Generated by Django 5.2.16 on 2026-08-10 03:32

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0012_phase25_device_traceability'),
        ('laboratory', '0001_phase22_laboratory_foundation'),
        ('organizations', '0003_phase04c_organization_configuration'),
        ('supplier_quality', '0001_phase32_supplier_quality_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_material_reference', models.CharField(help_text='External ERP/Bileeta material / item identifier — preferred key.', max_length=128)),
                ('display_name', models.CharField(blank=True, default='', help_text='Local label only — official description remains ERP-owned.', max_length=255)),
                ('uom_reference', models.CharField(blank=True, default='', help_text='Opaque UOM reference — catalogue EVIDENCE REQUIRED.', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_references_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_references', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Material reference',
                'verbose_name_plural': 'Material references',
                'ordering': ('organization__code', 'erp_material_reference'),
                'permissions': [('manage_materialreference', 'Can manage ERP-mapped material reference shells'), ('manage_receiptquality', 'Can create/edit raw material receipt quality records'), ('disposition_receiptquality', 'Can set receipt quality disposition (ACCEPTED/HOLD/REJECTED)'), ('view_receiptquality', 'Can view receipt quality / material receiving records'), ('manage_materialspecification', 'Can draft material specification versions'), ('approve_materialspecification', 'Can approve/retire material specification versions')],
            },
        ),
        migrations.CreateModel(
            name='MaterialSpecification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_specifications_created', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specifications', to='receiving.materialreference')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_specifications', to='organizations.organization')),
            ],
            options={
                'ordering': ('material__erp_material_reference', 'code'),
            },
        ),
        migrations.CreateModel(
            name='MaterialSpecificationVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('RETIRED', 'Retired')], default='DRAFT', max_length=16)),
                ('change_summary', models.TextField(blank=True, default='')),
                ('approval_reference', models.CharField(blank=True, default='', help_text='Opaque company approval reference — not invented.', max_length=255)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_spec_versions_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_spec_versions_created', to=settings.AUTH_USER_MODEL)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='receiving.materialspecification')),
            ],
            options={
                'ordering': ('specification__code', '-version_number'),
            },
        ),
        migrations.CreateModel(
            name='MaterialSpecificationParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('bound_min', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('bound_max', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Bounds remain EVIDENCE REQUIRED until company specs approved.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='receiving.materialspecificationversion')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='ReceiptQualityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_receipt_reference', models.CharField(help_text='ERP GRN / goods-receipt reference — inventory ownership remains ERP.', max_length=128)),
                ('supplier_lot', models.CharField(help_text='Supplier lot / batch identity as received.', max_length=128)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('uom', models.CharField(blank=True, default='', max_length=32)),
                ('received_date', models.DateField(default=django.utils.timezone.localdate)),
                ('quality_state', models.CharField(choices=[('PENDING_INSPECTION', 'Pending inspection'), ('ACCEPTED', 'Accepted'), ('HOLD', 'Hold'), ('REJECTED', 'Rejected')], default='PENDING_INSPECTION', max_length=32)),
                ('disposition_notes', models.TextField(blank=True, default='')),
                ('evidence_object_key', models.CharField(blank=True, default='', max_length=512)),
                ('evidence_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('frozen_receipt_context', models.JSONField(blank=True, default=dict)),
                ('dispositioned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispositioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_quality_dispositioned', to=settings.AUTH_USER_MODEL)),
                ('inspection_checklist_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_quality_records', to='checklists.checklisttemplate')),
                ('inspection_checklist_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_quality_records', to='checklists.checklistversion')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_quality_records', to='receiving.materialreference')),
                ('material_specification_version', models.ForeignKey(blank=True, help_text='Optional approved material spec version — no invented limits.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_quality_records', to='receiving.materialspecificationversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_quality_records', to='organizations.organization')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_quality_recorded', to=settings.AUTH_USER_MODEL)),
                ('supplier_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_quality_records', to='supplier_quality.supplierqualityprofile')),
            ],
            options={
                'verbose_name': 'Receipt quality record',
                'verbose_name_plural': 'Receipt quality records',
                'ordering': ('-received_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ReceiptLabSampleLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('lab_sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_quality_links', to='laboratory.labsample')),
                ('linked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lab_sample_links', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_sample_links', to='receiving.receiptqualityrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivingHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiving_history_actions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiving_history_entries', to='organizations.organization')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history_entries', to='receiving.receiptqualityrecord')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='materialreference',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('erp_material_reference'), models.F('organization'), name='receiving_material_erp_ref_org_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='materialspecification',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='receiving_material_spec_org_code_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='materialspecificationversion',
            constraint=models.UniqueConstraint(fields=('specification', 'version_number'), name='receiving_material_spec_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='materialspecificationparameter',
            constraint=models.UniqueConstraint(fields=('version', 'code'), name='receiving_material_spec_param_uniq'),
        ),
        migrations.AddIndex(
            model_name='receiptqualityrecord',
            index=models.Index(fields=['organization', 'erp_receipt_reference'], name='receiving_r_organiz_99437b_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptqualityrecord',
            index=models.Index(fields=['organization', 'supplier_lot'], name='receiving_r_organiz_283185_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptqualityrecord',
            index=models.Index(fields=['organization', 'quality_state'], name='receiving_r_organiz_7b9abf_idx'),
        ),
        migrations.AddConstraint(
            model_name='receiptqualityrecord',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('erp_receipt_reference'), models.F('organization'), models.F('supplier_lot'), models.F('material'), name='receiving_receipt_org_grn_lot_material_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='receiptlabsamplelink',
            constraint=models.UniqueConstraint(fields=('receipt', 'lab_sample'), name='receiving_receipt_lab_sample_uniq'),
        ),
    ]
