# Generated by Django 5.2.16 on 2026-08-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0006_phase06k_item_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='control_point_class',
            field=models.CharField(choices=[('NONE', 'None (unset / not classified)'), ('CCP', 'CCP (evidence-gated)'), ('OPRP', 'OPRP (evidence-gated)'), ('PRP', 'PRP (evidence-gated)'), ('GMP', 'GMP (evidence-gated)'), ('QUALITY', 'Quality (evidence-gated)')], default='NONE', help_text='Generic control-point taxonomy (ADR-019). Default NONE. Non-NONE production classifications require ASM-002 / APR-027 evidence. Does not auto HOLD/REJECT/RELEASE.', max_length=16),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='criticality',
            field=models.CharField(blank=True, choices=[('MINOR', 'Minor'), ('MAJOR', 'Major'), ('CRITICAL', 'Critical')], default='', help_text='Optional criticality metadata (MINOR/MAJOR/CRITICAL). Blank = unset. Never auto-assigned. Not a disposition rule.', max_length=16),
        ),
    ]
