# Generated by Django 5.2.16 on 2026-08-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0007_phase06l_control_point_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='decimal_precision',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional Decimal scale for NUMBER items. Null = no forced quantize (do not invent a business default).', null=True),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='max_inclusive',
            field=models.BooleanField(default=True, help_text='Whether maximum_value is inclusive (informational bounds).'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='min_inclusive',
            field=models.BooleanField(default=True, help_text='Whether minimum_value is inclusive (informational bounds).'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='rounding_mode',
            field=models.CharField(blank=True, choices=[('HALF_UP', 'Half up'), ('HALF_EVEN', "Half even (banker's)"), ('FLOOR', 'Floor'), ('CEILING', 'Ceiling'), ('DOWN', 'Toward zero')], default='', help_text='Optional closed rounding mode (HALF_UP/HALF_EVEN/FLOOR/CEILING/DOWN). Empty = no rounding. Applied only together with decimal_precision.', max_length=16),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='unit',
            field=models.CharField(blank=True, default='', help_text='Optional technical unit catalog code for NUMBER items. Not a limit.', max_length=32),
        ),
    ]
