# Generated by Django 5.2.16 on 2026-08-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0008_phase06m_measurement_semantics"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistitem",
            name="requires_equipment_reference",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "When True, future recording may require an equipment reference "
                    "for this item. Default False — does not force existing checklist "
                    "items. Overdue block/warn policy remains EVIDENCE REQUIRED."
                ),
            ),
        ),
    ]
