# Generated by Django 5.2.16 on 2026-08-09 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0009_phase05d_equipment_calibration'),
        ('master_data', '0003_phase06o_product_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitemevaluationrule',
            name='specification_parameter',
            field=models.ForeignKey(blank=True, help_text='Optional SpecificationParameter pin (must belong to specification_version). Bounds empty until APR-006 evidence => NOT_EVALUATED.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_evaluation_rules', to='master_data.specificationparameter'),
        ),
        migrations.AddField(
            model_name='checklistitemevaluationrule',
            name='specification_version',
            field=models.ForeignKey(blank=True, help_text='Optional exact SpecificationVersion pin for SPECIFICATION_PARAMETER rules. Historical pins remain valid after version retirement.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_evaluation_rules', to='master_data.specificationversion'),
        ),
        migrations.AlterField(
            model_name='checklistitemevaluationrule',
            name='rule_kind',
            field=models.CharField(choices=[('NUMERIC_BOUNDS', 'Numeric bounds'), ('EXPECTED_CHOICE', 'Expected YES/NO choice'), ('EXPECTED_OPTION', 'Expected SELECT option'), ('CALCULATED_NUMERIC_BOUNDS', 'Calculated numeric bounds'), ('SPECIFICATION_PARAMETER', 'Pinned product specification parameter (Phase 06O)')], max_length=32),
        ),
    ]
