# Generated by Django 5.2.16 on 2026-08-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0010_phase06o_product_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistversion',
            name='effective_from',
            field=models.DateTimeField(blank=True, help_text='Optional inclusive start of PUBLISHED eligibility (UTC). Blank = unbounded start. APR-015 as-of policy unresolved.', null=True),
        ),
        migrations.AddField(
            model_name='checklistversion',
            name='effective_to',
            field=models.DateTimeField(blank=True, help_text='Optional inclusive end of PUBLISHED eligibility (UTC). Blank = unbounded end. APR-015 as-of policy unresolved.', null=True),
        ),
        migrations.AddIndex(
            model_name='checklistversion',
            index=models.Index(fields=['template', 'status', 'effective_from', 'effective_to'], name='chk_version_tmpl_effect_idx'),
        ),
        migrations.AddConstraint(
            model_name='checklistversion',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='chk_version_effective_window_valid'),
        ),
    ]
