# Generated by Django 5.2.16 on 2026-08-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0011_phase07d_effective_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='required_equipment_type',
            field=models.CharField(blank=True, default='', help_text='Optional equipment-type filter (SCALE/THERMOMETER/…). Blank = any type. Does not invent a company type catalogue beyond the technical taxonomy.', max_length=32),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='requires_equipment_reference',
            field=models.BooleanField(default=False, help_text='When True, recording may require an equipment / device reference for this item. Default False — does not force existing checklist items. Overdue block/warn policy remains company-configured (Phase 25).'),
        ),
    ]
