# Generated by Django 5.2.16 on 2026-08-10 05:48

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0012_phase25_device_traceability'),
        ('nonconformance', '0002_phase12_ncr_hold_capa_foundation'),
        ('organizations', '0003_phase04c_organization_configuration'),
        ('scheduling', '0007_phase07h_due_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnQualityPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_stock_movement_enabled', models.BooleanField(default=False, help_text='Org gate only; settings approval and an approved adapter are also required.')),
                ('allowed_disposition_codes', models.JSONField(blank=True, default=list)),
                ('procedure_reference', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='return_quality_policy', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_quality_policies_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'return quality policy stub',
                'verbose_name_plural': 'return quality policy stubs',
                'permissions': [('manage_returnpolicystub', 'Can manage returned-product quality policy stubs')],
            },
        ),
        migrations.CreateModel(
            name='ReturnQualityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_return_reference', models.CharField(max_length=128)),
                ('erp_return_line_reference', models.CharField(blank=True, default='', max_length=128)),
                ('product_reference', models.CharField(max_length=128)),
                ('original_batch_reference', models.CharField(max_length=128)),
                ('quantity_reference', models.CharField(blank=True, default='', max_length=128)),
                ('uom_reference', models.CharField(blank=True, default='', max_length=64)),
                ('erp_customer_reference', models.CharField(blank=True, default='', max_length=128)),
                ('reason_reference', models.CharField(blank=True, default='', max_length=255)),
                ('condition_reference', models.CharField(blank=True, default='', max_length=255)),
                ('temperature_reference', models.CharField(blank=True, default='', max_length=255)),
                ('evidence_attachment_id', models.UUIDField(blank=True, null=True)),
                ('received_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('INSPECTION_IN_PROGRESS', 'Inspection in progress'), ('READY_FOR_DISPOSITION', 'Ready for disposition'), ('DISPOSITIONED', 'Dispositioned locally')], default='RECEIVED', max_length=32)),
                ('quarantine_state', models.CharField(choices=[('QUARANTINED', 'Quarantined'), ('HOLD', 'Hold'), ('REWORK', 'Rework'), ('REJECTED', 'Rejected')], default='QUARANTINED', max_length=16)),
                ('not_saleable_via_app', models.BooleanField(default=True, editable=False, help_text='Invariant: this application never makes returned stock saleable.')),
                ('disposition', models.CharField(blank=True, choices=[('RELEASE', 'Release (local quality only)'), ('HOLD', 'Hold'), ('REWORK', 'Rework'), ('REJECT', 'Reject')], default='', max_length=16)),
                ('disposition_note', models.TextField(blank=True, default='')),
                ('dispositioned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_quality_records_for_task', to='scheduling.checklisttask')),
                ('checklist_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_quality_records_for_template', to='checklists.checklisttemplate')),
                ('checklist_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_quality_records_for_version', to='checklists.checklistversion')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_quality_records_created', to=settings.AUTH_USER_MODEL)),
                ('dispositioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_quality_dispositions', to=settings.AUTH_USER_MODEL)),
                ('hold_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_quality_records', to='nonconformance.holdcase')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_quality_records', to='organizations.organization')),
            ],
            options={
                'ordering': ('-received_at', '-created_at'),
                'permissions': [('view_returnquality', 'Can view returned-product quality records'), ('manage_returnquality', 'Can manage returned-product quality records'), ('inspect_returnquality', 'Can inspect returned-product quality records'), ('disposition_returnquality', 'Can disposition returned-product quality records')],
            },
        ),
        migrations.CreateModel(
            name='ReturnQualityTimelineEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_quality_timeline_actions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_quality_timeline_entries', to='organizations.organization')),
                ('return_quality_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeline_entries', to='product_returns.returnqualityrecord')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='returnqualityrecord',
            index=models.Index(fields=['organization', 'status'], name='return_quality_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='returnqualityrecord',
            index=models.Index(fields=['organization', 'original_batch_reference'], name='return_quality_org_batch_idx'),
        ),
        migrations.AddConstraint(
            model_name='returnqualityrecord',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('erp_return_reference'), django.db.models.functions.text.Lower('erp_return_line_reference'), models.F('organization'), name='return_quality_erp_line_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='returnqualityrecord',
            constraint=models.CheckConstraint(condition=models.Q(('not_saleable_via_app', True)), name='return_quality_never_saleable'),
        ),
    ]
