# Generated by Django 5.2.16 on 2026-08-07 09:23

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_phase04a_shift_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FGProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fg_products', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'FG Product',
                'verbose_name_plural': 'FG Products',
                'ordering': ('organization__code', 'code'),
                'permissions': [('manage_fgproduct', 'Can manage FG product')],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='md_fgproduct_org_act_idx'), models.Index(django.db.models.functions.text.Lower('code'), name='md_fgproduct_code_lower_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='md_fgproduct_org_code_ci_uniq')],
            },
        ),
    ]
