# Generated by Django 5.2.16 on 2026-08-09 22:15

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0001_phase05a_fg_product_foundation"),
        ("organizations", "0003_phase04c_organization_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="fgproduct",
            name="barcode",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional barcode / SKU reference.",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="fgproduct",
            name="brand",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="fgproduct",
            name="category",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="fgproduct",
            name="effective_from",
            field=models.DateField(
                blank=True,
                help_text="Optional effective-from date. Blank until business rules evidenced.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fgproduct",
            name="effective_to",
            field=models.DateField(
                blank=True,
                help_text="Optional effective-to date. Prefer over hard delete.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fgproduct",
            name="erp_item_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Optional ERP / Bileeta item mapping reference. "
                    "Not primary Product identity."
                ),
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="fgproduct",
            name="label_artwork_reference",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional label / artwork document reference.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="fgproduct",
            name="pack_size",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="fgproduct",
            name="shelf_life_reference",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Optional shelf-life document / policy reference — "
                    "not a computed limit."
                ),
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="fgproduct",
            name="storage_category",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Optional storage-category label only. "
                    "Not a CCP/temperature class approval."
                ),
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="fgproduct",
            name="uom",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Unit of measure label (free text). No seeded UOM catalogue.",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="fgproduct",
            index=models.Index(
                django.db.models.functions.text.Lower("erp_item_code"),
                name="md_fgproduct_erp_lower_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fgproduct",
            index=models.Index(
                fields=["organization", "category"],
                name="md_fgproduct_org_cat_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="fgproduct",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("erp_item_code"),
                models.F("organization"),
                condition=models.Q(("erp_item_code", ""), _negated=True),
                name="md_fgproduct_org_erp_ci_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="fgproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_from__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="md_fgproduct_effective_window_valid",
            ),
        ),
    ]
