# Generated by Django 5.2.16 on 2026-08-10 03:46

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_phase04c_organization_configuration'),
        ('receiving', '0001_phase31_raw_material_quality'),
        ('recording', '0012_phase25_device_traceability'),
        ('reviews', '0002_phase09c_supervisor_governance'),
        ('sampling', '0001_phase24_sampling_engine'),
        ('scheduling', '0007_phase07h_due_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IqcInspectionCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_status', models.CharField(choices=[('OPEN', 'Open'), ('TASK_CREATED', 'IQC task created'), ('INSPECTION_IN_PROGRESS', 'Inspection in progress'), ('AWAITING_REVIEW', 'Awaiting review'), ('DISPOSITIONED', 'Dispositioned (local)'), ('CLOSED', 'Closed')], default='OPEN', max_length=32)),
                ('review_required', models.BooleanField(default=True, help_text='When True, disposition requires Supervisor APPROVED review.')),
                ('sampling_snapshot', models.JSONField(blank=True, default=dict)),
                ('frozen_traceability_context', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('checklist_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iqc_inspection_cases', to='recording.checklistsubmission')),
                ('checklist_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iqc_inspection_cases', to='scheduling.checklisttask')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iqc_cases_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iqc_inspection_cases', to='organizations.organization')),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='iqc_case', to='receiving.receiptqualityrecord')),
                ('sampling_plan_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iqc_inspection_cases', to='sampling.samplingplanversion')),
                ('supervisor_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iqc_inspection_cases', to='reviews.supervisorreview')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IqcHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iqc_history_actions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iqc_history_entries', to='organizations.organization')),
                ('inspection_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history_entries', to='iqc.iqcinspectioncase')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IncomingReceiptEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(max_length=64)),
                ('source_event_id', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('DUPLICATE', 'Duplicate (idempotent)'), ('FAILED', 'Failed')], default='RECEIVED', max_length=16)),
                ('erp_receipt_reference', models.CharField(max_length=128)),
                ('erp_supplier_reference', models.CharField(blank=True, default='', max_length=128)),
                ('supplier_lot', models.CharField(max_length=128)),
                ('erp_material_reference', models.CharField(max_length=128)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('uom', models.CharField(blank=True, default='', max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_receipt_events_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_receipt_events', to='organizations.organization')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_events', to='receiving.receiptqualityrecord')),
                ('inspection_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_events', to='iqc.iqcinspectioncase')),
            ],
            options={
                'ordering': ('-created_at',),
                'permissions': [('manage_iqc', 'Can manage IQC workflow / ingest receipt events'), ('disposition_iqc', 'Can complete IQC local disposition'), ('view_iqc', 'Can view IQC inspection cases'), ('manage_iqcpolicy', 'Can update IQC workflow policy stubs')],
            },
        ),
        migrations.CreateModel(
            name='IqcWorkflowPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_required', models.BooleanField(default=True)),
                ('erp_outbound_enabled', models.BooleanField(default=False, help_text='Org stub only — still requires IQC_ERP_OUTBOUND_APPROVED.')),
                ('procedure_reference', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='iqc_workflow_policy', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iqc_policies_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IQC workflow policy',
                'verbose_name_plural': 'IQC workflow policies',
            },
        ),
        migrations.AddIndex(
            model_name='iqcinspectioncase',
            index=models.Index(fields=['organization', 'workflow_status'], name='iqc_iqcinsp_organiz_0b88f3_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingreceiptevent',
            index=models.Index(fields=['organization', 'erp_receipt_reference'], name='iqc_incomin_organiz_72880f_idx'),
        ),
        migrations.AddConstraint(
            model_name='incomingreceiptevent',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('source_system'), django.db.models.functions.text.Lower('source_event_id'), name='iqc_incoming_event_source_ci_uniq'),
        ),
    ]
