# Generated by Django 5.2.16 on 2026-08-10 02:28

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0012_phase25_device_traceability'),
        ('instruments', '0002_phase25_device_traceability'),
        ('nonconformance', '0002_phase12_ncr_hold_capa_foundation'),
        ('organizations', '0003_phase04c_organization_configuration'),
        ('scheduling', '0007_phase07h_due_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeScheduleRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('schedule_mode', models.CharField(choices=[('AD_HOC', 'Ad hoc'), ('SHIFT', 'Shift-based'), ('BATCH', 'Batch-linked'), ('CHECKLIST_TASK', 'Checklist / scheduler task')], default='AD_HOC', max_length=32)),
                ('rule_code', models.CharField(blank=True, default='', help_text='Opaque company schedule/rule reference — not an invented frequency.', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foreign_body_schedule_rules', to='checklists.checklisttemplate')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foreign_body_schedule_rules_created', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foreign_body_schedule_rules', to='instruments.equipment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foreign_body_schedule_rules', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Challenge schedule rule',
                'verbose_name_plural': 'Challenge schedule rules',
                'ordering': ('organization__code', 'code'),
            },
        ),
        migrations.CreateModel(
            name='MetalDetectorChallengeTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('production_line_code', models.CharField(blank=True, default='', max_length=64)),
                ('batch_reference', models.CharField(blank=True, default='', max_length=128)),
                ('sub_lot_reference', models.CharField(blank=True, default='', max_length=128)),
                ('performed_at', models.DateTimeField()),
                ('expected_detected', models.BooleanField(help_text='Snapshot of configured expectation at record time.')),
                ('observed_detected', models.BooleanField(blank=True, help_text='Whether the detector indicated detection/reject during the challenge.', null=True)),
                ('result', models.CharField(choices=[('NOT_EVALUATED', 'Not evaluated'), ('PASS', 'Pass'), ('FAIL', 'Fail')], default='NOT_EVALUATED', max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RECORDED', 'Recorded'), ('VERIFIED', 'Verified'), ('VOID', 'Void (retained)')], default='DRAFT', max_length=16)),
                ('schedule_mode', models.CharField(choices=[('AD_HOC', 'Ad hoc'), ('SHIFT', 'Shift-based'), ('BATCH', 'Batch-linked'), ('CHECKLIST_TASK', 'Checklist / scheduler task')], default='AD_HOC', max_length=32)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_reference', models.CharField(blank=True, default='', help_text='Opaque evidence/attachment reference (secure evidence module later).', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('frozen_device_context', models.JSONField(blank=True, default=dict)),
                ('frozen_test_piece_context', models.JSONField(blank=True, default=dict)),
                ('void_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foreign_body_challenge_tests', to='scheduling.checklisttask')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foreign_body_challenges_created', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metal_detector_challenge_tests', to='instruments.equipment')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foreign_body_challenges_operated', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metal_detector_challenge_tests', to='organizations.organization')),
                ('schedule_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='challenge_tests', to='foreign_body.challengeschedulerule')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metal_detector_challenge_tests', to='organizations.site')),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foreign_body_challenges_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Metal detector challenge test',
                'verbose_name_plural': 'Metal detector challenge tests',
                'ordering': ('-performed_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ForeignBodyHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foreign_body_history_actions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foreign_body_history_entries', to='organizations.organization')),
                ('challenge_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='foreign_body.metaldetectorchallengetest')),
            ],
            options={
                'verbose_name': 'Foreign-body history entry',
                'verbose_name_plural': 'Foreign-body history entries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ContainmentAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interval_start', models.DateTimeField(blank=True, null=True)),
                ('interval_end', models.DateTimeField(blank=True, null=True)),
                ('affected_batch_references', models.JSONField(blank=True, default=list)),
                ('hold_recommended', models.BooleanField(default=False, help_text='Advisory only — not a QA HOLD disposition.')),
                ('hold_created', models.BooleanField(default=False, help_text='True only when auto-HOLD was explicitly approved and executed.')),
                ('assessment_context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foreign_body_containments_created', to=settings.AUTH_USER_MODEL)),
                ('hold_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foreign_body_containment_assessments', to='nonconformance.holdcase')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foreign_body_containment_assessments', to='organizations.organization')),
                ('failed_test', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='containment_assessment', to='foreign_body.metaldetectorchallengetest')),
                ('previous_pass_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='containment_as_previous_pass', to='foreign_body.metaldetectorchallengetest')),
            ],
            options={
                'verbose_name': 'Foreign-body containment assessment',
                'verbose_name_plural': 'Foreign-body containment assessments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TestPiece',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('category_label', models.CharField(blank=True, default='', help_text='Opaque material/category label (company-supplied). Not a seeded Fe/SS table.', max_length=64)),
                ('size_label', models.CharField(blank=True, default='', help_text='Opaque size/sensitivity label. Leave blank until company evidence loads values.', max_length=64)),
                ('expected_detected', models.BooleanField(default=True, help_text='Configured expected detection outcome for this piece (company-approved).')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foreign_body_test_pieces_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foreign_body_test_pieces', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Test piece',
                'verbose_name_plural': 'Test pieces',
                'ordering': ('organization__code', 'code'),
                'permissions': [('manage_testpiece', 'Can manage foreign-body test-piece catalogue'), ('record_challengeresult', 'Can record metal-detector challenge tests'), ('verify_challengeresult', 'Can verify metal-detector challenge tests'), ('view_foreignbody', 'Can view foreign-body challenge history')],
            },
        ),
        migrations.AddField(
            model_name='metaldetectorchallengetest',
            name='test_piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challenge_tests', to='foreign_body.testpiece'),
        ),
        migrations.AddConstraint(
            model_name='challengeschedulerule',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='fb_schedule_rule_org_code_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='testpiece',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='fb_test_piece_org_code_ci_uniq'),
        ),
        migrations.AddIndex(
            model_name='metaldetectorchallengetest',
            index=models.Index(fields=['organization', 'performed_at'], name='fb_challenge_org_perf_idx'),
        ),
        migrations.AddIndex(
            model_name='metaldetectorchallengetest',
            index=models.Index(fields=['equipment', 'performed_at'], name='fb_challenge_equip_perf_idx'),
        ),
        migrations.AddIndex(
            model_name='metaldetectorchallengetest',
            index=models.Index(fields=['organization', 'batch_reference'], name='fb_challenge_org_batch_idx'),
        ),
    ]
