# Generated by Django 5.2.16 on 2026-08-11 05:45

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capa', '0003_phase12_ncr_hold_capa_foundation'),
        ('change_control', '0001_phase44_change_control'),
        ('organizations', '0003_phase04c_organization_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureMode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode_code', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_fmea_modes_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FailureEffect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_fmea_effects_created', to=settings.AUTH_USER_MODEL)),
                ('failure_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='effects', to='process_fmea.failuremode')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CurrentControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('control_reference', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_fmea_controls_created', to=settings.AUTH_USER_MODEL)),
                ('failure_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_controls', to='process_fmea.failuremode')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PotentialCause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_fmea_causes_created', to=settings.AUTH_USER_MODEL)),
                ('failure_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='causes', to='process_fmea.failuremode')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProcessFmea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fmea_code', models.CharField(help_text='Owner-supplied PFMEA identifier (not seeded).', max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('process_reference', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_fmeas_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_fmeas', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Process FMEA',
                'verbose_name_plural': 'Process FMEAs',
                'permissions': [('view_processfmea', 'Can view process FMEA records'), ('manage_processfmea', 'Can draft and maintain process FMEA versions'), ('approve_processfmea', 'Can approve process FMEA versions'), ('configure_processfmeascoring', 'Can configure owner-cited FMEA scoring'), ('link_processfmea_action', 'Can link recommended actions to CAPA/change')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProcessFmeaScoringPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scoring_enabled', models.BooleanField(default=False)),
                ('formula_kind', models.CharField(choices=[('NONE', 'No automatic calculation'), ('SOD_PRODUCT', 'Mathematical S×O×D after explicit configuration'), ('OWNER_SUPPLIED', 'Owner-supplied score text only')], default='NONE', max_length=16)),
                ('formula_citation', models.CharField(blank=True, default='', help_text='Official owner-cited scoring method. Empty until APR-073.', max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_fmea_scoring_policies', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_fmea_scoring_policies_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProcessFmeaVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('SUPERSEDED', 'Superseded'), ('WITHDRAWN', 'Withdrawn')], default='DRAFT', max_length=16)),
                ('scoring_enabled', models.BooleanField(default=False)),
                ('formula_kind', models.CharField(choices=[('NONE', 'No automatic calculation'), ('SOD_PRODUCT', 'Mathematical S×O×D after explicit configuration'), ('OWNER_SUPPLIED', 'Owner-supplied score text only')], default='NONE', max_length=16)),
                ('formula_citation', models.CharField(blank=True, default='', max_length=512)),
                ('revision_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='process_fmea_versions_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_fmea_versions_created', to=settings.AUTH_USER_MODEL)),
                ('fmea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='process_fmea.processfmea')),
            ],
            options={
                'ordering': ('version_number',),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProcessFmeaLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_kind', models.CharField(choices=[('PROCESS', 'Process'), ('HACCP', 'HACCP'), ('CHECKLIST', 'Checklist'), ('RISK', 'Quality risk'), ('NCR', 'Nonconformance'), ('CAPA', 'CAPA'), ('CHANGE_CONTROL', 'Change control')], max_length=32)),
                ('linked_object_id', models.UUIDField(blank=True, null=True)),
                ('citation', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_fmea_links_created', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='process_fmea.processfmeaversion')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProcessFmeaEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=512)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='process_fmea_events', to=settings.AUTH_USER_MODEL)),
                ('fmea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='process_fmea.processfmea')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='process_fmea.processfmeaversion')),
            ],
            options={
                'ordering': ('created_at',),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_code', models.CharField(max_length=64)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_fmea_steps_created', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_steps', to='process_fmea.processfmeaversion')),
            ],
            options={
                'ordering': ('sequence', 'step_code'),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='failuremode',
            name='process_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='failure_modes', to='process_fmea.processstep'),
        ),
        migrations.CreateModel(
            name='RecommendedAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.CharField(max_length=512)),
                ('action_kind', models.CharField(choices=[('CAPA', 'CAPA'), ('CHANGE_REQUEST', 'Change request'), ('ACTION', 'Owner follow-up')], default='ACTION', max_length=16)),
                ('citation', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='process_fmea_actions', to='change_control.qualitychangerequest')),
                ('corrective_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='process_fmea_actions', to='capa.correctiveaction')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_fmea_actions_created', to=settings.AUTH_USER_MODEL)),
                ('failure_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommended_actions', to='process_fmea.failuremode')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FailureModeAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_number', models.PositiveIntegerField()),
                ('severity_input', models.CharField(blank=True, default='', max_length=64)),
                ('occurrence_input', models.CharField(blank=True, default='', max_length=64)),
                ('detection_input', models.CharField(blank=True, default='', max_length=64)),
                ('computed_score_text', models.CharField(blank=True, default='', help_text='Mathematical product or owner text. Allowed only when scoring is configured.', max_length=64)),
                ('method_citation', models.CharField(blank=True, default='', max_length=512)),
                ('notes', models.TextField(blank=True, default='')),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_fmea_assessments', to=settings.AUTH_USER_MODEL)),
                ('failure_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='process_fmea.failuremode')),
            ],
            options={
                'ordering': ('snapshot_number',),
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('failure_mode', 'snapshot_number'), name='process_fmea_assessment_snapshot_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='processfmea',
            index=models.Index(fields=['organization', 'fmea_code'], name='pfmea_org_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='processfmea',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('fmea_code'), models.F('organization'), name='process_fmea_org_code_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='processfmeascoringpolicy',
            constraint=models.UniqueConstraint(fields=('organization',), name='process_fmea_scoring_policy_org_uniq'),
        ),
        migrations.AddIndex(
            model_name='processfmeaversion',
            index=models.Index(fields=['fmea', 'status'], name='pfmea_ver_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='processfmeaversion',
            constraint=models.UniqueConstraint(fields=('fmea', 'version_number'), name='process_fmea_version_uniq'),
        ),
        migrations.AddIndex(
            model_name='processfmealink',
            index=models.Index(fields=['version', 'link_kind'], name='pfmea_link_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='processfmeaevent',
            index=models.Index(fields=['fmea', 'created_at'], name='pfmea_event_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='processstep',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('step_code'), models.F('version'), name='process_fmea_step_code_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='failuremode',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('mode_code'), models.F('process_step'), name='process_fmea_mode_code_ci_uniq'),
        ),
    ]
