# Generated by Django 5.2.16 on 2026-08-11 04:45

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capa', '0003_phase12_ncr_hold_capa_foundation'),
        ('checklists', '0012_phase25_device_traceability'),
        ('nonconformance', '0002_phase12_ncr_hold_capa_foundation'),
        ('organizations', '0003_phase04c_organization_configuration'),
        ('scheduling', '0007_phase07h_due_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audit_code', models.CharField(help_text='Owner-supplied audit identifier (not seeded).', max_length=64)),
                ('audit_type', models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External'), ('SUPPLIER', 'Supplier'), ('PROCESS', 'Process'), ('SYSTEM', 'System')], max_length=16)),
                ('type_code_reference', models.CharField(blank=True, default='', help_text='Optional owner-configured type catalogue code (APR-070).', max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('scope_summary', models.TextField()),
                ('site_reference', models.CharField(blank=True, default='', max_length=128)),
                ('department_reference', models.CharField(blank=True, default='', max_length=128)),
                ('process_reference', models.CharField(blank=True, default='', max_length=128)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In progress'), ('FINDINGS', 'Findings'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('checklist_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_audits', to='scheduling.checklisttask')),
                ('checklist_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_audits', to='checklists.checklisttemplate')),
                ('checklist_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_audits', to='checklists.checklistversion')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_audits_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_audits_created', to=settings.AUTH_USER_MODEL)),
                ('lead_auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_audits_led', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_audits', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Quality audit',
                'verbose_name_plural': 'Quality audits',
                'permissions': [('view_qualityaudit', 'Can view QMS quality audits'), ('plan_qualityaudit', 'Can plan QMS quality audits'), ('execute_qualityaudit', 'Can execute QMS quality audits and record findings'), ('close_qualityaudit', 'Can verify findings and close QMS quality audits'), ('link_audit_quality_case', 'Can explicitly link/create NCR/CAPA from a finding'), ('manage_auditfindingconfig', 'Can manage finding classification/severity shells')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QualityAuditChecklistBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checklist_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_audit_bindings', to='checklists.checklisttemplate')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_audit_checklist_bindings_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_audit_checklist_bindings', to='organizations.organization')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QualityAuditFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('classification_code', models.CharField(blank=True, default='', help_text='Owner-configured; not a seeded Nelna taxonomy.', max_length=64)),
                ('severity_code', models.CharField(blank=True, default='', help_text='Owner-configured; not a seeded Nelna taxonomy.', max_length=64)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACTION_COMPLETED', 'Action completed'), ('VERIFIED', 'Verified'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('action_completed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_audit_findings_actioned', to=settings.AUTH_USER_MODEL)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='quality_audits.qualityaudit')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_audit_findings_closed', to=settings.AUTH_USER_MODEL)),
                ('corrective_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_audit_findings', to='capa.correctiveaction')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_audit_findings_created', to=settings.AUTH_USER_MODEL)),
                ('nonconformance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_audit_findings', to='nonconformance.nonconformancerecord')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_audit_findings_owned', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_audit_findings_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QualityAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=512)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_audit_events', to=settings.AUTH_USER_MODEL)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='quality_audits.qualityaudit')),
                ('finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='quality_audits.qualityauditfinding')),
            ],
            options={
                'ordering': ('created_at',),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QualityAuditFindingCodeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('CLASSIFICATION', 'Classification'), ('SEVERITY', 'Severity')], max_length=16)),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_audit_finding_codes_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_audit_finding_codes', to='organizations.organization')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QualityAuditParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_reference', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='quality_audits.qualityaudit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_audit_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='qualityaudit',
            index=models.Index(fields=['organization', 'status'], name='qa_audit_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityaudit',
            index=models.Index(fields=['organization', 'site_reference'], name='qa_audit_org_site_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityaudit',
            index=models.Index(fields=['organization', 'process_reference'], name='qa_audit_org_process_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualityaudit',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('audit_code'), models.F('organization'), name='quality_audit_org_code_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='qualityauditchecklistbinding',
            constraint=models.UniqueConstraint(fields=('organization', 'checklist_template'), name='quality_audit_checklist_bind_uniq'),
        ),
        migrations.AddIndex(
            model_name='qualityauditfinding',
            index=models.Index(fields=['status', 'due_date'], name='qa_finding_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityauditfinding',
            index=models.Index(fields=['audit', 'status'], name='qa_finding_audit_status_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityauditevent',
            index=models.Index(fields=['audit', 'created_at'], name='qa_event_audit_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualityauditfindingcodeconfig',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), models.F('kind'), name='quality_audit_finding_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='qualityauditparticipant',
            constraint=models.UniqueConstraint(fields=('audit', 'user'), name='quality_audit_participant_uniq'),
        ),
    ]
