# Generated by Django 5.2.16 on 2026-08-10 02:32

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0012_phase25_device_traceability'),
        ('instruments', '0002_phase25_device_traceability'),
        ('organizations', '0003_phase04c_organization_configuration'),
        ('scheduling', '0007_phase07h_due_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('manufacturer_label', models.CharField(blank=True, default='', max_length=255)),
                ('concentration_label', models.CharField(blank=True, default='', help_text='Opaque company-approved label only — never invent ppm/% values.', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chemical_references_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chemical_references', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Chemical reference',
                'verbose_name_plural': 'Chemical references',
                'ordering': ('organization__code', 'code'),
            },
        ),
        migrations.CreateModel(
            name='SanitationFailPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_enabled', models.BooleanField(default=False, help_text='Company opt-in stub only — still gated by settings approval flag.')),
                ('procedure_reference', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sanitation_fail_policy', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanitation_fail_policies_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sanitation fail policy',
                'verbose_name_plural': 'Sanitation fail policies',
            },
        ),
        migrations.CreateModel(
            name='SanitationProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_template', models.ForeignKey(help_text='Reusable checklist engine template — not a separate sanitation form engine.', on_delete=django.db.models.deletion.PROTECT, related_name='sanitation_programs', to='checklists.checklisttemplate')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanitation_programs_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanitation_programs', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Sanitation program',
                'verbose_name_plural': 'Sanitation programs',
                'ordering': ('organization__code', 'code'),
                'permissions': [('manage_sanitationprogram', 'Can draft/edit sanitation programs'), ('publish_sanitationprogram', 'Can approve/retire sanitation program versions'), ('view_sanitation', 'Can view sanitation programs (read-only)')],
            },
        ),
        migrations.CreateModel(
            name='SanitationProgramVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('RETIRED', 'Retired')], default='DRAFT', max_length=16)),
                ('verification_mode', models.CharField(choices=[('SELF_CHECK', 'Operator self-check (submit only)'), ('SUPERVISOR', 'Self-check + Supervisor verification'), ('QA', 'Self-check + Supervisor + QA verification')], default='SELF_CHECK', help_text='Selects existing workflow layers only — not invented SSOP approval steps.', max_length=16)),
                ('change_summary', models.TextField(blank=True, default='')),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sanitation_versions_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanitation_versions_created', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='sanitation.sanitationprogram')),
            ],
            options={
                'verbose_name': 'Sanitation program version',
                'verbose_name_plural': 'Sanitation program versions',
                'ordering': ('program__code', '-version_number'),
            },
        ),
        migrations.CreateModel(
            name='SanitationHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanitation_history_actions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanitation_history_entries', to='organizations.organization')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='sanitation.sanitationprogram')),
                ('program_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='sanitation.sanitationprogramversion')),
            ],
            options={
                'verbose_name': 'Sanitation history entry',
                'verbose_name_plural': 'Sanitation history entries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SanitationChemicalReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_links', to='sanitation.chemicalreference')),
                ('program_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical_links', to='sanitation.sanitationprogramversion')),
            ],
            options={
                'verbose_name': 'Sanitation chemical link',
                'verbose_name_plural': 'Sanitation chemical links',
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateSanitationBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frozen_sanitation_context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sanitation_binding', to='checklists.checklisttemplate')),
                ('program_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_bindings', to='sanitation.sanitationprogramversion')),
            ],
            options={
                'verbose_name': 'Checklist template sanitation binding',
                'verbose_name_plural': 'Checklist template sanitation bindings',
            },
        ),
        migrations.CreateModel(
            name='SanitationScheduleLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_kind', models.CharField(choices=[('PRE_OP', 'Pre-operational'), ('POST_OP', 'Post-operational'), ('SHIFT', 'Shift-based'), ('DAILY', 'Daily'), ('PERIODIC', 'Periodic')], max_length=16)),
                ('label', models.CharField(blank=True, default='', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('checklist_schedule', models.ForeignKey(blank=True, help_text='Optional pointer to a configured recurring ChecklistSchedule (Phase 07E).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sanitation_links', to='scheduling.checklistschedule')),
                ('program_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_links', to='sanitation.sanitationprogramversion')),
            ],
            options={
                'verbose_name': 'Sanitation schedule link',
                'verbose_name_plural': 'Sanitation schedule links',
                'ordering': ('schedule_kind', 'label'),
            },
        ),
        migrations.CreateModel(
            name='SanitationScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('line_code', models.CharField(blank=True, default='', help_text='Opaque line label — Line master EVIDENCE REQUIRED.', max_length=64)),
                ('work_area_code', models.CharField(blank=True, default='', help_text='Opaque work-area label — Area master EVIDENCE REQUIRED.', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sanitation_scopes', to='organizations.department')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sanitation_scopes', to='instruments.equipment')),
                ('program_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='sanitation.sanitationprogramversion')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sanitation_scopes', to='organizations.site')),
            ],
            options={
                'verbose_name': 'Sanitation scope',
                'verbose_name_plural': 'Sanitation scopes',
                'ordering': ('code',),
            },
        ),
        migrations.AddConstraint(
            model_name='chemicalreference',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='chemical_reference_org_code_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='sanitationprogram',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='sanitation_program_org_code_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='sanitationprogramversion',
            constraint=models.UniqueConstraint(fields=('program', 'version_number'), name='sanitation_program_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='sanitationchemicalreference',
            constraint=models.UniqueConstraint(fields=('program_version', 'chemical'), name='sanitation_chem_link_uniq'),
        ),
        migrations.AddConstraint(
            model_name='sanitationscope',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('program_version'), name='sanitation_scope_version_code_ci_uniq'),
        ),
    ]
