# Generated by Django 5.2.16 on 2026-08-10 04:01

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0012_phase25_device_traceability'),
        ('haccp', '0001_phase23_haccp_foundation'),
        ('instruments', '0002_phase25_device_traceability'),
        ('master_data', '0003_phase06o_product_specifications'),
        ('nonconformance', '0002_phase12_ncr_hold_capa_foundation'),
        ('organizations', '0003_phase04c_organization_configuration'),
        ('recording', '0012_phase25_device_traceability'),
        ('sampling', '0001_phase24_sampling_engine'),
        ('scheduling', '0007_phase07h_due_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IpqcInspectionCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurrence_key', models.CharField(help_text='Idempotency key for scheduled / batch / manual generation.', max_length=255)),
                ('trigger_kind', models.CharField(choices=[('TIME_INTERVAL', 'Time interval'), ('SHIFT', 'Shift'), ('PRODUCTION_ORDER', 'Production order'), ('BATCH', 'Batch'), ('MANUAL', 'Manual')], max_length=32)),
                ('workflow_status', models.CharField(choices=[('OPEN', 'Open'), ('TASK_CREATED', 'Checklist task created'), ('IN_PROGRESS', 'In progress'), ('MEASURED', 'Measurement recorded'), ('FAILED', 'Failed (local / advisory)'), ('COMPLETED', 'Completed'), ('ESCALATED', 'Escalated to NCR/HOLD'), ('CLOSED', 'Closed')], default='OPEN', max_length=32)),
                ('production_line_code', models.CharField(blank=True, default='', max_length=64)),
                ('process_step_code', models.CharField(blank=True, default='', max_length=64)),
                ('batch_reference', models.CharField(blank=True, default='', max_length=128)),
                ('production_order_reference', models.CharField(blank=True, default='', max_length=128)),
                ('equipment_trace_snapshot', models.JSONField(blank=True, default=dict)),
                ('measurement_snapshot', models.JSONField(blank=True, default=dict)),
                ('sampling_snapshot', models.JSONField(blank=True, default=dict)),
                ('haccp_metadata_snapshot', models.JSONField(blank=True, default=dict)),
                ('failure_detected', models.BooleanField(default=False)),
                ('stop_production_signal', models.BooleanField(default=False, help_text='True only when dual-gated stop policy evaluates enabled.')),
                ('failure_decision', models.JSONField(blank=True, default=dict)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('window_start_at', models.DateTimeField(blank=True, null=True)),
                ('window_end_at', models.DateTimeField(blank=True, null=True)),
                ('frozen_process_context', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('checklist_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_inspection_cases', to='recording.checklistsubmission')),
                ('checklist_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_inspection_cases', to='scheduling.checklisttask')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_cases_created', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_inspection_cases', to='instruments.equipment')),
                ('hold_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_inspection_cases', to='nonconformance.holdcase')),
                ('nonconformance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_inspection_cases', to='nonconformance.nonconformancerecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_inspection_cases', to='organizations.organization')),
                ('process_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_inspection_cases', to='haccp.processstep')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_inspection_cases', to='master_data.fgproduct')),
                ('sampling_plan_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_inspection_cases', to='sampling.samplingplanversion')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_inspection_cases', to='organizations.shift')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IpqcHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_history_actions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_history_entries', to='organizations.organization')),
                ('inspection_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history_entries', to='ipqc.ipqcinspectioncase')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IpqcProcessCheckDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('trigger_kind', models.CharField(choices=[('TIME_INTERVAL', 'Time interval'), ('SHIFT', 'Shift'), ('PRODUCTION_ORDER', 'Production order'), ('BATCH', 'Batch'), ('MANUAL', 'Manual')], default='MANUAL', max_length=32)),
                ('interval_minutes', models.PositiveIntegerField(blank=True, help_text='Used when trigger_kind=TIME_INTERVAL. Not a company SLA invent.', null=True)),
                ('due_grace_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('production_line_code', models.CharField(blank=True, default='', max_length=64)),
                ('process_step_code', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_schedule', models.ForeignKey(blank=True, help_text='Optional Phase 07 schedule link for TIME_INTERVAL / SHIFT triggers.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_definitions', to='scheduling.checklistschedule')),
                ('checklist_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_definitions', to='checklists.checklisttemplate')),
                ('checklist_version', models.ForeignKey(blank=True, help_text='Optional pin; generation uses PUBLISHED versions only.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_definitions', to='checklists.checklistversion')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_definitions_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_process_check_definitions', to='organizations.organization')),
                ('process_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_definitions', to='haccp.processstep')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_definitions', to='master_data.fgproduct')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_definitions', to='organizations.shift')),
            ],
            options={
                'ordering': ('organization__code', 'code'),
                'permissions': [('manage_ipqc', 'Can manage IPQC definitions and generation'), ('record_ipqc', 'Can record IPQC measurements / equipment links'), ('escalate_ipqc', 'Can escalate IPQC failures to NCR/HOLD'), ('view_ipqc', 'Can view IPQC cases and dashboard'), ('manage_ipqcpolicy', 'Can update IPQC stop-line / policy stubs')],
            },
        ),
        migrations.AddField(
            model_name='ipqcinspectioncase',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_cases', to='ipqc.ipqcprocesscheckdefinition'),
        ),
        migrations.CreateModel(
            name='IpqcWorkflowPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stop_production_on_fail_enabled', models.BooleanField(default=False, help_text='Org stub only — still requires IPQC_STOP_PRODUCTION_ON_FAIL_APPROVED.')),
                ('procedure_reference', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_workflow_policy', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_policies_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IPQC workflow policy',
                'verbose_name_plural': 'IPQC workflow policies',
            },
        ),
        migrations.AddIndex(
            model_name='ipqcprocesscheckdefinition',
            index=models.Index(fields=['organization', 'trigger_kind', 'is_active'], name='ipqc_ipqcpr_organiz_d208a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='ipqcprocesscheckdefinition',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='ipqc_definition_org_code_ci_uniq'),
        ),
        migrations.AddIndex(
            model_name='ipqcinspectioncase',
            index=models.Index(fields=['organization', 'workflow_status'], name='ipqc_ipqcin_organiz_b8d2a6_idx'),
        ),
        migrations.AddIndex(
            model_name='ipqcinspectioncase',
            index=models.Index(fields=['organization', 'due_at'], name='ipqc_ipqcin_organiz_4aa1f9_idx'),
        ),
        migrations.AddIndex(
            model_name='ipqcinspectioncase',
            index=models.Index(fields=['organization', 'failure_detected'], name='ipqc_ipqcin_organiz_e3959e_idx'),
        ),
        migrations.AddIndex(
            model_name='ipqcinspectioncase',
            index=models.Index(fields=['organization', 'production_line_code'], name='ipqc_ipqcin_organiz_9008f1_idx'),
        ),
        migrations.AddIndex(
            model_name='ipqcinspectioncase',
            index=models.Index(fields=['organization', 'batch_reference'], name='ipqc_ipqcin_organiz_7f0204_idx'),
        ),
        migrations.AddConstraint(
            model_name='ipqcinspectioncase',
            constraint=models.UniqueConstraint(fields=('organization', 'occurrence_key'), name='ipqc_case_org_occurrence_uniq'),
        ),
    ]
