# Generated by Django 5.2.16 on 2026-08-08 06:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_phase04a_shift_foundation'),
        ('recording', '0003_phase09b_checklist_correction'),
        ('reviews', '0001_phase09a_supervisor_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QAReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('RELEASE', 'Release (provisional QA disposition)'), ('HOLD', 'Hold (provisional QA disposition)'), ('REJECT', 'Reject (provisional QA disposition)')], max_length=16)),
                ('review_note', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('checklist_submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='qa_review', to='recording.checklistsubmission')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qa_reviews', to='organizations.organization')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qa_reviews', to=settings.AUTH_USER_MODEL)),
                ('supervisor_review', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='qa_review', to='reviews.supervisorreview')),
            ],
            options={
                'verbose_name': 'QA review',
                'verbose_name_plural': 'QA reviews',
                'ordering': ('-reviewed_at',),
                'permissions': [('qa_review_checklistsubmission', 'Can record QA final review disposition for checklist submissions')],
                'indexes': [models.Index(fields=['organization', 'reviewed_at'], name='qa_review_org_reviewed_idx'), models.Index(fields=['organization', 'decision'], name='qa_review_org_decision_idx')],
            },
        ),
    ]
