# Generated by Django 5.2.16 on 2026-08-11 05:06

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capa', '0003_phase12_ncr_hold_capa_foundation'),
        ('change_control', '0001_phase44_change_control'),
        ('nonconformance', '0002_phase12_ncr_hold_capa_foundation'),
        ('organizations', '0003_phase04c_organization_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceControlMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clause_reference', models.CharField(help_text='Owner-supplied clause/requirement ID. Do not invent standard text.', max_length=128)),
                ('requirement_summary', models.TextField(blank=True, default='', help_text='Owner-supplied summary only. Do not paste proprietary standard text.')),
                ('system_control_kind', models.CharField(choices=[('CHECKLIST_DEFINITION', 'Checklist definition'), ('HACCP_CONTROL', 'HACCP control'), ('TRAINING_RECORD', 'Training record'), ('CALIBRATION', 'Calibration'), ('LABORATORY', 'Laboratory'), ('NCR', 'Nonconformance'), ('CAPA', 'CAPA'), ('QUALITY_AUDIT', 'QMS audit record'), ('DOCUMENT_VERSION', 'Controlled document version'), ('SECURITY_CONTROL', 'System security control'), ('BACKUP_DR', 'Backup / DR evidence'), ('OTHER', 'Other owner-cited control')], max_length=32)),
                ('system_control_reference', models.CharField(max_length=255)),
                ('owner_reference', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('NOT_ASSESSED', 'Not assessed'), ('APPLICABILITY_PENDING', 'Applicability pending'), ('APPLICABLE', 'Applicable'), ('NOT_APPLICABLE', 'Not applicable'), ('CONTROL_DESIGNED', 'Control designed'), ('IMPLEMENTED', 'Implemented'), ('VERIFIED', 'Verified'), ('GAP_IDENTIFIED', 'Gap identified')], default='NOT_ASSESSED', max_length=24)),
                ('gap_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_mappings_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_control_mappings', to='organizations.organization')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ComplianceGap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ADDRESSED', 'Addressed'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_gaps_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_gaps_created', to=settings.AUTH_USER_MODEL)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gaps', to='compliance_mapping.compliancecontrolmapping')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ComplianceGapAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_kind', models.CharField(choices=[('RISK', 'Risk register reference'), ('CHANGE_REQUEST', 'Quality change request'), ('NCR', 'Nonconformance'), ('CAPA', 'CAPA'), ('ACTION', 'Generic follow-up action')], max_length=16)),
                ('risk_reference', models.CharField(blank=True, default='', help_text='Owner-supplied risk ID (e.g. governance register). Not a certification claim.', max_length=64)),
                ('action_summary', models.CharField(max_length=512)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_gap_actions', to='change_control.qualitychangerequest')),
                ('corrective_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_gap_actions', to='capa.correctiveaction')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_gap_actions_created', to=settings.AUTH_USER_MODEL)),
                ('gap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='compliance_mapping.compliancegap')),
                ('nonconformance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_gap_actions', to='nonconformance.nonconformancerecord')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_gap_actions_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ComplianceSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_code', models.CharField(help_text='Owner-supplied source identifier (not seeded).', max_length=64)),
                ('kind', models.CharField(choices=[('COMPANY_POLICY', 'Company policy'), ('HACCP_PLAN', 'Approved HACCP plan'), ('CUSTOMER_REQUIREMENT', 'Customer requirement'), ('LEGAL_REGULATORY', 'Legal / regulatory requirement'), ('CERTIFICATION_SCHEME', 'Certification-scheme requirement'), ('OTHER', 'Other owner-cited source')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('business_owner_reference', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_sources_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_sources', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Compliance source',
                'verbose_name_plural': 'Compliance sources',
                'permissions': [('view_compliancemapping', 'Can view compliance sources and control mappings'), ('manage_compliancesource', 'Can register and revise compliance sources'), ('manage_compliancecontrol', 'Can create and update control mappings'), ('verify_compliancecontrol', 'Can record verification of implemented controls'), ('link_compliance_gap_action', 'Can explicitly link gap follow-up actions')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ComplianceSourceEdition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_edition', models.CharField(max_length=128)),
                ('official_source_citation', models.CharField(blank=True, default='', help_text='Exact official publisher/version citation. Do not store copyrighted text.', max_length=512)),
                ('applicability_status', models.CharField(choices=[('NOT_ASSESSED', 'Not assessed'), ('APPLICABILITY_PENDING', 'Applicability pending'), ('APPLICABLE', 'Applicable'), ('NOT_APPLICABLE', 'Not applicable')], default='NOT_ASSESSED', max_length=24)),
                ('evidence_reference', models.CharField(blank=True, default='', max_length=255)),
                ('last_reviewed_on', models.DateField(blank=True, null=True)),
                ('register_status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('WITHDRAWN', 'Withdrawn')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_source_editions_created', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editions', to='compliance_mapping.compliancesource')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ComplianceMappingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=512)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_mapping_events', to=settings.AUTH_USER_MODEL)),
                ('gap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='compliance_mapping.compliancegap')),
                ('mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='compliance_mapping.compliancecontrolmapping')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_mapping_events', to='organizations.organization')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='compliance_mapping.compliancesource')),
                ('edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='compliance_mapping.compliancesourceedition')),
            ],
            options={
                'ordering': ('created_at',),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='compliancecontrolmapping',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mappings', to='compliance_mapping.compliancesourceedition'),
        ),
        migrations.CreateModel(
            name='ComplianceEvidenceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_kind', models.CharField(choices=[('CHECKLIST_DEFINITION', 'Checklist definition'), ('HACCP_CONTROL', 'HACCP control'), ('TRAINING_RECORD', 'Training record'), ('CALIBRATION', 'Calibration'), ('LABORATORY', 'Laboratory'), ('NCR', 'Nonconformance'), ('CAPA', 'CAPA'), ('QUALITY_AUDIT', 'QMS audit record'), ('DOCUMENT_VERSION', 'Controlled document version'), ('SECURITY_CONTROL', 'System security control'), ('BACKUP_DR', 'Backup / DR evidence'), ('OTHER', 'Other owner-cited control')], max_length=32)),
                ('linked_object_id', models.UUIDField(blank=True, null=True)),
                ('citation', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_evidence_links_created', to=settings.AUTH_USER_MODEL)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_links', to='compliance_mapping.compliancecontrolmapping')),
            ],
            options={
                'default_permissions': (),
                'indexes': [models.Index(fields=['mapping', 'evidence_kind'], name='cm_evi_map_kind_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='compliancegap',
            index=models.Index(fields=['mapping', 'status'], name='cm_gap_map_status_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancesource',
            index=models.Index(fields=['organization', 'kind'], name='cm_source_org_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='compliancesource',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('source_code'), models.F('organization'), name='compliance_source_org_code_ci_uniq'),
        ),
        migrations.AddIndex(
            model_name='compliancesourceedition',
            index=models.Index(fields=['source', 'register_status'], name='cm_edition_source_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='compliancesourceedition',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('version_edition'), models.F('source'), name='compliance_source_edition_uniq'),
        ),
        migrations.AddIndex(
            model_name='compliancemappingevent',
            index=models.Index(fields=['organization', 'created_at'], name='cm_event_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancemappingevent',
            index=models.Index(fields=['source', 'created_at'], name='cm_event_source_created_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancecontrolmapping',
            index=models.Index(fields=['organization', 'status'], name='cm_mapping_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancecontrolmapping',
            index=models.Index(fields=['edition', 'status'], name='cm_mapping_edition_status_idx'),
        ),
    ]
