# Generated by Django 5.2.16 on 2026-08-10 04:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_phase04c_organization_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchDossierPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_export_enabled', models.BooleanField(default=False, help_text='Org stub only — still requires BATCH_DOSSIER_PDF_EXPORT_APPROVED.')),
                ('procedure_reference', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='batch_dossier_policy', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_dossier_policies_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Batch dossier policy',
                'verbose_name_plural': 'Batch dossier policies',
                'permissions': [('view_batchdossier', 'Can view electronic batch quality dossier'), ('export_batchdossier', 'Can prepare batch dossier PDF export hook'), ('manage_batchdossierpolicy', 'Can update batch dossier policy stubs')],
            },
        ),
        migrations.CreateModel(
            name='BatchDossierExportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_reference', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('PREPARED', 'Prepared (hook only)'), ('BLOCKED', 'Blocked by dual-gate'), ('FAILED', 'Failed')], default='BLOCKED', max_length=16)),
                ('reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('procedure_reference', models.CharField(blank=True, default='', max_length=255)),
                ('dossier_fingerprint', models.CharField(blank=True, default='', help_text='Opaque hash of assembled reference ids at prepare time.', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_dossier_export_requests', to='organizations.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_dossier_exports_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'batch_reference'], name='batch_dossi_organiz_1fcf6c_idx'), models.Index(fields=['organization', 'status'], name='batch_dossi_organiz_9174c8_idx')],
            },
        ),
    ]
