# Generated by Django 5.2.16 on 2026-08-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_phase07a_batch_checklist_task_foundation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklisttask',
            options={'ordering': ('-created_at',), 'permissions': [('manage_checklisttask', 'Can manage checklist tasks'), ('record_checklisttask', 'Can record checklist task responses (Phase 08 capability foundation)')], 'verbose_name': 'Checklist task', 'verbose_name_plural': 'Checklist tasks'},
        ),
    ]
