# Generated by Django 5.2.16 on 2026-08-09 22:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0010_phase06o_product_specifications'),
        ('master_data', '0003_phase06o_product_specifications'),
        ('organizations', '0003_phase04c_organization_configuration'),
        ('scheduling', '0002_phase07b_record_checklisttask_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistApplicabilityRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('process_reference', models.CharField(blank=True, default='', help_text='Optional free-text process/stage label only — not a Process master. Process master remains DECISION REQUIRED / EVIDENCE REQUIRED.', max_length=128)),
                ('effective_from', models.DateField(blank=True, help_text='Optional effective-from. Blank = unbounded start.', null=True)),
                ('effective_to', models.DateField(blank=True, help_text='Optional effective-to. Blank = unbounded end.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicability_rules', to='checklists.checklisttemplate')),
                ('checklist_version', models.ForeignKey(help_text='Exact PUBLISHED version pin — never auto-select latest.', on_delete=django.db.models.deletion.PROTECT, related_name='applicability_rules', to='checklists.checklistversion')),
                ('department', models.ForeignKey(blank=True, help_text='Optional Department constraint. Null = any department (wildcard).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_applicability_rules', to='organizations.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_applicability_rules', to='organizations.organization')),
                ('product', models.ForeignKey(blank=True, help_text='Optional FG Product constraint. Null = any product (wildcard).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_applicability_rules', to='master_data.fgproduct')),
                ('shift', models.ForeignKey(blank=True, help_text='Optional Shift constraint. Null = any shift (wildcard).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_applicability_rules', to='organizations.shift')),
                ('site', models.ForeignKey(blank=True, help_text='Optional Site constraint. Null = any site (wildcard).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_applicability_rules', to='organizations.site')),
            ],
            options={
                'verbose_name': 'Checklist applicability rule',
                'verbose_name_plural': 'Checklist applicability rules',
                'ordering': ('organization__code', 'checklist_template__code', 'created_at'),
                'permissions': [('manage_checklistapplicability', 'Can manage checklist applicability rules'), ('view_checklistapplicability', 'Can view and preview checklist applicability')],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='sched_appl_org_act_idx'), models.Index(fields=['organization', 'product', 'is_active'], name='sched_appl_org_prod_act_idx'), models.Index(fields=['organization', 'site', 'is_active'], name='sched_appl_org_site_act_idx'), models.Index(fields=['organization', 'department', 'is_active'], name='sched_appl_org_dept_act_idx'), models.Index(fields=['organization', 'shift', 'is_active'], name='sched_appl_org_shift_act_idx'), models.Index(fields=['organization', 'effective_from', 'effective_to'], name='sched_appl_org_effect_idx'), models.Index(fields=['checklist_template', 'is_active'], name='sched_appl_tmpl_act_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'code'), name='sched_appl_org_code_uniq'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='sched_applicability_effective_window_valid')],
            },
        ),
    ]
