# Generated by Django 5.2.16 on 2026-08-09 23:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0004_phase03c_roletemplate_deliverable'),
        ('checklists', '0011_phase07d_effective_version'),
        ('organizations', '0003_phase04c_organization_configuration'),
        ('scheduling', '0005_phase07f_batch_event_generation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTaskAssignmentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ASSIGN', 'Assign'), ('REASSIGN', 'Reassign'), ('UNASSIGN', 'Unassign')], max_length=16)),
                ('assignee_kind', models.CharField(blank=True, default='', help_text='Post-change kind; blank when UNASSIGN.', max_length=16)),
                ('assigned_team_code', models.CharField(blank=True, default='', max_length=64)),
                ('previous_assignee_kind', models.CharField(blank=True, default='', max_length=16)),
                ('previous_assigned_team_code', models.CharField(blank=True, default='', max_length=64)),
                ('assigned_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Checklist task assignment event',
                'verbose_name_plural': 'Checklist task assignment events',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AlterModelOptions(
            name='checklisttask',
            options={'ordering': ('-created_at',), 'permissions': [('manage_checklisttask', 'Can manage checklist tasks'), ('record_checklisttask', 'Can record checklist task responses (Phase 08 capability foundation)'), ('assign_checklisttask', 'Can assign / reassign / unassign checklist tasks (ownership only)')], 'verbose_name': 'Checklist task', 'verbose_name_plural': 'Checklist tasks'},
        ),
        migrations.AddField(
            model_name='checklisttask',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklisttask',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_task_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklisttask',
            name='assigned_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_checklist_tasks', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='checklisttask',
            name='assigned_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_checklist_tasks', to='access_control.role'),
        ),
        migrations.AddField(
            model_name='checklisttask',
            name='assigned_shift',
            field=models.ForeignKey(blank=True, help_text='Ownership assignee Shift (distinct from generation trigger shift when both set).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_checklist_tasks_ownership', to='organizations.shift'),
        ),
        migrations.AddField(
            model_name='checklisttask',
            name='assigned_team_code',
            field=models.CharField(blank=True, default='', help_text='Opaque team label only — Team master is EVIDENCE REQUIRED / not modeled.', max_length=64),
        ),
        migrations.AddField(
            model_name='checklisttask',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_checklist_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklisttask',
            name='assignee_kind',
            field=models.CharField(blank=True, default='', help_text='Empty = unassigned. USER/ROLE/SHIFT/DEPARTMENT/TEAM ownership metadata only — never grants RBAC.', max_length=16),
        ),
        migrations.AddField(
            model_name='checklisttask',
            name='assignment_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='checklisttask',
            index=models.Index(fields=['organization', 'assignee_kind'], name='sched_task_org_assignee_idx'),
        ),
        migrations.AddIndex(
            model_name='checklisttask',
            index=models.Index(fields=['assigned_user', 'status'], name='sched_task_assignee_user_idx'),
        ),
        migrations.AddField(
            model_name='checklisttaskassignmentevent',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_task_assignment_events_acted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklisttaskassignmentevent',
            name='assigned_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_task_assignment_events', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='checklisttaskassignmentevent',
            name='assigned_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_task_assignment_events', to='access_control.role'),
        ),
        migrations.AddField(
            model_name='checklisttaskassignmentevent',
            name='assigned_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_task_assignment_events', to='organizations.shift'),
        ),
        migrations.AddField(
            model_name='checklisttaskassignmentevent',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_task_assignment_events_as_assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklisttaskassignmentevent',
            name='checklist_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_events', to='scheduling.checklisttask'),
        ),
        migrations.AddField(
            model_name='checklisttaskassignmentevent',
            name='previous_assigned_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_task_assignment_events_previous_dept', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='checklisttaskassignmentevent',
            name='previous_assigned_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_task_assignment_events_previous_role', to='access_control.role'),
        ),
        migrations.AddField(
            model_name='checklisttaskassignmentevent',
            name='previous_assigned_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_task_assignment_events_previous_shift', to='organizations.shift'),
        ),
        migrations.AddField(
            model_name='checklisttaskassignmentevent',
            name='previous_assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_task_assignment_events_as_previous', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='checklisttaskassignmentevent',
            index=models.Index(fields=['checklist_task', 'assigned_at'], name='sched_assign_evt_task_at_idx'),
        ),
        migrations.AddIndex(
            model_name='checklisttaskassignmentevent',
            index=models.Index(fields=['action', 'assigned_at'], name='sched_assign_evt_action_idx'),
        ),
    ]
