# Generated by Django 5.2.16 on 2026-08-10 04:55

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_phase04c_organization_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecallCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Opaque case ID / reference.', max_length=64)),
                ('case_type_reference', models.CharField(blank=True, default='', help_text='Opaque type/procedure reference — not a regulatory class invent.', max_length=128)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('RECONCILING', 'Quantity reconciliation'), ('PENDING_CLOSURE', 'Pending closure'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=32)),
                ('scope_notes', models.TextField(blank=True, default='', help_text='Free-text scope description — company SOPs EVIDENCE REQUIRED.')),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recall_cases_closed', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recall_cases_initiated', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recall_cases', to='organizations.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recall_cases_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recall case',
                'verbose_name_plural': 'Recall cases',
                'permissions': [('view_recall', 'Can view recall/withdrawal cases'), ('initiate_recall', 'Can initiate recall/withdrawal cases (high-risk; not System Admin by default)'), ('manage_recallcase', 'Can update recall case scope and quantities'), ('close_recall', 'Can close recall/withdrawal cases'), ('manage_recallpolicy', 'Can manage recall policy stubs')],
            },
        ),
        migrations.CreateModel(
            name='RecallAffectedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_reference', models.CharField(max_length=128)),
                ('notes', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recall_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affected_products', to='recall.recallcase')),
            ],
        ),
        migrations.CreateModel(
            name='RecallAffectedBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_reference', models.CharField(max_length=128)),
                ('genealogy_node_id', models.UUIDField(blank=True, help_text='Optional Phase 36 GenealogyNode id — reference only.', null=True)),
                ('genealogy_node_kind', models.CharField(blank=True, default='', max_length=32)),
                ('selected_via', models.CharField(blank=True, default='MANUAL', help_text='MANUAL | GENEALOGY_EXPANSION — how the batch entered the case.', max_length=64)),
                ('notes', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recall_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affected_batches', to='recall.recallcase')),
            ],
        ),
        migrations.CreateModel(
            name='RecallCommunicationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=128)),
                ('channel_reference', models.CharField(blank=True, default='', help_text='Opaque channel/procedure reference — not an auto-send.', max_length=128)),
                ('audience_reference', models.CharField(blank=True, default='', help_text='Opaque audience label — no customer PII invent.', max_length=128)),
                ('evidence_attachment_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recall_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communications', to='recall.recallcase')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recall_communications_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='RecallPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_notification_enabled', models.BooleanField(default=False, help_text='Org stub only — still requires RECALL_EXTERNAL_NOTIFICATION_APPROVED.')),
                ('erp_distribution_pull_enabled', models.BooleanField(default=False, help_text='Org stub only — still requires RECALL_ERP_DISTRIBUTION_PULL_APPROVED.')),
                ('procedure_reference', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recall_policy', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recall_policies_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recall policy',
                'verbose_name_plural': 'Recall policies',
            },
        ),
        migrations.CreateModel(
            name='RecallQuantityLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('produced_reference', models.CharField(blank=True, default='', max_length=128)),
                ('distributed_reference', models.CharField(blank=True, default='', max_length=128)),
                ('remaining_reference', models.CharField(blank=True, default='', max_length=128)),
                ('recovered_reference', models.CharField(blank=True, default='', max_length=128)),
                ('disposed_reference', models.CharField(blank=True, default='', max_length=128)),
                ('reworked_reference', models.CharField(blank=True, default='', max_length=128)),
                ('uom_reference', models.CharField(blank=True, default='', max_length=64)),
                ('erp_source_system', models.CharField(blank=True, default='', max_length=64)),
                ('erp_source_event_id', models.CharField(blank=True, default='', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quantity_lines', to='recall.recallaffectedbatch')),
                ('recall_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quantity_lines', to='recall.recallcase')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recall_quantity_lines_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecallTimelineEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=512)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recall_timeline_entries', to=settings.AUTH_USER_MODEL)),
                ('recall_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeline_entries', to='recall.recallcase')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='recallcase',
            index=models.Index(fields=['organization', 'status'], name='recall_reca_organiz_0565ea_idx'),
        ),
        migrations.AddIndex(
            model_name='recallcase',
            index=models.Index(fields=['organization', 'code'], name='recall_reca_organiz_ff87cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='recallcase',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='recall_case_org_code_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='recallaffectedproduct',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('product_reference'), models.F('recall_case'), name='recall_product_case_ref_ci_uniq'),
        ),
        migrations.AddIndex(
            model_name='recallaffectedbatch',
            index=models.Index(fields=['recall_case', 'batch_reference'], name='recall_reca_recall__b9b3e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='recallaffectedbatch',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('batch_reference'), models.F('recall_case'), name='recall_batch_case_ref_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='recallquantityline',
            constraint=models.UniqueConstraint(fields=('recall_case', 'affected_batch'), name='recall_qty_case_batch_uniq'),
        ),
        migrations.AddIndex(
            model_name='recalltimelineentry',
            index=models.Index(fields=['recall_case', 'created_at'], name='recall_reca_recall__f72a0f_idx'),
        ),
    ]
