# Generated by Django 5.2.16 on 2026-08-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_audit', '0005_phase07a_batch_checklist_task_foundation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityauditevent',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILURE', 'Login failure'), ('ACCOUNT_LOCKED', 'Account locked'), ('ACCOUNT_UNLOCKED', 'Account unlocked'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Password changed'), ('PASSWORD_RESET_BY_ADMIN', 'Password reset by admin'), ('USER_ACTIVATED', 'User activated'), ('USER_DEACTIVATED', 'User deactivated'), ('ROLE_ASSIGNED', 'Role assigned'), ('ROLE_REVOKED', 'Role revoked'), ('SHIFT_CREATED', 'Shift created'), ('SHIFT_UPDATED', 'Shift updated'), ('SHIFT_ACTIVATED', 'Shift activated'), ('SHIFT_DEACTIVATED', 'Shift deactivated'), ('FG_PRODUCT_CREATED', 'FG Product created'), ('FG_PRODUCT_UPDATED', 'FG Product updated'), ('FG_PRODUCT_ACTIVATED', 'FG Product activated'), ('FG_PRODUCT_DEACTIVATED', 'FG Product deactivated'), ('CHECKLIST_TEMPLATE_CREATED', 'Checklist template created'), ('CHECKLIST_TEMPLATE_UPDATED', 'Checklist template updated'), ('CHECKLIST_TEMPLATE_ACTIVATED', 'Checklist template activated'), ('CHECKLIST_TEMPLATE_DEACTIVATED', 'Checklist template deactivated'), ('CHECKLIST_VERSION_CREATED', 'Checklist version created'), ('CHECKLIST_VERSION_CLONED', 'Checklist version cloned'), ('CHECKLIST_VERSION_PUBLISHED', 'Checklist version published'), ('CHECKLIST_VERSION_RETIRED', 'Checklist version retired'), ('CHECKLIST_TASK_CREATED', 'Checklist task created'), ('CHECKLIST_TASK_CANCELLED', 'Checklist task cancelled'), ('CHECKLIST_RECORD_STARTED', 'Checklist record started'), ('CHECKLIST_RECORD_DRAFT_SAVED', 'Checklist record draft saved')], max_length=64),
        ),
    ]
