# Generated by Django 5.2.16 on 2026-08-10 02:49

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0002_phase25_device_traceability'),
        ('laboratory', '0001_phase22_laboratory_foundation'),
        ('nonconformance', '0002_phase12_ncr_hold_capa_foundation'),
        ('organizations', '0003_phase04c_organization_configuration'),
        ('scheduling', '0007_phase07h_due_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalExcursionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_hold_enabled', models.BooleanField(default=False)),
                ('procedure_reference', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_excursion_policy', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environmental_excursion_policies_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Environmental excursion policy',
                'verbose_name_plural': 'Environmental excursion policies',
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environmental_history_actions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='environmental_history_entries', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Environmental history entry',
                'verbose_name_plural': 'Environmental history entries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MonitoringParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('category', models.CharField(blank=True, choices=[('TEMPERATURE', 'Temperature'), ('HUMIDITY', 'Humidity'), ('WATER', 'Water test'), ('SWAB', 'Surface / environment swab'), ('OTHER', 'Other approved measurement')], default='', help_text='Optional family label only — blank until company catalogue exists.', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_parameters_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_parameters', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Monitoring parameter',
                'verbose_name_plural': 'Monitoring parameters',
                'ordering': ('organization__code', 'code'),
            },
        ),
        migrations.CreateModel(
            name='MonitoringPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('room_code', models.CharField(blank=True, default='', help_text='Opaque room label — Room master EVIDENCE REQUIRED.', max_length=64)),
                ('line_code', models.CharField(blank=True, default='', help_text='Opaque line label — Line master EVIDENCE REQUIRED.', max_length=64)),
                ('work_area_code', models.CharField(blank=True, default='', help_text='Opaque work-area label — Area master EVIDENCE REQUIRED.', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_points_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_points', to='organizations.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_points', to='organizations.organization')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_points', to='organizations.site')),
            ],
            options={
                'verbose_name': 'Monitoring point',
                'verbose_name_plural': 'Monitoring points',
                'ordering': ('organization__code', 'code'),
                'permissions': [('manage_environmental', 'Can manage environmental monitoring configuration'), ('record_environmentalreading', 'Can record environmental monitoring readings'), ('view_environmental', 'Can view environmental monitoring (read-only)')],
            },
        ),
        migrations.CreateModel(
            name='MonitoringLimitRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bound_min', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('bound_max', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('warn_min', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('warn_max', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='limit_rules', to='environmental.monitoringparameter')),
                ('monitoring_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='limit_rules', to='environmental.monitoringpoint')),
            ],
            options={
                'verbose_name': 'Monitoring limit rule',
                'verbose_name_plural': 'Monitoring limit rules',
                'ordering': ('parameter__code', 'monitoring_point__code'),
            },
        ),
        migrations.CreateModel(
            name='MonitoringReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('MANUAL', 'Manual entry'), ('LAB', 'Laboratory result link'), ('SENSOR', 'Sensor / IoT placeholder')], max_length=16)),
                ('numeric_value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('recorded_at', models.DateTimeField()),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('sensor_reference', models.CharField(blank=True, default='', help_text='Opaque sensor/device id placeholder — IoT not required.', max_length=128)),
                ('device_trace_context', models.JSONField(blank=True, default=dict, help_text='Frozen equipment identity at reading time when equipment linked.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(blank=True, help_text='Optional measuring device for MANUAL/SENSOR traceability.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='environmental_readings', to='instruments.equipment')),
                ('lab_result', models.ForeignKey(blank=True, help_text='Optional laboratory result provenance for LAB source.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='environmental_readings', to='laboratory.labresult')),
                ('monitoring_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='environmental.monitoringpoint')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_readings', to='organizations.organization')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='environmental.monitoringparameter')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_readings_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monitoring reading',
                'verbose_name_plural': 'Monitoring readings',
                'ordering': ('-recorded_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='MonitoringExcursion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('IN_RANGE', 'In range'), ('WARN', 'Warning band'), ('EXCURSION', 'Excursion (outside configured limits)'), ('NOT_EVALUATED', 'Not evaluated (limits pending)')], max_length=16)),
                ('frozen_limit_context', models.JSONField(blank=True, default=dict)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('hold_recommended', models.BooleanField(default=False)),
                ('auto_hold_created', models.BooleanField(default=False, help_text='True only when dual-gate policy actually created a HoldCase.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hold_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environmental_excursions', to='nonconformance.holdcase')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_excursions', to='organizations.organization')),
                ('limit_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='excursions', to='environmental.monitoringlimitrule')),
                ('reading', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='excursion', to='environmental.monitoringreading')),
            ],
            options={
                'verbose_name': 'Monitoring excursion',
                'verbose_name_plural': 'Monitoring excursions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MonitoringScheduleLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('checklist_schedule', models.ForeignKey(help_text='Recurring readings use the existing scheduler — frequencies EVIDENCE REQUIRED.', on_delete=django.db.models.deletion.PROTECT, related_name='environmental_links', to='scheduling.checklistschedule')),
                ('monitoring_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_links', to='environmental.monitoringpoint')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_schedule_links', to='organizations.organization')),
                ('parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_links', to='environmental.monitoringparameter')),
            ],
            options={
                'verbose_name': 'Monitoring schedule link',
                'verbose_name_plural': 'Monitoring schedule links',
                'ordering': ('monitoring_point__code', 'label'),
            },
        ),
        migrations.CreateModel(
            name='MonitoringSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_specs_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_specs', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Monitoring specification',
                'verbose_name_plural': 'Monitoring specifications',
                'ordering': ('organization__code', 'code'),
            },
        ),
        migrations.CreateModel(
            name='MonitoringSpecVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('RETIRED', 'Retired')], default='DRAFT', max_length=16)),
                ('change_summary', models.TextField(blank=True, default='')),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_spec_versions_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_spec_versions_created', to=settings.AUTH_USER_MODEL)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='environmental.monitoringspec')),
            ],
            options={
                'verbose_name': 'Monitoring specification version',
                'verbose_name_plural': 'Monitoring specification versions',
                'ordering': ('spec__code', '-version_number'),
            },
        ),
        migrations.AddField(
            model_name='monitoringreading',
            name='spec_version',
            field=models.ForeignKey(blank=True, help_text='Approved spec version used for evaluation (historical identity).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='environmental.monitoringspecversion'),
        ),
        migrations.AddField(
            model_name='monitoringlimitrule',
            name='spec_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit_rules', to='environmental.monitoringspecversion'),
        ),
        migrations.CreateModel(
            name='MonitoringTrendIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('MANUAL', 'Manual entry'), ('LAB', 'Laboratory result link'), ('SENSOR', 'Sensor / IoT placeholder')], max_length=16)),
                ('numeric_value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('recorded_at', models.DateTimeField()),
                ('evaluation_outcome', models.CharField(blank=True, choices=[('IN_RANGE', 'In range'), ('WARN', 'Warning band'), ('EXCURSION', 'Excursion (outside configured limits)'), ('NOT_EVALUATED', 'Not evaluated (limits pending)')], default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monitoring_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trend_indexes', to='environmental.monitoringpoint')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_trend_indexes', to='organizations.organization')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trend_indexes', to='environmental.monitoringparameter')),
                ('reading', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trend_index', to='environmental.monitoringreading')),
            ],
            options={
                'verbose_name': 'Monitoring trend index',
                'verbose_name_plural': 'Monitoring trend indexes',
                'ordering': ('-recorded_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='monitoringparameter',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='em_monitoring_parameter_org_code_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='monitoringpoint',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='em_monitoring_point_org_code_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='monitoringspec',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='em_monitoring_spec_org_code_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='monitoringspecversion',
            constraint=models.UniqueConstraint(fields=('spec', 'version_number'), name='em_monitoring_spec_version_uniq'),
        ),
        migrations.AddIndex(
            model_name='monitoringreading',
            index=models.Index(fields=['organization', 'monitoring_point', 'parameter', '-recorded_at'], name='em_reading_trend_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringreading',
            index=models.Index(fields=['organization', 'parameter', '-recorded_at'], name='em_reading_param_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='monitoringlimitrule',
            constraint=models.UniqueConstraint(fields=('spec_version', 'monitoring_point', 'parameter'), name='em_limit_rule_version_point_param_uniq'),
        ),
        migrations.AddIndex(
            model_name='monitoringtrendindex',
            index=models.Index(fields=['organization', 'parameter', '-recorded_at'], name='em_trend_param_time_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringtrendindex',
            index=models.Index(fields=['organization', 'monitoring_point', '-recorded_at'], name='em_trend_point_time_idx'),
        ),
    ]
