# Generated by Django 5.2.16 on 2026-08-08 05:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_phase04a_shift_foundation'),
        ('recording', '0002_phase08b_checklist_submission_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Correction draft'), ('RESUBMITTED', 'Resubmitted')], default='DRAFT', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='recording.checklistrecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_corrections', to='organizations.organization')),
                ('resulting_submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produced_by_correction', to='recording.checklistsubmission')),
                ('source_submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='correction_cycle', to='recording.checklistsubmission')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='started_checklist_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checklist correction',
                'verbose_name_plural': 'Checklist corrections',
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['organization', 'status'], name='rec_corr_org_status_idx'), models.Index(fields=['checklist_record', 'status'], name='rec_corr_record_status_idx')],
            },
        ),
    ]
