# Generated by Django 5.2.16 on 2026-08-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0008_phase06l_control_point_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistresponse',
            name='measurement_context',
            field=models.JSONField(blank=True, default=None, help_text='Server-authored NUMBER measurement semantics snapshot (Phase 06M).', null=True),
        ),
        migrations.AddField(
            model_name='checklistsubmissionresponse',
            name='measurement_context',
            field=models.JSONField(blank=True, default=None, help_text='Frozen NUMBER measurement semantics at submit time. Historical truth — do not recompute with future definition rules.', null=True),
        ),
    ]
