# Generated by Django 5.2.16 on 2026-08-09 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_phase05d_equipment_calibration'),
        ('recording', '0010_phase06m_measurement_semantics'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistrecord',
            name='draft_version',
            field=models.PositiveIntegerField(default=1, help_text='Optimistic concurrency token for DRAFT saves. Clients must send the expected version; mismatched saves are rejected (no silent last-write-wins).'),
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='equipment',
            field=models.ForeignKey(blank=True, help_text='Optional equipment reference when the item requires it. Calibration overdue block/warn remains EVIDENCE REQUIRED — not enforced here.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_draft_responses', to='instruments.equipment'),
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='evidence_hook',
            field=models.JSONField(blank=True, default=None, help_text='Future evidence/attachment hook metadata only (Phase 11). Never stores file bytes — object storage later.', null=True),
        ),
        migrations.AddField(
            model_name='checklistsubmissionresponse',
            name='equipment',
            field=models.ForeignKey(blank=True, help_text='Frozen optional equipment reference at submit time.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_submission_responses', to='instruments.equipment'),
        ),
        migrations.AddField(
            model_name='checklistsubmissionresponse',
            name='evidence_hook',
            field=models.JSONField(blank=True, default=None, help_text='Frozen evidence/attachment hook metadata (no file bytes).', null=True),
        ),
    ]
