# Generated by Django 5.2.16 on 2026-08-10 03:22

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0012_phase25_device_traceability'),
        ('master_data', '0003_phase06o_product_specifications'),
        ('organizations', '0003_phase04c_organization_configuration'),
        ('packaging', '0001_phase29_packaging_artwork'),
        ('recording', '0012_phase25_device_traceability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergenReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Company-assigned allergen code — not invented by the system.', max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allergen_references_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allergen_references', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Allergen reference',
                'verbose_name_plural': 'Allergen references',
                'ordering': ('organization__code', 'code'),
                'permissions': [('manage_allergenreference', 'Can manage allergen reference shells'), ('view_changeover', 'Can view allergen/changeover/line-clearance records'), ('manage_changeover', 'Can record allergen/changeover/line-clearance events'), ('verify_changeover', 'Can verify changeover / line-clearance records (QA/Food Safety)'), ('manage_allergenriskpolicy', 'Can update allergen risk / production-block policy stubs')],
            },
        ),
        migrations.CreateModel(
            name='AllergenRiskPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_enabled', models.BooleanField(default=False, help_text='When False, allergen matrix never blocks production start.')),
                ('procedure_reference', models.CharField(blank=True, default='', help_text='Opaque company SOP / matrix reference — not invented.', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='allergen_risk_policy', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allergen_risk_policies_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Allergen risk policy',
                'verbose_name_plural': 'Allergen risk policies',
            },
        ),
        migrations.CreateModel(
            name='ChangeoverRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_code', models.CharField(blank=True, default='', help_text='Opaque line identifier — Line master EVIDENCE REQUIRED.', max_length=64)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RECORDED', 'Recorded'), ('VERIFIED', 'Verified'), ('VOIDED', 'Voided')], default='RECORDED', max_length=16)),
                ('batch_reference', models.CharField(blank=True, default='', help_text='Opaque batch/dossier reference for future traceability.', max_length=128)),
                ('verification_notes', models.TextField(blank=True, default='')),
                ('evidence_object_key', models.CharField(blank=True, default='', max_length=512)),
                ('evidence_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('frozen_changeover_context', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cleaning_checklist_template', models.ForeignKey(blank=True, help_text='Preferred: reuse checklist engine for cleaning/clearance.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changeover_cleaning_refs', to='checklists.checklisttemplate')),
                ('cleaning_checklist_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changeover_cleaning_refs', to='checklists.checklistversion')),
                ('next_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changeovers_as_next', to='master_data.fgproduct')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changeover_records', to='organizations.organization')),
                ('packaging_artwork_hook', models.ForeignKey(blank=True, help_text='Optional packaging/label clearance hook from Phase 29.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changeover_records', to='packaging.lineclearanceartworkhook')),
                ('previous_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changeovers_as_previous', to='master_data.fgproduct')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changeovers_recorded', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changeovers_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Changeover record',
                'verbose_name_plural': 'Changeover records',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='LineClearanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_code', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('VOIDED', 'Voided')], default='COMPLETED', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('evidence_object_key', models.CharField(blank=True, default='', max_length=512)),
                ('frozen_clearance_context', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changeover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='line_clearances', to='changeover.changeoverrecord')),
                ('checklist_submission', models.ForeignKey(blank=True, help_text='Optional immutable submission evidence when available.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='line_clearance_records', to='recording.checklistsubmission')),
                ('checklist_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_clearance_records', to='checklists.checklisttemplate')),
                ('checklist_version', models.ForeignKey(blank=True, help_text='Exact checklist version used — historical pin.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='line_clearance_records', to='checklists.checklistversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_clearance_records', to='organizations.organization')),
                ('packaging_artwork_hook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='line_clearance_records', to='packaging.lineclearanceartworkhook')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_clearances_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Line clearance record',
                'verbose_name_plural': 'Line clearance records',
                'ordering': ('-completed_at',),
            },
        ),
        migrations.CreateModel(
            name='ChangeoverHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changeover_history_actions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changeover_history_entries', to='organizations.organization')),
                ('changeover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history_entries', to='changeover.changeoverrecord')),
                ('line_clearance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history_entries', to='changeover.lineclearancerecord')),
            ],
            options={
                'verbose_name': 'Changeover history entry',
                'verbose_name_plural': 'Changeover history entries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductAllergenDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('RETIRED', 'Retired')], default='DRAFT', max_length=16)),
                ('declaration_reference', models.CharField(blank=True, default='', help_text='Opaque company declaration / document-control reference.', max_length=255)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allergen_references', models.ManyToManyField(blank=True, help_text='Optional links — leave empty until company mapping evidenced.', related_name='product_declarations', to='changeover.allergenreference')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_allergen_declarations_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_allergen_declarations_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_allergen_declarations', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allergen_declarations', to='master_data.fgproduct')),
            ],
            options={
                'verbose_name': 'Product allergen declaration',
                'verbose_name_plural': 'Product allergen declarations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='changeoverrecord',
            name='next_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changeovers_as_next_declaration', to='changeover.productallergendeclaration'),
        ),
        migrations.AddField(
            model_name='changeoverrecord',
            name='previous_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changeovers_as_previous_declaration', to='changeover.productallergendeclaration'),
        ),
        migrations.AddConstraint(
            model_name='allergenreference',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='changeover_allergen_ref_org_code_ci_uniq'),
        ),
        migrations.AddIndex(
            model_name='lineclearancerecord',
            index=models.Index(fields=['organization', 'line_code', '-completed_at'], name='changeover__organiz_56d16c_idx'),
        ),
        migrations.AddIndex(
            model_name='changeoverrecord',
            index=models.Index(fields=['organization', 'line_code', '-started_at'], name='changeover__organiz_597adc_idx'),
        ),
        migrations.AddIndex(
            model_name='changeoverrecord',
            index=models.Index(fields=['organization', 'batch_reference'], name='changeover__organiz_edd71f_idx'),
        ),
    ]
