export const POLICY_MESSAGES: Record<string, string> = {
  ALLOWED: "Action is permitted",
  TENANT_REQUIRED: "Tenant context is required",
  VEHICLE_INACTIVE: "Vehicle is not available for operation",
  VEHICLE_IN_USE: "Vehicle is already in use",
  VEHICLE_UNDER_MAINTENANCE: "Vehicle is under maintenance",
  VEHICLE_OUT_OF_SERVICE: "Vehicle is out of service",
  VEHICLE_DISPOSED: "Vehicle is disposed",
  MAINTENANCE_CRITICALLY_OVERDUE: "Preventive maintenance is overdue",
  CRITICAL_WORK_ORDER_OPEN: "A critical work order is still open",
  COMPLIANCE_INVALID: "Mandatory compliance is not valid",
  DRIVER_INVALID: "Assigned driver is not valid for operation",
  DRIVER_LICENSE_EXPIRED: "Driver license is expired",
  OVERRIDE_UNAUTHORIZED: "Override is not authorized for this role",
  OVERRIDE_REASON_REQUIRED: "Override reason is required",
  WO_INVALID_TRANSITION: "Work order status transition is not allowed",
  WO_ASSIGNMENT_REQUIRED: "Work order requires an assigned technician",
  WO_APPROVAL_REQUIRED: "Work order is not approved for execution",
  WO_EVIDENCE_REQUIRED: "Required completion evidence is missing",
  WO_PARTS_INCOMPLETE: "Required parts are not issued or used",
  WO_SOD_VIOLATION: "Segregation of duties prevents this action",
  WO_REOPEN_UNAUTHORIZED: "Work order reopen is not authorized",
  WO_CONCURRENCY_CONFLICT: "Work order was updated by another user",
  ITEM_INACTIVE: "Item is inactive",
  WAREHOUSE_INVALID: "Warehouse is invalid or inactive",
  QUANTITY_INVALID: "Quantity must be a whole number greater than zero",
  INSUFFICIENT_STOCK: "Available stock is lower than requested quantity",
  RESERVATION_EXCEEDS_AVAILABLE: "Reservation exceeds available stock",
  ADJUSTMENT_UNAUTHORIZED: "Stock adjustment is not authorized",
  REVERSAL_ORIGINAL_MISSING: "Reversal requires the original movement",
  REVERSAL_ALREADY_APPLIED: "This movement has already been reversed",
  ERP_SOURCE_REQUIRED: "ERP source identity is required",
  ERP_DUPLICATE_PAYLOAD_MISMATCH: "Idempotency key was reused with a different payload",
  ERP_MAPPING_MISSING: "ERP item or warehouse mapping is missing",
  ERP_SOURCE_STATUS_INVALID: "ERP source status cannot be applied",
  ERP_APPLY_UNSAFE: "ERP apply is blocked until reconciliation is resolved",
  METER_ROLLBACK: "Meter reading cannot roll back",
  METER_NEGATIVE: "Meter reading cannot be negative",
  METER_FUTURE_IMPOSSIBLE: "Meter reading is impossibly far in the future",
  PM_INTERVAL_INVALID: "Preventive schedule interval is invalid",
  PM_NEXT_DUE_INVALID: "Next due point would be invalid",
  PART_INCOMPATIBLE: "Part is incompatible with the selected vehicle",
  PROCUREMENT_DUPLICATE: "An open purchase request already covers this demand",
  PROCUREMENT_NO_QUANTITY: "No purchase is required",
  USER_APPROVAL_UNAUTHORIZED: "User is not authorized to approve",
  USER_REVIEW_UNAUTHORIZED: "User is not authorized to review"
};

export function policyMessage(code: string): string {
  return POLICY_MESSAGES[code] ?? "Action is not permitted";
}
