export const POLICY_MESSAGES: Record<string, string> = {
  ALLOWED: "Action is permitted",
  TENANT_REQUIRED: "Tenant context is required",
  VEHICLE_INACTIVE: "Vehicle is not available for operation",
  VEHICLE_IN_USE: "Vehicle is already in use",
  VEHICLE_UNDER_MAINTENANCE: "Vehicle is under maintenance",
  VEHICLE_OUT_OF_SERVICE: "Vehicle is out of service",
  VEHICLE_DISPOSED: "Vehicle is disposed",
  MAINTENANCE_CRITICALLY_OVERDUE: "Preventive maintenance is overdue",
  CRITICAL_WORK_ORDER_OPEN: "A critical work order is still open",
  COMPLIANCE_INVALID: "Mandatory compliance is not valid",
  DRIVER_INVALID: "Assigned driver is not valid for operation",
  DRIVER_LICENSE_EXPIRED: "Driver license is expired",
  OVERRIDE_UNAUTHORIZED: "Override is not authorized for this role",
  OVERRIDE_REASON_REQUIRED: "Override reason is required",
  WO_INVALID_TRANSITION: "Work order status transition is not allowed",
  WO_ASSIGNMENT_REQUIRED: "Work order requires an assigned technician",
  WO_APPROVAL_REQUIRED: "Work order is not approved for execution",
  WO_EVIDENCE_REQUIRED: "Required completion evidence is missing",
  WO_PARTS_INCOMPLETE: "Required parts are not issued or used",
  WO_SOD_VIOLATION: "Segregation of duties prevents this action",
  WO_REOPEN_UNAUTHORIZED: "Work order reopen is not authorized",
  WO_CONCURRENCY_CONFLICT: "Work order was updated by another user",
  ITEM_INACTIVE: "Item is inactive",
  WAREHOUSE_INVALID: "Warehouse is invalid or inactive",
  QUANTITY_INVALID: "Quantity must be a whole number greater than zero",
  INSUFFICIENT_STOCK: "Available stock is lower than requested quantity",
  RESERVATION_EXCEEDS_AVAILABLE: "Reservation exceeds available stock",
  ADJUSTMENT_UNAUTHORIZED: "Stock adjustment is not authorized",
  REVERSAL_ORIGINAL_MISSING: "Reversal requires the original movement",
  REVERSAL_ALREADY_APPLIED: "This movement has already been reversed",
  ERP_SOURCE_REQUIRED: "ERP source identity is required",
  ERP_DUPLICATE_PAYLOAD_MISMATCH: "Idempotency key was reused with a different payload",
  ERP_MAPPING_MISSING: "ERP item or warehouse mapping is missing",
  ERP_SOURCE_STATUS_INVALID: "ERP source status cannot be applied",
  ERP_APPLY_UNSAFE: "ERP apply is blocked until reconciliation is resolved",
  METER_ROLLBACK: "Meter reading cannot roll back",
  METER_NEGATIVE: "Meter reading cannot be negative",
  METER_FUTURE_IMPOSSIBLE: "Meter reading is impossibly far in the future",
  PM_INTERVAL_INVALID: "Preventive schedule interval is invalid",
  PM_NEXT_DUE_INVALID: "Next due point would be invalid",
  PART_INCOMPATIBLE: "Part is incompatible with the selected vehicle",
  PROCUREMENT_DUPLICATE: "An open purchase request already covers this demand",
  PROCUREMENT_NO_QUANTITY: "No purchase is required",
  USER_APPROVAL_UNAUTHORIZED: "User is not authorized to approve",
  USER_REVIEW_UNAUTHORIZED: "User is not authorized to review",
  INVALID_TRANSITION: "Status transition is not allowed",
  MAKER_CHECKER_VIOLATION: "Submitter cannot approve their own request",
  APPROVAL_LIMIT_EXCEEDED: "Amount exceeds the approval limit for this role",
  TECHNICIAN_INACTIVE: "Technician is inactive",
  TECHNICIAN_NOT_DISPATCHABLE: "Technician cannot receive work orders",
  TECHNICIAN_ON_LEAVE: "Technician is on approved leave",
  TECHNICIAN_CERTIFICATION_REQUIRED: "This job requires a valid certification",
  TECHNICIAN_SKILL_MISMATCH: "Technician skills do not match the job",
  TECHNICIAN_OVER_CAPACITY: "Technician does not have remaining capacity",
  BUSINESS_APPROVAL_REQUIRED: "Hazardous work requires an approved permit or authorized override",
  BUDGET_EXCEEDED: "Requested amount exceeds available budget",
  VENDOR_INACTIVE: "Vendor is not active",
  VENDOR_BLOCKED: "Vendor is blocked",
  VENDOR_CONTRACT_EXPIRED: "Vendor contract is expired",
  VENDOR_INSURANCE_EXPIRED: "Vendor insurance is expired",
  FUEL_QUANTITY_INVALID: "Fuel quantity must be greater than zero",
  FUEL_DUPLICATE_REFERENCE: "A fuel entry with the same reference already exists",
  TRIP_CONFLICT: "An active trip already exists for this vehicle or driver",
  OFFLINE_CLIENT_ACTION_REQUIRED: "Offline mutations require a stable client action id",
  MAPPING_REQUIRED: "Master-data mapping is required before apply"
};

export function policyMessage(code: string): string {
  return POLICY_MESSAGES[code] ?? "Action is not permitted";
}
