# Generated by Django 5.2.16 on 2026-08-09 20:35

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_phase04a_shift_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NonConformanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nonconformances_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nonconformances', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Nonconformance record',
                'verbose_name_plural': 'Nonconformance records',
                'ordering': ('organization__code', 'code'),
                'permissions': [('manage_nonconformance', 'Can manage nonconformance records')],
                'indexes': [models.Index(fields=['organization', 'status'], name='ncr_org_status_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='ncr_org_code_ci_uniq')],
            },
        ),
    ]
