# Generated by Django 5.2.16 on 2026-08-10 00:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_phase04c_organization_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('INBOUND_BATCH', 'Inbound batch event'), ('OUTBOUND_DISPOSITION', 'Outbound disposition (not approved)')], max_length=32)),
                ('source_system', models.CharField(blank=True, default='', max_length=64)),
                ('idempotency_key', models.CharField(max_length=191)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('DEAD_LETTER', 'Dead letter'), ('BLOCKED', 'Blocked by evidence/policy')], default='PENDING', max_length=16)),
                ('error_class', models.CharField(blank=True, default='', max_length=32)),
                ('error_summary', models.CharField(blank=True, default='', max_length=255)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('external_batch_event_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integration_attempts', to='organizations.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integration_attempts_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integration attempt',
                'verbose_name_plural': 'Integration attempts',
                'ordering': ('-created_at',),
                'permissions': [('manage_integrationboundary', 'Can manage ERP integration boundary'), ('view_integrationboundary', 'Can view ERP integration boundary')],
                'indexes': [models.Index(fields=['status', 'created_at'], name='integ_attempt_status_at_idx'), models.Index(fields=['organization', 'status'], name='integ_attempt_org_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_system', 'idempotency_key', 'channel'), name='integ_src_idem_channel_uniq')],
            },
        ),
    ]
