import { FACILITY_PERMISSION_KEYS } from "./facility-seed.constants";

/**
 * Canonical list of every permission key the platform defines. Single
 * source of truth shared by the seed script (`apps/api/src/database/seed.ts`)
 * and the Admin Console's permission-catalog sync endpoint
 * (`AdminRolesService.syncPermissionCatalog`) — do not duplicate this list
 * elsewhere. Adding a new permission means adding its key here once.
 */
export const PERMISSION_CATALOG = [
  // Phase 1 enterprise RBAC / PBAC keys
  "dashboard.view",
  "users.view",
  "users.create",
  "users.edit",
  "users.status.manage",
  "users.delete",
  "roles.view",
  "roles.manage",
  "permissions.view",
  "permissions.create",
  "settings.view",
  "settings.organization.manage",
  "settings.system.manage",
  "audit.view",
  "qa.view",
  "qa.create",
  "qa.manage",
  "qa.accept_risk",
  "qa.export",
  "delivery.view",
  "delivery.manage",
  "delivery.accept_risk",
  "delivery.sign_off",
  "delivery.export",
  "operations.view",
  "operations.manage",
  "support.create",
  "support.manage",
  "change_request.create",
  "change_request.approve",
  "change_request.manage",
  "release.manage",
  "training.manage",
  "hypercare.manage",
  "go_live.view",
  "go_live.manage",
  "go_live.sign_off",
  "go_live.accept_risk",
  "go_live.export",
  "erp.view",
  "erp.manage",
  "erp.import",
  "erp.reconcile",
  "vehicles.view",
  "vehicles.create",
  "vehicles.edit",
  "vehicles.operate",
  "gate.out.create",
  "gate.in.create",
  "vehicles.delete",
  "gate.override.approve",
  "service.rules.manage",
  "settings.manage",

  // Backward-compatible / module-level keys already used by other modules
  "users.manage",
  "modules.view_all",
  "assets.manage",
  "work_orders.manage",
  "work_orders.update_status",
  "work_orders.view_own",
  "work_orders.plan",
  "work_orders.assign",
  "work_orders.start",
  "work_orders.hold",
  "work_orders.resume",
  "work_orders.complete",
  "work_orders.verify",
  "work_orders.close",
  "work_orders.cancel",
  "work_orders.reopen",
  "work_orders.correct",
  "planning.view",
  "planning.manage",
  "parts.view",
  "parts.issue",
  "parts.return",
  "erp.mapping.manage",
  "vendor.manage",
  "contract.manage",
  "cost.view",
  "cost.adjust",
  "approvals.view",
  "approvals.view_all",
  "approvals.decide",
  "approvals.rule.manage",
  "approvals.override.emergency",
  "part_requests.create",
  "part_requests.view",
  "part_requests.approve_operational",
  "part_requests.approve_finance",
  "part_requests.reject",
  "part_requests.issue",
  "fleet.manage",
  "fleet.log_fuel_trip",
  "inventory.manage",
  "inventory.stock_issue",
  "inventory.erp_dry_run",
  "inventory.erp_apply",
  "inventory.erp_import.view",
  "inventory.erp_import.upload",
  "inventory.erp_import.apply",
  "inventory.erp_import.history",
  "fg.access",
  "fg.recording.view",
  "fg.recording.create",
  "fg.recording.edit",
  "fg.recording.submit",
  "fg.review.view",
  "fg.review.perform",
  "fg.qa.view",
  "fg.qa.disposition",
  "fg.nonconformance.view",
  "fg.nonconformance.manage",
  "fg.capa.view",
  "fg.capa.manage",
  "fg.laboratory.view",
  "fg.laboratory.manage",
  "fg.haccp.view",
  "fg.haccp.manage",
  "fg.dispatch.view",
  "fg.dispatch.manage",
  "fg.complaints.view",
  "fg.complaints.manage",
  "fg.reports.view",
  "fg.reports.export",
  "fg.admin",
  "purchase_orders.create",
  "purchase_orders.view",
  "purchase_orders.receive",
  "purchase_orders.approve_operational",
  "purchase_orders.approve_finance",
  "purchase_orders.reject",
  "purchase_orders.erp_sync",
  "purchase_orders.erp_sync_retry",
  "reports.view",
  "reports.operations.view",
  "reports.financials.view",
  "reports.user_activity.view",
  "reports.assets.view",
  "reports.inventory.view",
  "reports.performance.view",
  "reports.system_logs.view",
  "reports.driver_intelligence.view",
  "reports.fuel.view",
  "reports.vehicle_cost.view",
  "reports.export",
  "reports.management.view",
  "utilities.manage",
  "system.configure",
  "cleaning.manage",
  "cleaning.log_visit",
  "cleaning.sign_off",
  "cleaning.report_issue",

  // Building / Facility module — BUILD-002 foundation
  ...FACILITY_PERMISSION_KEYS,

  // Phase 4 — vehicle compliance, documents, accidents, claims, fines
  "compliance.view",
  "vehicle_documents.view",
  "vehicle_documents.manage",
  "vehicle_documents.verify",
  "accidents.view",
  "accidents.report",
  "accidents.manage",
  "insurance_claims.view",
  "insurance_claims.manage",
  "insurance_claims.approve",
  "traffic_fines.view",
  "traffic_fines.report",
  "traffic_fines.manage",
  "traffic_fines.payment",

  // Phase 5 Maintenance Request permissions live in FACILITY_PERMISSION_KEYS (spread above).

  // Phase 5 — intelligence, analytics, dashboards
  "driver_intelligence.view",
  "driver_intelligence.manage",
  "dashboard_analytics.view",
  "fuel_analytics.view",
  "vehicle_cost_analytics.view",

  // Phase 6 — operational scanning
  "operations.scan_lookup",
  "predictive_insights.view",

  // Phase 10 — fleet lifecycle: vehicle, tyre, battery, assignment, accident, gate
  "fleet.view",
  "fleet.vehicle.manage",
  "fleet.service.manage",
  "fleet.inspection.perform",
  "fleet.tyre.manage",
  "fleet.battery.manage",
  "fleet.fuel.record",
  "fleet.driver.manage",
  "fleet.assignment.manage",
  "fleet.document.manage",
  "fleet.accident.manage",
  "fleet.claim.manage",
  "fleet.fine.manage",
  "gate.check",
  "gate.record",
  "gate.override",

  // Phase 11 — domain coverage: asset taxonomy domain profile read/manage
  "domains.view",
  "domains.manage",

  // Phase 12 — admin governance
  "admin.overview.view",
  "admin.dataquality.view",
  "admin.audit.view",
  "admin.system.view",
  "admin.users.manage",
  "admin.organization.manage"
];
