# Generated by Django 5.2.16 on 2026-08-06 20:28

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_phase03_accounts_rbac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='organizations.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='organizations.organization')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='organizations.site')),
            ],
            options={
                'ordering': ('organization__code', 'code', 'effective_from'),
                'permissions': [('manage_shift', 'Can manage shift')],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='org_shift_org_act_idx'), models.Index(fields=['site', 'is_active'], name='org_shift_site_act_idx'), models.Index(fields=['department', 'is_active'], name='org_shift_dept_act_idx'), models.Index(django.db.models.functions.text.Lower('code'), name='org_shift_code_lower_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), models.F('site'), models.F('department'), name='org_shift_scope_code_ci_uniq', nulls_distinct=False), models.CheckConstraint(condition=models.Q(('department__isnull', True), ('site__isnull', False), _connector='OR'), name='org_shift_department_requires_site'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='org_shift_effective_window_valid')],
            },
        ),
    ]
