import { BadRequestException, Injectable, NotFoundException } from "@nestjs/common";
import { AuditAction } from "@prisma/client";

import { rowsToCsv, writeAuditTrail } from "../../common/utils/audit-trail.util";
import { clampPage, clampPageSize } from "../../common/utils/pagination.util";
import { PrismaService } from "../../database/prisma.service";

import type { JwtPayload } from "../auth/auth.types";

interface ListAuditQuery {
  entity?: string;
  entityId?: string;
  actorId?: string;
  module?: string;
  from?: string;
  to?: string;
  page: number;
  pageSize: number;
}

@Injectable()
export class AuditService {
  constructor(private readonly prisma: PrismaService) {}

  async list(actor: JwtPayload, query: ListAuditQuery) {
    const tenantId = actor.tenantId ?? null;
    const page = clampPage(query.page);
    const pageSize = clampPageSize(query.pageSize);

    const where: Record<string, unknown> = {};
    if (tenantId) where.tenantId = tenantId;
    if (query.entity) where.entity = query.entity;
    if (query.entityId) where.entityId = query.entityId;
    if (query.actorId) where.actorId = query.actorId;
    if (query.module) where.module = query.module;

    const from = this.parseDate(query.from);
    const to = this.parseDate(query.to);
    if (from || to) {
      where.createdAt = {
        ...(from ? { gte: from } : {}),
        ...(to ? { lte: to } : {})
      };
    }

    const [items, total] = await Promise.all([
      this.prisma.auditLog.findMany({
        where,
        include: {
          actor: {
            select: { id: true, firstName: true, lastName: true, email: true }
          }
        },
        orderBy: { createdAt: "desc" },
        skip: (page - 1) * pageSize,
        take: pageSize
      }),
      this.prisma.auditLog.count({ where })
    ]);

    return {
      items,
      pagination: {
        page,
        pageSize,
        total,
        totalPages: Math.max(1, Math.ceil(total / pageSize))
      }
    };
  }

  async forEntity(
    actor: JwtPayload,
    entity: string,
    entityId: string,
    page = 1,
    pageSize = 50
  ) {
    if (!entity || !entityId) {
      throw new NotFoundException("entity and entityId are required");
    }
    return this.list(actor, { entity, entityId, page, pageSize });
  }

  async export(actor: JwtPayload, query: Omit<ListAuditQuery, "page" | "pageSize">) {
    const result = await this.list(actor, { ...query, page: 1, pageSize: 100 });
    if (result.items.length === 0) {
      throw new BadRequestException("No audit rows available to export for the selected filters.");
    }

    const rows = result.items.map((item) => ({
      id: item.id,
      createdAt: item.createdAt.toISOString(),
      actorId: item.actorId ?? "",
      actorEmail: item.actor?.email ?? "",
      module: item.module ?? "",
      entity: item.entity,
      entityId: item.entityId,
      action: item.action,
      reason: item.reason ?? ""
    }));

    const csv = rowsToCsv(
      ["id", "createdAt", "actorId", "actorEmail", "module", "entity", "entityId", "action", "reason"],
      rows,
      [
        "Report: audit-logs",
        `Generated at: ${new Date().toISOString()}`,
        `Generated by: ${actor.email ?? actor.sub ?? "unknown"}`,
        `Filters: ${JSON.stringify({
          entity: query.entity,
          entityId: query.entityId,
          actorId: query.actorId,
          module: query.module,
          from: query.from,
          to: query.to
        })}`
      ]
    );

    await writeAuditTrail(this.prisma, {
      actor,
      entity: "report",
      entityId: "audit-logs",
      action: AuditAction.UPDATE,
      module: "audit",
      reason: "report_exported",
      metadata: {
        event: "report_exported",
        reportKey: "audit-logs",
        rowCount: rows.length
      }
    });

    return {
      filename: `audit-logs-${new Date().toISOString().slice(0, 10)}.csv`,
      contentType: "text/csv; charset=utf-8",
      content: csv
    };
  }

  private parseDate(value?: string): Date | undefined {
    if (!value || value.trim().length === 0) {
      return undefined;
    }

    const parsed = new Date(value);
    if (Number.isNaN(parsed.getTime())) {
      return undefined;
    }

    return parsed;
  }
}
