# Generated by Django 5.2.16 on 2026-08-10 00:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_phase04c_organization_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_code', models.CharField(choices=[('BATCH_CHECKLIST', 'BATCH_CHECKLIST'), ('SUBMISSION_HISTORY', 'SUBMISSION_HISTORY'), ('SUPERVISOR_REVIEW', 'SUPERVISOR_REVIEW'), ('QA_DISPOSITION', 'QA_DISPOSITION'), ('CORRECTIONS', 'CORRECTIONS'), ('HOLD_NCR_CAPA', 'HOLD_NCR_CAPA'), ('OVERDUE_TASKS', 'OVERDUE_TASKS'), ('AUDIT_EVENTS', 'AUDIT_EVENTS'), ('INTEGRATION_FAILURES', 'INTEGRATION_FAILURES')], max_length=64)),
                ('export_format', models.CharField(choices=[('CSV', 'CSV')], default='CSV', max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('result_csv', models.TextField(blank=True, default='')),
                ('error_summary', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_runs', to='organizations.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_runs_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report run',
                'verbose_name_plural': 'Report runs',
                'ordering': ('-created_at',),
                'permissions': [('run_qualityreport', 'Can run governed quality reports'), ('export_qualityreport', 'Can export governed quality reports'), ('view_reportcatalogue', 'Can view quality report catalogue')],
                'indexes': [models.Index(fields=['organization', 'report_code', 'created_at'], name='reports_org_code_at_idx'), models.Index(fields=['organization', 'status'], name='reports_org_status_idx')],
            },
        ),
    ]
