# Generated by Django 5.2.16 on 2026-08-10 00:18

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformance', '0001_phase32_supplier_quality_foundation'),
        ('organizations', '0003_phase04c_organization_configuration'),
        ('recording', '0011_phase08c_recording_hardening'),
        ('scheduling', '0007_phase07h_due_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('reason_reference', models.CharField(help_text='Reason or external reference — not a company resolution catalogue code.', max_length=255)),
                ('scope', models.TextField(blank=True, default='', help_text='Free-text scope (batch/site/product/etc.) — no invented scope enums.')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('resolution', models.TextField(blank=True, default='', help_text='Free-text resolution — not a Nelna-approved resolution enum.')),
                ('batch_reference', models.CharField(blank=True, default='', max_length=128)),
                ('quantity_reference', models.CharField(blank=True, default='', help_text='Opaque future quantity/sub-lot reference — no disposition rules invented.', max_length=128)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hold case',
                'verbose_name_plural': 'Hold cases',
                'ordering': ('organization__code', 'code'),
                'permissions': [('create_holdcase', 'Can create hold cases'), ('manage_holdcase', 'Can manage hold cases'), ('close_holdcase', 'Can close hold cases')],
            },
        ),
        migrations.CreateModel(
            name='QualityCaseHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_kind', models.CharField(choices=[('NONCONFORMANCE', 'Nonconformance'), ('HOLD', 'Hold case'), ('CAPA', 'CAPA')], max_length=32)),
                ('case_id', models.UUIDField()),
                ('event_type', models.CharField(max_length=64)),
                ('from_status', models.CharField(blank=True, default='', max_length=32)),
                ('to_status', models.CharField(blank=True, default='', max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quality case history entry',
                'verbose_name_plural': 'Quality case history entries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='nonconformancerecord',
            options={'ordering': ('organization__code', 'code'), 'permissions': [('create_nonconformance', 'Can create nonconformance records'), ('manage_nonconformance', 'Can manage nonconformance records'), ('close_nonconformance', 'Can close nonconformance records')], 'verbose_name': 'Nonconformance record', 'verbose_name_plural': 'Nonconformance records'},
        ),
        migrations.AddField(
            model_name='nonconformancerecord',
            name='batch_reference',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='nonconformancerecord',
            name='checklist_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nonconformances', to='recording.checklistsubmission'),
        ),
        migrations.AddField(
            model_name='nonconformancerecord',
            name='checklist_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nonconformances', to='scheduling.checklisttask'),
        ),
        migrations.AddField(
            model_name='nonconformancerecord',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonconformancerecord',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nonconformances_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nonconformancerecord',
            name='closure_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='nonconformancerecord',
            name='containment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='nonconformancerecord',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='nonconformancerecord',
            name='investigation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='nonconformancerecord',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nonconformances_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nonconformancerecord',
            name='quantity_reference',
            field=models.CharField(blank=True, default='', help_text='Opaque future quantity/sub-lot reference — no disposition rules invented.', max_length=128),
        ),
        migrations.AddField(
            model_name='nonconformancerecord',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('CHECKLIST_SUBMISSION', 'Checklist submission reference'), ('QA_REVIEW', 'QA review reference'), ('OTHER', 'Other (opaque reference)')], default='MANUAL', max_length=32),
        ),
        migrations.AlterField(
            model_name='nonconformancerecord',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('ACTION_REQUIRED', 'Action required'), ('VERIFICATION', 'Verification'), ('CLOSED', 'Closed')], default='OPEN', max_length=32),
        ),
        migrations.AddIndex(
            model_name='nonconformancerecord',
            index=models.Index(fields=['organization', 'batch_reference'], name='ncr_org_batch_idx'),
        ),
        migrations.AddField(
            model_name='holdcase',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hold_cases_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holdcase',
            name='nonconformance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hold_cases', to='nonconformance.nonconformancerecord'),
        ),
        migrations.AddField(
            model_name='holdcase',
            name='opened_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hold_cases_opened', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holdcase',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hold_cases', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='holdcase',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hold_cases_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualitycasehistoryentry',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_case_history_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualitycasehistoryentry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_case_history', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='holdcase',
            index=models.Index(fields=['organization', 'status'], name='hold_org_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='holdcase',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='hold_org_code_ci_uniq'),
        ),
        migrations.AddIndex(
            model_name='qualitycasehistoryentry',
            index=models.Index(fields=['organization', 'case_kind', 'case_id', 'created_at'], name='qch_org_case_created_idx'),
        ),
    ]
