# Generated by Django 5.2.16 on 2026-08-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phase03_security_fix'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='acct_user_emp_code_ci_uniq',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='acct_user_emp_code_idx',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['employee_code'], name='acct_user_emp_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_code__isnull', False)), fields=('employee_code',), name='acct_user_emp_code_ci_uniq'),
        ),
    ]
