# Generated by Django 5.2.16 on 2026-08-13 04:33

from django.db import migrations, models


def normalize_existing_employee_codes(apps, schema_editor):
    """Normalize existing employee codes to uppercase before applying unique constraint."""
    User = apps.get_model('accounts', 'User')
    for user in User.objects.exclude(employee_code__isnull=True):
        normalized = user.employee_code.strip().upper()
        if user.employee_code != normalized:
            user.employee_code = normalized
            user.save(update_fields=['employee_code'])


def reverse_normalize(apps, schema_editor):
    """No-op reverse migration."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phase03_security_fix'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='acct_user_emp_code_ci_uniq',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='acct_user_emp_code_idx',
        ),
        migrations.RunPython(normalize_existing_employee_codes, reverse_normalize),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['employee_code'], name='acct_user_emp_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_code__isnull', False)), fields=('employee_code',), name='acct_user_emp_code_ci_uniq'),
        ),
    ]
