# Generated by Django 5.2.16 on 2026-08-10 05:27

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_phase04c_organization_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerComplaintCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Opaque complaint ID.', max_length=64)),
                ('received_at', models.DateTimeField()),
                ('channel_reference', models.CharField(blank=True, default='', help_text='Opaque intake channel / procedure reference.', max_length=128)),
                ('erp_customer_reference', models.CharField(blank=True, default='', help_text='ERP customer master key — SoR for customer identity.', max_length=128)),
                ('customer_display_label', models.CharField(blank=True, default='', help_text='Optional non-PII label; sensitive reveal requires dedicated permission.', max_length=128)),
                ('product_reference', models.CharField(blank=True, default='', max_length=128)),
                ('batch_reference', models.CharField(blank=True, default='', help_text='Opaque batch/lot if known — empty when unknown.', max_length=128)),
                ('batch_known', models.BooleanField(default=False, help_text='True when batch_reference was provided at intake or confirmed later.')),
                ('description', models.TextField()),
                ('category_reference', models.CharField(blank=True, default='', help_text='Configurable category reference — not a seeded taxonomy.', max_length=128)),
                ('severity_reference', models.CharField(blank=True, default='', help_text='Configurable severity reference — EVIDENCE REQUIRED.', max_length=128)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('PENDING_RESPONSE', 'Pending response'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=32)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_complaints_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_complaints_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_complaint_cases', to='organizations.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_complaints_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer complaint case',
                'verbose_name_plural': 'Customer complaint cases',
                'permissions': [('view_customercomplaint', 'Can view customer complaint cases'), ('create_customercomplaint', 'Can create customer complaint cases'), ('manage_customercomplaint', 'Can update complaint investigation and links'), ('close_customercomplaint', 'Can close customer complaint cases'), ('view_complaint_customer_sensitive', 'Can view customer-sensitive labels on complaints (privacy-restricted)'), ('record_complaint_communication', 'Can record complaint communication references'), ('manage_complaintpolicy', 'Can manage complaint policy stubs')],
            },
        ),
        migrations.CreateModel(
            name='CustomerComplaintBatchTrace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_reference', models.CharField(blank=True, default='', max_length=128)),
                ('dossier_batch_reference', models.CharField(blank=True, default='', help_text='Phase 35 dossier lookup key — usually same as batch_reference.', max_length=128)),
                ('genealogy_node_id', models.UUIDField(blank=True, null=True)),
                ('qa_disposition_reference', models.CharField(blank=True, default='', help_text='Opaque QA disposition / review reference.', max_length=128)),
                ('qa_review_id', models.UUIDField(blank=True, null=True)),
                ('lab_sample_id', models.UUIDField(blank=True, null=True)),
                ('lab_sample_reference', models.CharField(blank=True, default='', max_length=128)),
                ('dispatch_record_id', models.UUIDField(blank=True, null=True)),
                ('dispatch_reference', models.CharField(blank=True, default='', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaint_batch_traces_updated', to=settings.AUTH_USER_MODEL)),
                ('complaint_case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='batch_trace', to='customer_complaints.customercomplaintcase')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerComplaintCategoryConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(help_text='CATEGORY or SEVERITY — technical discriminator only.', max_length=32)),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_complaint_category_configs', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_category_configs_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerComplaintCommunication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=128)),
                ('channel_reference', models.CharField(blank=True, default='', max_length=128)),
                ('audience_reference', models.CharField(blank=True, default='', help_text='Opaque audience label — no customer PII invent.', max_length=128)),
                ('evidence_attachment_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communications', to='customer_complaints.customercomplaintcase')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_communications_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='CustomerComplaintEvidenceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_attachment_id', models.UUIDField()),
                ('notes', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_links', to='customer_complaints.customercomplaintcase')),
                ('linked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_evidence_links_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerComplaintInvestigationLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_kind', models.CharField(choices=[('INVESTIGATION', 'Investigation reference'), ('RCA', 'Root-cause analysis reference'), ('NCR', 'Nonconformance'), ('CAPA', 'Corrective / preventive action')], max_length=32)),
                ('reference', models.CharField(blank=True, default='', help_text='Opaque investigation/RCA reference when no NCR/CAPA id.', max_length=128)),
                ('nonconformance_id', models.UUIDField(blank=True, null=True)),
                ('corrective_action_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('explicit_user_action', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investigation_links', to='customer_complaints.customercomplaintcase')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_investigation_links_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='CustomerComplaintPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_response_auto_send_enabled', models.BooleanField(default=False, help_text='Org stub only — still requires COMPLAINT_CUSTOMER_RESPONSE_AUTO_SEND_APPROVED.')),
                ('procedure_reference', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer_complaint_policy', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_complaint_policies_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer complaint policy',
                'verbose_name_plural': 'Customer complaint policies',
            },
        ),
        migrations.CreateModel(
            name='CustomerComplaintTimelineEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=512)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaint_timeline_entries', to=settings.AUTH_USER_MODEL)),
                ('complaint_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeline_entries', to='customer_complaints.customercomplaintcase')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='customercomplaintcase',
            index=models.Index(fields=['organization', 'status'], name='customer_co_organiz_272a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='customercomplaintcase',
            index=models.Index(fields=['organization', 'code'], name='customer_co_organiz_220cb2_idx'),
        ),
        migrations.AddIndex(
            model_name='customercomplaintcase',
            index=models.Index(fields=['organization', 'batch_reference'], name='customer_co_organiz_fdd1b2_idx'),
        ),
        migrations.AddIndex(
            model_name='customercomplaintcase',
            index=models.Index(fields=['organization', 'erp_customer_reference'], name='customer_co_organiz_4e78bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='customercomplaintcase',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='complaint_case_org_code_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='customercomplaintcategoryconfig',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), models.F('kind'), name='complaint_category_org_kind_code_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='customercomplaintevidencelink',
            constraint=models.UniqueConstraint(fields=('complaint_case', 'evidence_attachment_id'), name='complaint_evidence_case_attachment_uniq'),
        ),
        migrations.AddIndex(
            model_name='customercomplaintinvestigationlink',
            index=models.Index(fields=['complaint_case', 'link_kind'], name='customer_co_complai_cb2869_idx'),
        ),
        migrations.AddIndex(
            model_name='customercomplainttimelineentry',
            index=models.Index(fields=['complaint_case', 'created_at'], name='customer_co_complai_db3a0f_idx'),
        ),
    ]
