# Generated by Django 5.2.16 on 2026-08-10 06:07

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_phase04c_organization_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityQuarantinePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_recording_enabled', models.BooleanField(default=False)),
                ('erp_sync_enabled', models.BooleanField(default=False, help_text='Organization gate only; settings approval and approved adapter evidence are required.')),
                ('procedure_reference', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='quality_quarantine_policy', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_quarantine_policies_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'quality quarantine policy stub',
                'verbose_name_plural': 'quality quarantine policy stubs',
            },
        ),
        migrations.CreateModel(
            name='QualityQuarantineRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=128)),
                ('batch_reference', models.CharField(max_length=128)),
                ('sub_lot_reference', models.CharField(blank=True, default='', max_length=128)),
                ('quantity_reference', models.CharField(blank=True, default='', max_length=128)),
                ('uom_reference', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(choices=[('QA_HOLD', 'QA hold'), ('RETURNED_PRODUCT', 'Returned product'), ('INCOMING_INSPECTION', 'Incoming inspection'), ('LAB_PENDING', 'Laboratory pending'), ('NCR', 'Nonconformance'), ('MANUAL', 'Manual')], max_length=32)),
                ('source_reference', models.CharField(max_length=128)),
                ('reason_reference', models.CharField(max_length=255)),
                ('opened_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RELEASED', 'Released'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=16)),
                ('resolution_reference', models.CharField(blank=True, default='', max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('erp_sync_status', models.CharField(choices=[('NOT_SENT', 'Not sent'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='NOT_SENT', max_length=16)),
                ('erp_sync_detail', models.TextField(blank=True, default='')),
                ('not_inventory_ledger', models.BooleanField(default=True, editable=False, help_text='Invariant: this app records quality state and is never the inventory ledger.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_quarantines_opened', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_quarantine_records', to='organizations.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_quarantines_owned', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_quarantines_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-opened_at', '-created_at'),
                'permissions': [('view_qualityquarantine', 'Can view quality quarantine records'), ('manage_qualityquarantine', 'Can manage quality quarantine records'), ('release_qualityquarantine', 'Can release quality quarantine records'), ('manage_quarantinepolicystub', 'Can manage quality quarantine policy stubs')],
            },
        ),
        migrations.CreateModel(
            name='QualityQuarantineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_quarantine_events', to=settings.AUTH_USER_MODEL)),
                ('quarantine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='quality_quarantine.qualityquarantinerecord')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='qualityquarantinerecord',
            index=models.Index(fields=['organization', 'status'], name='quality_quar_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityquarantinerecord',
            index=models.Index(fields=['organization', 'batch_reference'], name='quality_quar_org_batch_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityquarantinerecord',
            index=models.Index(fields=['organization', 'source', 'source_reference'], name='quality_quar_org_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualityquarantinerecord',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='quality_quarantine_code_org_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='qualityquarantinerecord',
            constraint=models.CheckConstraint(condition=models.Q(('not_inventory_ledger', True)), name='quality_quarantine_not_ledger'),
        ),
        migrations.AddIndex(
            model_name='qualityquarantineevent',
            index=models.Index(fields=['quarantine', 'created_at'], name='quality_quar_event_idx'),
        ),
    ]
