# Generated by Django 5.2.16 on 2026-08-11 03:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nonconformance', '0002_phase12_ncr_hold_capa_foundation'),
        ('organizations', '0003_phase04c_organization_configuration'),
        ('quality', '0001_phase10a_qa_review'),
        ('scheduling', '0007_phase07h_due_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReworkCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_batch_reference', models.CharField(help_text='Original finished-good batch reference (genealogy parent).', max_length=128)),
                ('source_sublot_reference', models.CharField(blank=True, default='', max_length=128)),
                ('source_quantity_reference', models.CharField(max_length=64)),
                ('source_uom_reference', models.CharField(max_length=32)),
                ('remaining_source_quantity_reference', models.CharField(blank=True, default='', max_length=64)),
                ('resulting_quantity_reference', models.CharField(blank=True, default='', max_length=64)),
                ('reason_reference', models.CharField(max_length=255)),
                ('instruction_reference', models.CharField(blank=True, default='', max_length=255)),
                ('resulting_batch_reference', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('AUTHORIZED', 'Authorized'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16)),
                ('execution_key', models.CharField(max_length=128)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorized_rework_cases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_rework_cases', to=settings.AUTH_USER_MODEL)),
                ('inspection_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rework_cases', to='scheduling.checklisttask')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rework_cases', to='organizations.organization')),
                ('source_hold_case', models.ForeignKey(blank=True, help_text='Optional pointer to original HOLD — never mutated by rework.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rework_cases_as_source', to='nonconformance.holdcase')),
                ('source_ncr', models.ForeignKey(blank=True, help_text='Optional pointer to original NCR — never mutated by rework.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rework_cases_as_source', to='nonconformance.nonconformancerecord')),
                ('source_qa_review', models.ForeignKey(blank=True, help_text='Optional pointer to original QA review — never mutated by rework.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rework_cases_as_source', to='quality.qareview')),
            ],
            options={
                'verbose_name': 'Rework case',
                'verbose_name_plural': 'Rework cases',
                'ordering': ('-created_at',),
                'permissions': [('view_reworkcase', 'Can view rework cases'), ('create_reworkcase', 'Can create rework cases'), ('authorize_reworkcase', 'Can authorize rework cases'), ('execute_reworkcase', 'Can execute rework cases'), ('manage_reworkpolicystub', 'Can manage rework policy stubs')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ReworkCaseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('AUTHORIZED', 'Authorized'), ('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REINSPECTION_OPENED', 'Reinspection opened'), ('GENEALOGY_RECORDED', 'Genealogy recorded'), ('ERP_SYNC_STUBBED', 'ERP sync stubbed')], max_length=32)),
                ('detail_reference', models.CharField(blank=True, default='', max_length=255)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rework_case_events', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rework.reworkcase')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rework_case_events', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Rework case event',
                'verbose_name_plural': 'Rework case events',
                'ordering': ('occurred_at',),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ReworkPolicyStub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_key', models.CharField(max_length=64)),
                ('policy_value_reference', models.CharField(max_length=255)),
                ('erp_stock_movement_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rework_policy_stubs', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_rework_policy_stubs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rework policy stub',
                'verbose_name_plural': 'Rework policy stubs',
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='reworkcase',
            index=models.Index(fields=['organization', 'status'], name='rework_case_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reworkcase',
            index=models.Index(fields=['organization', 'source_batch_reference'], name='rework_case_org_src_batch_idx'),
        ),
        migrations.AddConstraint(
            model_name='reworkcase',
            constraint=models.UniqueConstraint(fields=('organization', 'execution_key'), name='rework_case_org_execution_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='reworkpolicystub',
            constraint=models.UniqueConstraint(fields=('organization', 'policy_key'), name='rework_policy_org_key_uniq'),
        ),
    ]
