# Generated by Django 5.2.16 on 2026-08-10 00:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capa', '0002_phase32_supplier_quality_foundation'),
        ('organizations', '0003_phase04c_organization_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correctiveaction',
            options={'ordering': ('organization__code', 'code'), 'permissions': [('create_capa', 'Can create CAPA records'), ('manage_capa', 'Can manage CAPA records'), ('close_capa', 'Can close CAPA records')], 'verbose_name': 'Corrective action', 'verbose_name_plural': 'Corrective actions'},
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='closure_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='due_date',
            field=models.DateField(blank=True, help_text='Optional CAPA-level due date — not a Nelna SLA fact.', null=True),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='effectiveness_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='effectiveness_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='effectiveness_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capa_effectiveness_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capa_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='verification_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capa_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('VERIFICATION', 'Verification'), ('EFFECTIVENESS_REVIEW', 'Effectiveness review'), ('CLOSED', 'Closed')], default='OPEN', max_length=32),
        ),
        migrations.CreateModel(
            name='CapaActionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=16)),
                ('completion_notes', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_items', to='capa.correctiveaction')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capa_action_items_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CAPA action item',
                'verbose_name_plural': 'CAPA action items',
                'ordering': ('due_date', 'created_at'),
                'indexes': [models.Index(fields=['capa', 'status'], name='capa_action_status_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['organization', 'due_date'], name='capa_org_due_idx'),
        ),
        migrations.CreateModel(
            name='CapaHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('from_status', models.CharField(blank=True, default='', max_length=32)),
                ('to_status', models.CharField(blank=True, default='', max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capa_history_actions', to=settings.AUTH_USER_MODEL)),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_entries', to='capa.correctiveaction')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capa_history', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'CAPA history entry',
                'verbose_name_plural': 'CAPA history entries',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'capa', 'created_at'], name='capa_hist_org_capa_idx')],
            },
        ),
    ]
