# Generated by Django 5.2.16 on 2026-08-06 13:30

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('code',),
                'indexes': [models.Index(fields=['is_active'], name='org_org_active_idx'), models.Index(django.db.models.functions.text.Lower('code'), name='org_org_code_lower_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='org_organization_code_ci_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='organizations.organization')),
            ],
            options={
                'ordering': ('organization__code', 'code'),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='organizations.organization')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='organizations.site')),
            ],
            options={
                'ordering': ('organization__code', 'code'),
            },
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['organization', 'is_active'], name='org_site_org_act_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(django.db.models.functions.text.Lower('code'), name='org_site_code_lower_idx'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='org_site_org_code_ci_uniq'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['organization', 'is_active'], name='org_dept_org_act_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['site', 'is_active'], name='org_dept_site_act_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(django.db.models.functions.text.Lower('code'), name='org_dept_code_lower_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), condition=models.Q(('site__isnull', True)), name='org_dept_org_code_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('site'), condition=models.Q(('site__isnull', False)), name='org_dept_site_code_ci_uniq'),
        ),
    ]
