# Generated by Django 5.2.16 on 2026-08-09 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_phase04a_shift_foundation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('organization__code', 'code'), 'permissions': [('manage_department', 'Can manage department')]},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('code',), 'permissions': [('manage_organization', 'Can manage organization')]},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ('organization__code', 'code'), 'permissions': [('manage_site', 'Can manage site')]},
        ),
    ]
