# Generated by Django 5.2.16 on 2026-08-10 04:38

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_phase04c_organization_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenealogyNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('RAW_MATERIAL_LOT', 'Raw material lot'), ('SUPPLIER_LOT', 'Supplier lot'), ('PRODUCTION_BATCH', 'Production batch'), ('REWORK_BATCH', 'Rework batch'), ('FG_BATCH', 'Finished goods batch'), ('SUB_LOT_PALLET', 'Sub-lot / pallet'), ('SHIPMENT_CUSTOMER', 'Shipment / customer reference')], max_length=32)),
                ('external_key', models.CharField(help_text='Opaque ERP/external lot/batch/shipment key — not invented.', max_length=128)),
                ('display_label', models.CharField(blank=True, default='', max_length=255)),
                ('supplier_reference', models.CharField(blank=True, default='', max_length=128)),
                ('customer_reference', models.CharField(blank=True, default='', max_length=128)),
                ('receipt_reference', models.CharField(blank=True, default='', max_length=128)),
                ('product_reference', models.CharField(blank=True, default='', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_genealogy_nodes', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Genealogy node',
                'verbose_name_plural': 'Genealogy nodes',
                'permissions': [('view_batchgenealogy', 'Can view batch genealogy traces'), ('ingest_batchgenealogy', 'Can ingest ERP genealogy edges'), ('view_genealogy_partner', 'Can view supplier/customer genealogy refs'), ('manage_batchgenealogypolicy', 'Can manage genealogy policy stubs')],
            },
        ),
        migrations.CreateModel(
            name='GenealogyEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation', models.CharField(choices=[('CONSUMED_INTO', 'Consumed into'), ('PRODUCED_AS', 'Produced as'), ('REWORKED_FROM', 'Reworked from (parent → rework child)'), ('PACKED_AS', 'Packed as sub-lot/pallet'), ('SHIPPED_AS', 'Shipped as')], max_length=32)),
                ('source_system', models.CharField(max_length=64)),
                ('source_event_id', models.CharField(max_length=128)),
                ('integration_attempt_id', models.UUIDField(blank=True, null=True)),
                ('external_batch_event_id', models.UUIDField(blank=True, null=True)),
                ('quantity_reference', models.CharField(blank=True, default='', help_text='Opaque quantity/UOM reference from ERP — no invented math.', max_length=128)),
                ('is_rework', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_genealogy_edges_ingested', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_genealogy_edges', to='organizations.organization')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_edges', to='batch_genealogy.genealogynode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_edges', to='batch_genealogy.genealogynode')),
            ],
            options={
                'verbose_name': 'Genealogy edge',
                'verbose_name_plural': 'Genealogy edges',
            },
        ),
        migrations.CreateModel(
            name='GenealogyPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mongo_projection_enabled', models.BooleanField(default=False, help_text='Org stub only — still requires BATCH_GENEALOGY_MONGO_PROJECTION_APPROVED.')),
                ('max_trace_depth', models.PositiveIntegerField(default=25, help_text='Technical bound only — not a company SLA invent.')),
                ('procedure_reference', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='batch_genealogy_policy', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_genealogy_policies_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Genealogy policy',
                'verbose_name_plural': 'Genealogy policies',
            },
        ),
        migrations.AddIndex(
            model_name='genealogynode',
            index=models.Index(fields=['organization', 'kind'], name='batch_genea_organiz_685709_idx'),
        ),
        migrations.AddIndex(
            model_name='genealogynode',
            index=models.Index(fields=['organization', 'external_key'], name='batch_genea_organiz_76bcc2_idx'),
        ),
        migrations.AddConstraint(
            model_name='genealogynode',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('external_key'), models.F('organization'), models.F('kind'), name='batch_gen_node_org_kind_key_ci_uniq'),
        ),
        migrations.AddIndex(
            model_name='genealogyedge',
            index=models.Index(fields=['organization', 'from_node'], name='batch_genea_organiz_13bb58_idx'),
        ),
        migrations.AddIndex(
            model_name='genealogyedge',
            index=models.Index(fields=['organization', 'to_node'], name='batch_genea_organiz_26a2db_idx'),
        ),
        migrations.AddIndex(
            model_name='genealogyedge',
            index=models.Index(fields=['organization', 'relation'], name='batch_genea_organiz_30cb72_idx'),
        ),
        migrations.AddIndex(
            model_name='genealogyedge',
            index=models.Index(fields=['organization', 'is_rework'], name='batch_genea_organiz_d70212_idx'),
        ),
        migrations.AddConstraint(
            model_name='genealogyedge',
            constraint=models.UniqueConstraint(fields=('organization', 'source_system', 'source_event_id'), name='batch_gen_edge_org_source_event_uniq'),
        ),
        migrations.AddConstraint(
            model_name='genealogyedge',
            constraint=models.CheckConstraint(condition=models.Q(('from_node', models.F('to_node')), _negated=True), name='batch_gen_edge_no_self_loop'),
        ),
    ]
