name: maintainpro_mobile
description: MaintainPro - Operations Excellence. Enterprise facility & fleet management.
publish_to: "none"
version: 1.2.0+2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^2.6.1

  # Networking
  dio: ^5.7.0

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.2

  # Scanning & camera
  mobile_scanner: ^6.0.6
  image_picker: ^1.1.2
  file_picker: ^8.1.4

  # Firebase
  firebase_core: ^3.8.1
  firebase_messaging: ^15.2.3
  flutter_local_notifications: ^18.0.1

  # Routing
  go_router: ^14.6.2

  # Utils & i18n
  intl: ^0.19.0
  uuid: ^4.5.1
  path_provider: ^2.1.4
  share_plus: ^10.1.2
  url_launcher: ^6.3.1
  package_info_plus: ^8.1.2

  # Network awareness & sockets
  socket_io_client: ^3.0.1
  connectivity_plus: ^6.1.0

  # Location & maps
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.9.0

  # UI & UX
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  lottie: ^3.1.3
  flutter_animate: ^4.5.0
  fl_chart: ^0.69.0
  syncfusion_flutter_charts: ^27.1.58
  table_calendar: ^3.1.2
  pull_to_refresh_flutter3: ^2.0.2
  infinite_scroll_pagination: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
